import type {ProposalBranding,ProposalCommercialTerms,ProposalContentBlock,ProposalCustomer,ProposalMetricSelection,ProposalSectionConfig,ProposalValidity} from './types';
export const DEFAULT_BRANDING:ProposalBranding={companyDisplayName:'Helio Solar Engineering',primaryColor:'#0b3154',accentColor:'#10a6a0',secondaryColor:'#e9f2f7',footerText:'Solar proposal · Planning estimate',website:'',phone:'',email:'',legalDisclaimer:'Technical and financial results are planning estimates based on the project assumptions stated in this proposal. Actual utility bills, production and financial outcomes may vary.',coverTagline:'Engineering-led solar proposal'};
export const DEFAULT_CUSTOMER:ProposalCustomer={customerName:'Mariana Torres',contactName:'',projectName:'Residencia Montebello',siteAddress:'C. 21 184, Montebello, Mérida, Yuc.',siteCityState:'Mérida, Yucatán',tariffLabel:'CFE DAC',proposalDate:'2026-09-10',advisorName:'',advisorTitle:'Solar advisor',advisorContact:''};
export const DEFAULT_VALIDITY:ProposalValidity={validityDays:15,validUntil:'2026-09-25'};
export const DEFAULT_TERMS:ProposalCommercialTerms={paymentTerms:'Payment terms to be confirmed in the commercial agreement.',scheduleText:'Installation schedule and lead time will be confirmed after technical review, material availability and required customer approvals.',customerResponsibilities:'Customer to provide safe site access and accurate service/property information required for final engineering and installation.',utilityCaveat:'Utility interconnection, meter changes and final approval remain subject to the applicable utility process; this proposal does not represent CFE approval.'};
export const DEFAULT_METRICS:ProposalMetricSelection={showDcAcRatio:false,showSpecificYield:false,showNpv:true,showIrr:true,showCashflowChart:true};
const s=(key:ProposalSectionConfig['key'],title:string,order:number,required=false,visible=true):ProposalSectionConfig=>({key,title,order,required,visible});
export const DEFAULT_SECTIONS:ProposalSectionConfig[]=[s('cover','Cover',1,true),s('executive-summary','Proposed solution',2,true),s('consumption','Current electricity consumption',3,true),s('system','Proposed PV system',4,true),s('design','Solar design',5,true),s('production','Estimated energy production',6,true),s('coverage','Consumption vs production',7,false),s('equipment','Selected equipment',8,true),s('investment','Investment',9,true),s('financial','Financial return',10,true),s('assumptions','Assumptions & methodology',11,true),s('scope','Scope / inclusions',12,true),s('exclusions','Exclusions',13,true),s('warranties','Warranties',14,true),s('terms','Commercial terms',15,true),s('next-steps','Next steps',16,false),s('disclaimers','Disclaimers',17,true)];
export const DEFAULT_CONTENT_BLOCKS:ProposalContentBlock[]=[
{id:'summary',key:'executive-summary',title:'Proposed solution',body:'',templateContent:true},
{id:'assumptions',key:'assumptions',title:'Assumptions & methodology',body:'Energy and financial results are estimates derived from the accepted project inputs and assumptions summarized in this document. Production is a deterministic planning estimate rather than an hourly bankable simulation.',templateContent:true},
{id:'scope',key:'scope',title:'Included scope',body:'Supply and installation of the photovoltaic equipment identified in this proposal, standard mounting, electrical integration represented by the accepted project design, commissioning and basic handover documentation.',templateContent:true},
{id:'exclusions',key:'exclusions',title:'Exclusions',body:'Structural remediation, concealed electrical upgrades, civil works beyond normal installation, utility charges, permits or third-party works not expressly included are excluded unless added in writing.',templateContent:true},
{id:'warranties',key:'warranties',title:'Warranties',body:'Warranty terms must be entered and verified by the proposing company before issue. No manufacturer warranty duration or certification is inferred from product names in this proposal.',templateContent:true},
{id:'next',key:'next-steps',title:'Next steps',body:'Confirm commercial terms, authorize final site/engineering review and coordinate the installation schedule. Acceptance/signature workflow is outside this proposal version.',templateContent:true},
{id:'disclaimer',key:'disclaimer',title:'Important notice',body:'Estimated production, savings, payback, IRR and NPV are not guarantees. Actual performance depends on site conditions, consumption behavior, utility billing, equipment operation and future economic assumptions.',templateContent:true}
];
