import type {ProposalBranding,ProposalCommercialTerms,ProposalContentBlock,ProposalCustomer,ProposalMetricSelection,ProposalSectionConfig,ProposalValidity} from './types';
export const DEFAULT_BRANDING:ProposalBranding={companyDisplayName:'Buenos días sol by Enertika',primaryColor:'#0295BF',accentColor:'#0780AD',secondaryColor:'#007FB8',footerText:'Buenos días sol by Enertika · Energía que conecta.',website:'',phone:'',email:'',legalDisclaimer:'Los resultados técnicos y financieros son estimaciones de planeación basadas en los supuestos documentados del proyecto. La producción, el recibo eléctrico y los resultados financieros reales pueden variar.',coverTagline:'Energía que conecta.'};
export const DEFAULT_CUSTOMER:ProposalCustomer={customerName:'Mariana Torres',contactName:'',projectName:'Residencia Montebello',siteAddress:'C. 21 184, Montebello, Mérida, Yuc.',siteCityState:'Mérida, Yucatán',tariffLabel:'CFE DAC',proposalDate:'2026-09-10',advisorName:'',advisorTitle:'Asesor solar',advisorContact:''};
export const DEFAULT_VALIDITY:ProposalValidity={validityDays:15,validUntil:'2026-09-25'};
export const DEFAULT_TERMS:ProposalCommercialTerms={paymentTerms:'Las condiciones de pago se confirmarán en el acuerdo comercial.',scheduleText:'El calendario y plazo de instalación se confirmarán después de la revisión técnica, disponibilidad de materiales y autorizaciones requeridas.',customerResponsibilities:'El cliente deberá proporcionar acceso seguro al sitio e información correcta del servicio y del inmueble para la ingeniería e instalación final.',utilityCaveat:'La interconexión, cambio de medidor y aprobación final están sujetos al proceso de la compañía suministradora; esta propuesta no representa aprobación de CFE.'};
export const DEFAULT_METRICS:ProposalMetricSelection={showDcAcRatio:false,showSpecificYield:false,showNpv:true,showIrr:true,showCashflowChart:true};
const s=(key:ProposalSectionConfig['key'],title:string,order:number,required=false,visible=true):ProposalSectionConfig=>({key,title,order,required,visible});
export const DEFAULT_SECTIONS:ProposalSectionConfig[]=[s('cover','Portada',1,true),s('executive-summary','Solución propuesta',2,true),s('consumption','Consumo eléctrico actual',3,true),s('system','Sistema FV propuesto',4,true),s('design','Diseño solar',5,true),s('production','Producción energética estimada',6,true),s('coverage','Consumo vs producción',7,false),s('equipment','Equipos seleccionados',8,true),s('investment','Inversión',9,true),s('financial','Retorno financiero',10,true),s('assumptions','Supuestos y metodología',11,true),s('scope','Alcance / inclusiones',12,true),s('exclusions','Exclusiones',13,true),s('warranties','Garantías',14,true),s('terms','Condiciones comerciales',15,true),s('next-steps','Siguientes pasos',16,false),s('disclaimers','Avisos importantes',17,true)];
export const DEFAULT_CONTENT_BLOCKS:ProposalContentBlock[]=[
{id:'summary',key:'executive-summary',title:'Solución propuesta',body:'',templateContent:true},
{id:'assumptions',key:'assumptions',title:'Supuestos y metodología',body:'Los resultados energéticos y financieros son estimaciones derivadas de las entradas y supuestos aceptados del proyecto. La producción es una estimación determinística de planeación y no una simulación horaria bancable.',templateContent:true},
{id:'scope',key:'scope',title:'Alcance incluido',body:'Suministro e instalación del equipo fotovoltaico identificado en esta propuesta, montaje estándar, integración eléctrica representada por el diseño aceptado, puesta en marcha y documentación básica de entrega.',templateContent:true},
{id:'exclusions',key:'exclusions',title:'Exclusiones',body:'Correcciones estructurales, adecuaciones eléctricas ocultas, obra civil fuera de la instalación normal, cargos de la compañía suministradora, permisos o trabajos de terceros no incluidos expresamente quedan fuera salvo que se agreguen por escrito.',templateContent:true},
{id:'warranties',key:'warranties',title:'Garantías',body:'Las garantías deberán ser capturadas y verificadas por la empresa proponente antes de emitir la propuesta. No se infiere duración de garantía ni certificación por el nombre de los equipos.',templateContent:true},
{id:'next',key:'next-steps',title:'Siguientes pasos',body:'Confirmar condiciones comerciales, autorizar la revisión final del sitio e ingeniería y coordinar el calendario de instalación. El flujo de aceptación/firma queda fuera de esta versión.',templateContent:true},
{id:'disclaimer',key:'disclaimer',title:'Aviso importante',body:'La producción, ahorro, retorno, TIR y VPN estimados no son garantías. El desempeño real depende del sitio, hábitos de consumo, facturación eléctrica, operación de equipos y supuestos económicos futuros.',templateContent:true}
];
