import type {ProposalDocumentModel,ProposalDocumentSection,ProposalSectionKey,ProposalVersion} from './types';
import {INTERNAL_ONLY_FIELDS} from './metrics';
function block(v:ProposalVersion,key:string){return v.contentBlocks.find(x=>x.key===key)?.body||'';}
export function buildProposalDocumentModel(v:ProposalVersion):ProposalDocumentModel{const s=v.snapshot;const payloads:Record<ProposalSectionKey,Record<string,unknown>>={
cover:{tagline:v.branding.coverTagline,customer:v.customer.customerName,project:v.customer.projectName,address:v.customer.siteAddress,proposalDate:v.customer.proposalDate,validUntil:v.validity.validUntil},
'executive-summary':{body:block(v,'executive-summary')},
consumption:{tariff:s.consumption.tariff,siteType:s.consumption.siteType,annualKwh:s.consumption.annualKwh,annualBilledMxn:s.consumption.annualBilledMxn,monthly:s.consumption.monthly,sourceLabel:s.consumption.sourceLabel},
system:{moduleCount:s.system.moduleCount,moduleManufacturer:s.system.moduleManufacturer,moduleModel:s.system.moduleModel,moduleWattage:s.system.moduleWattage,installedDcKwp:s.system.installedDcKwp,inverterCount:s.system.inverterCount,inverterModels:s.system.inverterModels,inverterAcKw:s.system.inverterAcKw,dcAcRatio:v.metricSelection.showDcAcRatio?s.system.dcAcRatio:undefined,roofCapacity:s.system.roofCapacity,targetPanelCount:s.system.targetPanelCount},
design:{geometry:s.geometry},
production:{annualProductionKwh:s.energy.annualProductionKwh,specificYieldKwhPerKwp:v.metricSelection.showSpecificYield?s.energy.specificYieldKwhPerKwp:undefined,effectiveLossPct:s.energy.effectiveLossPct,resourceLabel:s.energy.resourceLabel,monthly:s.energy.monthly,statement:s.limitations.productionStatement},
coverage:{monthly:s.energy.monthly,annualConsumptionKwh:s.consumption.annualKwh,annualProductionKwh:s.energy.annualProductionKwh,energyOffsetPct:s.energy.energyOffsetPct},
equipment:{items:s.equipment},
investment:{currency:s.investment.currency,priceBeforeVat:s.investment.priceBeforeVat,vatRatePct:s.investment.vatRatePct,vatMxn:s.investment.vatMxn,totalIncludingVat:s.investment.totalIncludingVat,paymentTerms:v.commercialTerms.paymentTerms,validUntil:v.validity.validUntil},
financial:{caseName:s.financial.caseName,year1AvoidedElectricityCostMxn:s.financial.year1AvoidedElectricityCostMxn,simplePaybackYears:s.financial.simplePaybackYears,irrPct:v.metricSelection.showIrr?s.financial.irrPct:undefined,npvMxn:v.metricSelection.showNpv?s.financial.npvMxn:undefined,analysisTermYears:s.financial.analysisTermYears,electricityEscalationPct:s.financial.electricityEscalationPct,pvDegradationPct:s.financial.pvDegradationPct,discountRatePct:s.financial.discountRatePct,cashFlow:v.metricSelection.showCashflowChart?s.financial.cashFlow:[],statement:s.limitations.economicsStatement},
assumptions:{body:block(v,'assumptions')},scope:{body:block(v,'scope')},exclusions:{body:block(v,'exclusions')},warranties:{body:block(v,'warranties')},terms:{paymentTerms:v.commercialTerms.paymentTerms,scheduleText:v.commercialTerms.scheduleText,customerResponsibilities:v.commercialTerms.customerResponsibilities,utilityCaveat:v.commercialTerms.utilityCaveat,validUntil:v.validity.validUntil},'next-steps':{body:block(v,'next-steps')},disclaimers:{body:block(v,'disclaimer'),legal:v.branding.legalDisclaimer}}
;const sections:ProposalDocumentSection[]=v.sections.filter(x=>x.visible).sort((a,b)=>a.order-b.order).map((x,i)=>({key:x.key,title:x.title,pageBreakBefore:i>0&&['consumption','design','investment','scope'].includes(x.key),payload:payloads[x.key]}));return{title:`Solar proposal · ${v.customer.projectName}`,folio:`${v.snapshot.sourceRefs.r4Version}-${v.versionNumber}`,versionNumber:v.versionNumber,status:v.status,generatedAt:v.snapshot.capturedAt,customer:v.customer,branding:v.branding,validity:v.validity,commercialTerms:v.commercialTerms,sections,snapshot:structuredClone(s),privacyGuard:{internalFieldsExcluded:true,blockedFieldNames:[...INTERNAL_ONLY_FIELDS]}};}
export function serializeCustomerDocument(model:ProposalDocumentModel){return JSON.stringify({title:model.title,customer:model.customer,branding:model.branding,validity:model.validity,sections:model.sections,snapshot:{consumption:model.snapshot.consumption,system:model.snapshot.system,geometry:model.snapshot.geometry,energy:model.snapshot.energy,equipment:model.snapshot.equipment,investment:model.snapshot.investment,financial:model.snapshot.financial,limitations:model.snapshot.limitations}},null,2);}
