import {jsPDF} from 'jspdf';
import type {ProposalDocumentModel,ProposalProjectSnapshot} from './types';
const A4={w:210,h:297,margin:16};
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
export function proposalPdfFilename(projectName:string,versionNumber:number){const slug=projectName.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'project';return`proposal-${slug}-v${versionNumber}.pdf`;}
function hex(c:string,fallback=[11,49,84] as [number,number,number]):[number,number,number]{const m=c.match(/^#([0-9a-f]{6})$/i);if(!m)return fallback;return[parseInt(m[1].slice(0,2),16),parseInt(m[1].slice(2,4),16),parseInt(m[1].slice(4,6),16)];}
function footer(doc:jsPDF,m:ProposalDocumentModel,page:number){doc.setFontSize(7);doc.setTextColor(95,105,115);doc.text(m.branding.footerText||'Propuesta solar',A4.margin,289);doc.text(`v${m.versionNumber} · ${m.customer.projectName}`,105,289,{align:'center'});doc.text(`${page}`,194,289,{align:'right'});}
function title(doc:jsPDF,text:string,color:[number,number,number]){doc.setTextColor(...color);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(text,A4.margin,28);doc.setDrawColor(...color);doc.setLineWidth(.5);doc.line(A4.margin,33,194,33);doc.setTextColor(30,39,47);}
function wrapped(doc:jsPDF,text:string,x:number,y:number,w:number,size=9){doc.setFont('helvetica','normal');doc.setFontSize(size);doc.setTextColor(50,60,68);const lines=doc.splitTextToSize(text,w);doc.text(lines,x,y);return y+lines.length*(size*.42+1.4);}
function metric(doc:jsPDF,label:string,value:string,x:number,y:number,w:number){doc.setFillColor(246,249,251);doc.roundedRect(x,y,w,20,2,2,'F');doc.setFontSize(7);doc.setTextColor(90,100,110);doc.text(label.toUpperCase(),x+4,y+6);doc.setFontSize(13);doc.setFont('helvetica','bold');doc.setTextColor(20,42,60);doc.text(value,x+4,y+15);doc.setFont('helvetica','normal');}
function chart(doc:jsPDF,rows:Array<{label:string;a:number;b?:number}>,x:number,y:number,w:number,h:number,primary:[number,number,number],accent:[number,number,number]){const max=Math.max(1,...rows.flatMap(r=>[r.a,r.b||0]));doc.setDrawColor(220,226,231);doc.rect(x,y,w,h);const gap=w/rows.length;rows.forEach((r,i)=>{const bh=(r.a/max)*(h-12);doc.setFillColor(...primary);doc.rect(x+i*gap+2,y+h-8-bh,Math.max(1,gap*.3),bh,'F');if(r.b!==undefined){const bh2=(r.b/max)*(h-12);doc.setFillColor(...accent);doc.rect(x+i*gap+2+gap*.32,y+h-8-bh2,Math.max(1,gap*.3),bh2,'F')}doc.setFontSize(5.5);doc.setTextColor(100,110,118);doc.text(r.label,x+i*gap+gap*.5,y+h-2,{align:'center'})})}
function drawBrandLogo(doc:jsPDF,dataUrl:string|undefined,x:number,y:number,maxW:number,maxH:number){if(!dataUrl)return false;try{const p=doc.getImageProperties(dataUrl);const ratio=p.width/p.height;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}doc.addImage(dataUrl,p.fileType||'PNG',x,y,w,h,undefined,'FAST');return true}catch{return false}}
function designVisual(doc:jsPDF,s:ProposalProjectSnapshot,x:number,y:number,w:number,h:number,primary:[number,number,number],accent:[number,number,number]){const pts=[...s.geometry.roofs.flatMap(r=>r.points),...s.geometry.modules.map(m=>({x:m.x,y:m.y}))];if(!pts.length){wrapped(doc,'No hay geometría de diseño disponible.',x,y,w);return}const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const sx=(w-12)/Math.max(1,maxX-minX),sy=(h-12)/Math.max(1,maxY-minY),sc=Math.min(sx,sy),tx=(vx:number)=>x+6+(vx-minX)*sc,ty=(vy:number)=>y+6+(vy-minY)*sc;doc.setFillColor(248,250,251);doc.rect(x,y,w,h,'F');s.geometry.roofs.forEach(r=>{const p=r.points;if(!p.length)return;doc.setDrawColor(...primary);doc.setLineWidth(.7);for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];doc.line(tx(a.x),ty(a.y),tx(b.x),ty(b.y))}});s.geometry.obstructions.forEach(o=>{doc.setFillColor(190,196,202);if(o.x!==undefined&&o.y!==undefined&&o.width&&o.height)doc.rect(tx(o.x),ty(o.y),o.width*sc,o.height*sc,'F')});const md=s.geometry.moduleDimensions;s.geometry.modules.forEach(m=>{const mw=(m.orientation==='portrait'?md.width:md.height)*sc,mh=(m.orientation==='portrait'?md.height:md.width)*sc;doc.setFillColor(...accent);doc.setDrawColor(...primary);doc.rect(tx(m.x)-mw/2,ty(m.y)-mh/2,mw,mh,'FD')});doc.setFontSize(6);doc.setTextColor(80,90,98);doc.text(`${s.geometry.modules.length} módulos · geometría R2`,x+4,y+h-3)}
export function generateProposalPdf(model:ProposalDocumentModel){const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:false});const primary=hex(model.branding.primaryColor),accent=hex(model.branding.accentColor,[7,128,173]);doc.setProperties({title:model.title,subject:`Propuesta solar v${model.versionNumber}`,author:model.branding.companyDisplayName,creator:'solar-platform-v2 R7'});let page=1;const newPage=(heading:string)=>{if(page>1)doc.addPage();title(doc,heading,primary);footer(doc,model,page);page++};const b=model.branding;doc.setFillColor(...primary);doc.rect(0,0,210,72,'F');const hasLogo=drawBrandLogo(doc,b.logoDataUrl,16,12,76,24);doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(12);if(!hasLogo)doc.text(b.companyDisplayName||'Empresa solar',16,22);doc.setFontSize(29);doc.text('PROPUESTA',16,47);doc.text('SOLAR',16,60);doc.setTextColor(...primary);doc.setFontSize(20);doc.text(model.customer.projectName,16,100);doc.setFontSize(11);doc.setFont('helvetica','normal');doc.setTextColor(70,80,88);doc.text(`Preparada para ${model.customer.customerName}`,16,112);doc.text(model.customer.siteAddress,16,121);doc.setFontSize(9);doc.text(`Fecha ${model.customer.proposalDate} · Vigente hasta ${model.validity.validUntil} · Versión ${model.versionNumber}`,16,139);doc.setTextColor(...accent);doc.setFontSize(14);doc.text(b.coverTagline||'Energía que conecta.',16,167);wrapped(doc,'Este documento presenta el diseño, la estimación energética y el caso comercial aceptados y congelados en esta versión de propuesta.',16,184,170,10);footer(doc,model,1);page=2;const s=model.snapshot;
newPage('Solución propuesta');let y=46;const summary=model.sections.find(x=>x.key==='executive-summary')?.payload.body as string||'';y=wrapped(doc,summary,16,y,178,10)+7;metric(doc,'Potencia DC',`${s.system.installedDcKwp.toFixed(2)} kWp`,16,y,41);metric(doc,'Módulos',`${s.system.moduleCount} × ${s.system.moduleWattage} W`,60,y,41);metric(doc,'Producción anual',`${Math.round(s.energy.annualProductionKwh/1000)} MWh`,104,y,41);metric(doc,'Cobertura',`${s.energy.energyOffsetPct.toFixed(1)}%`,148,y,46);
newPage('Consumo y sistema propuesto');metric(doc,'Consumo anual',`${Math.round(s.consumption.annualKwh).toLocaleString('es-MX')} kWh`,16,44,54);metric(doc,'Tarifa CFE',s.consumption.tariff,74,44,34);metric(doc,'Potencia DC',`${s.system.installedDcKwp.toFixed(2)} kWp`,112,44,38);metric(doc,'Inversor AC',`${s.system.inverterAcKw.toFixed(1)} kW`,154,44,40);chart(doc,s.consumption.monthly.map(m=>({label:m.label,a:m.kwh})),16,72,178,62,primary,accent);y=147;doc.setFontSize(10);doc.setFont('helvetica','bold');doc.text('Equipos seleccionados',16,y);doc.setFont('helvetica','normal');y+=8;doc.setFontSize(8);s.equipment.slice(0,8).forEach(item=>{doc.text(`${item.quantity} ${item.unit} · ${item.description}`,18,y);y+=6});
newPage('Diseño solar y energía');designVisual(doc,s,16,43,178,92,primary,accent);doc.setFontSize(8);doc.setTextColor(75,84,92);doc.text('Visual limpio generado directamente desde geometría R2; no implica imagen satelital.',16,143);chart(doc,s.energy.monthly.map(m=>({label:m.label,a:m.productionKwh,b:m.consumptionKwh})),16,158,178,70,primary,accent);wrapped(doc,s.limitations.productionStatement,16,241,178,7.5);
newPage('Inversión y retorno financiero');metric(doc,'Antes de IVA',money(s.investment.priceBeforeVat),16,44,54);metric(doc,`IVA ${s.investment.vatRatePct}%`,money(s.investment.vatMxn),74,44,54);metric(doc,'Inversión total',money(s.investment.totalIncludingVat),132,44,62);metric(doc,'Valor evitado año 1',money(s.financial.year1AvoidedElectricityCostMxn),16,72,54);metric(doc,'Retorno simple',s.financial.simplePaybackYears===null?'N/D':`${s.financial.simplePaybackYears.toFixed(1)} años`,74,72,38);metric(doc,'TIR',s.financial.irrPct===null?'N/D':`${s.financial.irrPct.toFixed(1)}%`,116,72,34);metric(doc,'VPN',money(s.financial.npvMxn),154,72,40);chart(doc,s.financial.cashFlow.filter((_,i)=>i%Math.max(1,Math.ceil(s.financial.cashFlow.length/12))===0).map(c=>({label:String(c.year),a:Math.max(0,c.cumulativeCashFlowMxn),b:Math.max(0,-c.cumulativeCashFlowMxn)})),16,108,178,66,primary,accent);wrapped(doc,`Caso económico: ${s.financial.caseName}. Horizonte ${s.financial.analysisTermYears} años · escalamiento eléctrico ${s.financial.electricityEscalationPct}%/año · degradación FV ${s.financial.pvDegradationPct}%/año · tasa de descuento ${s.financial.discountRatePct}%.`,16,188,178,8);wrapped(doc,s.limitations.economicsStatement,16,210,178,7.5);
newPage('Alcance, términos y supuestos');y=42;for(const key of ['scope','exclusions','warranties','assumptions','next-steps','disclaimers'] as const){const sec=model.sections.find(x=>x.key===key);if(!sec)continue;doc.setFont('helvetica','bold');doc.setTextColor(...primary);doc.setFontSize(10);doc.text(sec.title,16,y);y+=6;const body=(sec.payload.body||sec.payload.legal||'') as string;y=wrapped(doc,body,16,y,178,8)+5;if(y>255){footer(doc,model,page-1);doc.addPage();title(doc,'Alcance, términos y supuestos · continuación',primary);footer(doc,model,page);page++;y=43}}doc.setFont('helvetica','bold');doc.setTextColor(...primary);doc.text('Condiciones comerciales',16,y);y+=6;wrapped(doc,`${model.commercialTerms.paymentTerms}\n${model.commercialTerms.scheduleText}\n${model.commercialTerms.customerResponsibilities}\n${model.commercialTerms.utilityCaveat}`,16,y,178,8);const blob=doc.output('blob');return{blob,pageCount:doc.getNumberOfPages()}}
export async function downloadProposalPdf(model:ProposalDocumentModel){const filename=proposalPdfFilename(model.customer.projectName,model.versionNumber);const {blob,pageCount}=generateProposalPdf(model);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return{filename,sizeBytes:blob.size,pageCount,mimeType:'application/pdf' as const}}
