import type {AcceptedProjectOutputs} from '../acceptedProjectOutputs';
import type {ProposalProjectSnapshot} from './types';
function monthLabel(period:string){const d=new Date(`${period}-01T00:00:00`);return Number.isNaN(d.getTime())?period:d.toLocaleString('en',{month:'short'});}
export function buildProposalSnapshot(o:AcceptedProjectOutputs,now=new Date().toISOString()):ProposalProjectSnapshot{
  const selectedScenario=o.r4Economics.scenarios.find(x=>x.scenario.id===o.r4State.selectedScenarioId);
  const selectedCatalogIds=new Set(o.r4Economics.bom.lines.map(x=>x.catalogItemId).filter(Boolean));
  const equipment=o.r4Economics.bom.lines.filter(x=>x.derivation==='design-derived'||x.category==='mounting'||x.category==='monitoring').filter(x=>!x.catalogItemId||selectedCatalogIds.has(x.catalogItemId)).map(x=>({description:x.description,quantity:x.quantityOverride??x.quantity,unit:x.unit,category:x.category}));
  return{
    capturedAt:now,
    sourceRefs:{r1Version:o.profile.version,r1UpdatedAt:o.profile.updatedAt,r2Version:o.design.version,r2UpdatedAt:o.design.updatedAt,r3Version:o.electrical.version,r3UpdatedAt:o.electrical.updatedAt,r4Version:o.r4State.version,r4UpdatedAt:o.r4State.updatedAt,designBasisId:o.design.designBasisId,economicCaseId:o.r4State.selectedScenarioId},
    consumption:{tariff:o.profile.service.tariff,siteType:o.profile.service.siteType,annualKwh:o.r1Metrics.annualKwh,annualBilledMxn:o.r4Economics.baseline.annualBilledMxn,sourceLabel:`${o.profile.source.kind} · ${o.profile.source.status}`,monthly:o.profile.consumption.slice(-12).map(x=>({period:x.period,label:monthLabel(x.period),kwh:x.kwh,amountMxn:x.amountMxn}))},
    system:{moduleCount:o.design.layout.placements.length,moduleManufacturer:o.module.manufacturer,moduleModel:o.module.model,moduleWattage:o.module.pmaxW,installedDcKwp:o.r3Summary.installedDcKwp,inverterCount:o.electrical.inverters.length,inverterModels:o.inverterSpecs.map(x=>`${x.spec.manufacturer} ${x.spec.model}`),inverterAcKw:o.r3AcKw,dcAcRatio:o.r3DcAcRatio,roofCapacity:o.r2Summary.capacity,targetPanelCount:o.design.targetPanelCount,targetOffsetPct:o.design.targetOffset},
    geometry:{moduleDimensions:{...o.design.moduleDimensions},roofs:o.design.roofs.map(r=>({id:r.id,name:r.name,points:r.points.map(p=>({x:p.x,y:p.y}))})),obstructions:o.design.obstructions.map(x=>({id:x.id,kind:x.kind,name:x.name,x:x.x,y:x.y,width:x.width,height:x.height,points:x.points?.map(p=>({x:p.x,y:p.y}))})),restrictedZones:o.design.restrictedZones.map(x=>({id:x.id,name:x.name,points:x.points.map(p=>({x:p.x,y:p.y}))})),modules:o.design.layout.placements.map(x=>({id:x.id,roofId:x.roofId,x:x.x,y:x.y,orientation:x.orientation,rotation:x.rotation}))},
    energy:{annualProductionKwh:o.r3Summary.annualProductionKwh,specificYieldKwhPerKwp:o.r3Summary.specificYieldKwhPerKwp,energyOffsetPct:o.r3Summary.energyOffsetPct,effectiveLossPct:o.r3Summary.effectiveLossPct,resourceLabel:o.electrical.resourceLabel,monthly:o.r3Monthly.map(x=>({label:x.label,productionKwh:x.productionKwh,consumptionKwh:x.consumptionKwh}))},
    equipment,
    investment:{currency:'MXN',priceBeforeVat:o.r4Economics.pricing.sellPriceBeforeVat,vatRatePct:o.r4State.costBasis.vatRatePct,vatMxn:o.r4Economics.pricing.vat,totalIncludingVat:o.r4Economics.pricing.customerTotal},
    financial:{caseId:o.r4State.selectedScenarioId,caseName:selectedScenario?.scenario.name||o.r4State.selectedScenarioId,year1AvoidedElectricityCostMxn:o.r4Economics.solarValue.year1AvoidedElectricityCostMxn,simplePaybackYears:o.r4Economics.metrics.simplePaybackYears,irrPct:o.r4Economics.metrics.irrPct,npvMxn:o.r4Economics.metrics.npvMxn,analysisTermYears:o.r4State.financial.analysisTermYears,electricityEscalationPct:o.r4State.financial.electricityEscalationPct,pvDegradationPct:o.r4State.financial.pvDegradationPct,discountRatePct:o.r4State.financial.discountRatePct,cashFlow:o.r4Economics.cashFlows.map(x=>({year:x.year,cumulativeCashFlowMxn:x.cumulativeCashFlowMxn,netAnnualBenefitMxn:x.netAnnualBenefitMxn}))},
    limitations:{productionStatement:'Production is a deterministic R3 planning estimate based on editable monthly resource and loss assumptions; it is not a bankable hourly/PVsyst-equivalent simulation.',economicsStatement:'Financial results use the accepted R4 monthly energy-value approximation and explicit economic assumptions; they are estimates, not guaranteed utility bills or returns.'}
  };
}
