import type {Proposal,ProposalBranding,ProposalCustomer,ProposalExportMetadata,ProposalProjectSnapshot,ProposalVersion} from './types';
import {DEFAULT_BRANDING,DEFAULT_CONTENT_BLOCKS,DEFAULT_CUSTOMER,DEFAULT_METRICS,DEFAULT_SECTIONS,DEFAULT_TERMS,DEFAULT_VALIDITY} from './defaults';import {getRuntimeProposalBrand} from './runtimeBrand';
function dateOnly(iso:string){return iso.slice(0,10)}
function addDays(iso:string,days:number){const d=new Date(`${dateOnly(iso)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function deterministicExecutiveSummary(s:ProposalProjectSnapshot){const payback=s.financial.simplePaybackYears===null?'no disponible con los supuestos actuales':`${s.financial.simplePaybackYears.toFixed(1)} años`;return`Proponemos un sistema fotovoltaico de ${s.system.installedDcKwp.toFixed(2)} kWp con ${s.system.moduleCount} módulos de ${s.system.moduleWattage} W. El modelo de planeación R3 estima ${Math.round(s.energy.annualProductionKwh).toLocaleString('es-MX')} kWh de producción durante el primer año, equivalente aproximadamente al ${s.energy.energyOffsetPct.toFixed(1)}% del consumo anual registrado bajo un balance energético anual simple. El snapshot comercial R4 muestra una inversión de ${Math.round(s.investment.totalIncludingVat).toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0})} con IVA, un valor evitado estimado de ${Math.round(s.financial.year1AvoidedElectricityCostMxn).toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0})} durante el primer año y un retorno simple de ${payback}. Estas cifras son estimaciones de planeación, no garantías de producción, ahorro o rendimiento.`;}
export function createProposalVersion(snapshot:ProposalProjectSnapshot,sourceFingerprint:string,versionNumber=1,now=new Date().toISOString(),seed?:Partial<ProposalVersion>,brandingOverride?:ProposalBranding):ProposalVersion{const blocks=structuredClone(seed?.contentBlocks||DEFAULT_CONTENT_BLOCKS);const summary=blocks.find(x=>x.key==='executive-summary');if(summary&&!summary.body)summary.body=deterministicExecutiveSummary(snapshot);const validityDays=seed?.validity?.validityDays||DEFAULT_VALIDITY.validityDays;const customer=structuredClone(seed?.customer||DEFAULT_CUSTOMER);customer.proposalDate=dateOnly(now);return{id:`v${versionNumber}`,versionNumber,status:'Draft',frozen:false,createdAt:now,updatedAt:now,snapshot:structuredClone(snapshot),sourceFingerprint,customer,branding:structuredClone(brandingOverride||seed?.branding||getRuntimeProposalBrand()||DEFAULT_BRANDING),sections:structuredClone(seed?.sections||DEFAULT_SECTIONS),contentBlocks:blocks,metricSelection:structuredClone(seed?.metricSelection||DEFAULT_METRICS),commercialTerms:structuredClone(seed?.commercialTerms||DEFAULT_TERMS),validity:{validityDays,validUntil:addDays(now,validityDays)}};}
export function createProposal(projectId:string,snapshot:ProposalProjectSnapshot,fingerprint:string,now=new Date().toISOString(),branding?:ProposalBranding):Proposal{const effective=branding||getRuntimeProposalBrand()||DEFAULT_BRANDING;const first=createProposalVersion(snapshot,fingerprint,1,now,undefined,effective);return{version:5,projectId,activeVersionId:first.id,versions:[first],brandingDefaults:structuredClone(effective),updatedAt:now};}
export function nextVersionNumber(p:Proposal){return Math.max(0,...p.versions.map(v=>v.versionNumber))+1;}
export function createNextVersion(p:Proposal,snapshot:ProposalProjectSnapshot,fingerprint:string,now=new Date().toISOString(),brandingOverride?:ProposalBranding):Proposal{const active=p.versions.find(v=>v.id===p.activeVersionId);const effective=brandingOverride||getRuntimeProposalBrand()||p.brandingDefaults;const next=createProposalVersion(snapshot,fingerprint,nextVersionNumber(p),now,active,effective);const versions=p.versions.map(v=>v.id===active?.id&&v.status==='Ready'?{...v,status:'Superseded' as const}:v);return{...p,versions:[...versions,next],activeVersionId:next.id,brandingDefaults:structuredClone(effective),updatedAt:now};}
export function updateActiveDraft(p:Proposal,updater:(v:ProposalVersion)=>ProposalVersion,now=new Date().toISOString()):Proposal{const active=p.versions.find(v=>v.id===p.activeVersionId);if(!active||active.frozen||active.status==='Exported')return p;return{...p,versions:p.versions.map(v=>v.id===active.id?{...updater(structuredClone(v)),updatedAt:now}:v),updatedAt:now};}
export function setVersionStatus(p:Proposal,id:string,status:ProposalVersion['status'],now=new Date().toISOString()):Proposal{return{...p,versions:p.versions.map(v=>v.id===id?{...v,status,frozen:status==='Exported'?true:v.frozen,updatedAt:now}:v),updatedAt:now};}
export function recordProposalExport(p:Proposal,id:string,meta:ProposalExportMetadata,now=new Date().toISOString()):Proposal{return{...p,versions:p.versions.map(v=>v.id===id?{...v,status:meta.status==='success'?'Exported':v.status,frozen:meta.status==='success'?true:v.frozen,exportMetadata:structuredClone(meta),updatedAt:now}:v),updatedAt:now};}
export function selectProposalVersion(p:Proposal,id:string):Proposal{return p.versions.some(v=>v.id===id)?{...p,activeVersionId:id}:p;}
export function updateBrandingDefaults(p:Proposal,branding:ProposalBranding):Proposal{return{...p,brandingDefaults:structuredClone(branding)};}
export function updateCustomer(v:ProposalVersion,customer:ProposalCustomer):ProposalVersion{return v.frozen?v:{...v,customer:structuredClone(customer)};}
