import type {Proposal,ProposalBranding,ProposalCustomer,ProposalExportMetadata,ProposalProjectSnapshot,ProposalVersion} from './types';
import {DEFAULT_BRANDING,DEFAULT_CONTENT_BLOCKS,DEFAULT_CUSTOMER,DEFAULT_METRICS,DEFAULT_SECTIONS,DEFAULT_TERMS,DEFAULT_VALIDITY} from './defaults';
function dateOnly(iso:string){return iso.slice(0,10)}
function addDays(iso:string,days:number){const d=new Date(`${dateOnly(iso)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function deterministicExecutiveSummary(s:ProposalProjectSnapshot){const payback=s.financial.simplePaybackYears===null?'not available under the current assumptions':`${s.financial.simplePaybackYears.toFixed(1)} years`;return`We propose a ${s.system.installedDcKwp.toFixed(2)} kWp photovoltaic system using ${s.system.moduleCount} × ${s.system.moduleWattage} W modules. The accepted R3 planning model estimates ${Math.round(s.energy.annualProductionKwh).toLocaleString()} kWh of first-year production, equivalent to approximately ${s.energy.energyOffsetPct.toFixed(1)}% of the recorded annual energy consumption on a simple annual energy-balance basis. The current R4 commercial snapshot shows an investment of MX$${Math.round(s.investment.totalIncludingVat).toLocaleString()} including VAT, an estimated first-year avoided electricity value of MX$${Math.round(s.financial.year1AvoidedElectricityCostMxn).toLocaleString()}, and simple payback of ${payback}. These figures are planning estimates, not guaranteed production, bill savings or returns.`;}
export function createProposalVersion(snapshot:ProposalProjectSnapshot,sourceFingerprint:string,versionNumber=1,now=new Date().toISOString(),seed?:Partial<ProposalVersion>):ProposalVersion{const blocks=structuredClone(seed?.contentBlocks||DEFAULT_CONTENT_BLOCKS);const summary=blocks.find(x=>x.key==='executive-summary');if(summary&&!summary.body)summary.body=deterministicExecutiveSummary(snapshot);const validityDays=seed?.validity?.validityDays||DEFAULT_VALIDITY.validityDays;const customer=structuredClone(seed?.customer||DEFAULT_CUSTOMER);customer.proposalDate=dateOnly(now);return{id:`v${versionNumber}`,versionNumber,status:'Draft',frozen:false,createdAt:now,updatedAt:now,snapshot:structuredClone(snapshot),sourceFingerprint,customer,branding:structuredClone(seed?.branding||DEFAULT_BRANDING),sections:structuredClone(seed?.sections||DEFAULT_SECTIONS),contentBlocks:blocks,metricSelection:structuredClone(seed?.metricSelection||DEFAULT_METRICS),commercialTerms:structuredClone(seed?.commercialTerms||DEFAULT_TERMS),validity:{validityDays,validUntil:addDays(now,validityDays)}};}
export function createProposal(projectId:string,snapshot:ProposalProjectSnapshot,fingerprint:string,now=new Date().toISOString()):Proposal{const first=createProposalVersion(snapshot,fingerprint,1,now);return{version:5,projectId,activeVersionId:first.id,versions:[first],brandingDefaults:structuredClone(DEFAULT_BRANDING),updatedAt:now};}
export function nextVersionNumber(p:Proposal){return Math.max(0,...p.versions.map(v=>v.versionNumber))+1;}
export function createNextVersion(p:Proposal,snapshot:ProposalProjectSnapshot,fingerprint:string,now=new Date().toISOString()):Proposal{const active=p.versions.find(v=>v.id===p.activeVersionId);const next=createProposalVersion(snapshot,fingerprint,nextVersionNumber(p),now,active);const versions=p.versions.map(v=>v.id===active?.id&&v.status==='Ready'?{...v,status:'Superseded' as const}:v);return{...p,versions:[...versions,next],activeVersionId:next.id,updatedAt:now};}
export function updateActiveDraft(p:Proposal,updater:(v:ProposalVersion)=>ProposalVersion,now=new Date().toISOString()):Proposal{const active=p.versions.find(v=>v.id===p.activeVersionId);if(!active||active.frozen||active.status==='Exported')return p;return{...p,versions:p.versions.map(v=>v.id===active.id?{...updater(structuredClone(v)),updatedAt:now}:v),updatedAt:now};}
export function setVersionStatus(p:Proposal,id:string,status:ProposalVersion['status'],now=new Date().toISOString()):Proposal{return{...p,versions:p.versions.map(v=>v.id===id?{...v,status,frozen:status==='Exported'?true:v.frozen,updatedAt:now}:v),updatedAt:now};}
export function recordProposalExport(p:Proposal,id:string,meta:ProposalExportMetadata,now=new Date().toISOString()):Proposal{return{...p,versions:p.versions.map(v=>v.id===id?{...v,status:meta.status==='success'?'Exported':v.status,frozen:meta.status==='success'?true:v.frozen,exportMetadata:structuredClone(meta),updatedAt:now}:v),updatedAt:now};}
export function selectProposalVersion(p:Proposal,id:string):Proposal{return p.versions.some(v=>v.id===id)?{...p,activeVersionId:id}:p;}
export function updateBrandingDefaults(p:Proposal,branding:ProposalBranding):Proposal{return{...p,brandingDefaults:structuredClone(branding)};}
export function updateCustomer(v:ProposalVersion,customer:ProposalCustomer):ProposalVersion{return v.frozen?v:{...v,customer:structuredClone(customer)};}
