import {catalogByEngineeringSpec,catalogById} from './catalog';
import type {BomLineItem,BomOverride,CostBasis,CostBreakdown,EquipmentCatalogItem,EquipmentCategory,ManualBomInput,ProjectBom} from './types';
import type {ElectricalDesign,InverterSpec} from '../electrical/types';
const categories:EquipmentCategory[]=['pv-module','inverter','mounting','dc-electrical','ac-electrical','protections','cabling-connectors','monitoring','installation-labor','engineering-design','permits-interconnection','freight-logistics','misc-contingency'];
export function convertToMxn(value:number,currency:'MXN'|'USD',exchangeRate:number){return currency==='USD'?value*exchangeRate:value;}
export function generateProjectBom(args:{projectId:string;placedModuleCount:number;installedDcKwp:number;electrical:ElectricalDesign;inverterCatalog:InverterSpec[];catalog:EquipmentCatalogItem[];manualLines:ManualBomInput[];overrides:BomOverride[]}):ProjectBom{
 const {projectId,placedModuleCount,installedDcKwp,electrical,inverterCatalog,catalog,manualLines,overrides}=args;const lines:BomLineItem[]=[];
 const mod=catalogByEngineeringSpec(catalog,electrical.selectedModuleSpecId);if(mod)lines.push({id:'bom-modules',catalogItemId:mod.id,description:mod.description,category:'pv-module',quantity:placedModuleCount,unit:'module',derivation:'design-derived',derivationNote:`R2 placed modules = ${placedModuleCount}`,vatApplicable:mod.vatApplicable,sourceStatus:'engineering-linked'});
 const grouped=new Map<string,number>();for(const inv of electrical.inverters)grouped.set(inv.specId,(grouped.get(inv.specId)||0)+1);for(const [specId,qty] of grouped){const item=catalogByEngineeringSpec(catalog,specId);const spec=inverterCatalog.find(x=>x.id===specId);if(item)lines.push({id:`bom-inverter-${specId}`,catalogItemId:item.id,description:item.description,category:'inverter',quantity:qty,unit:'unit',derivation:'design-derived',derivationNote:`R3 selected inverter instances: ${qty} × ${spec?.model||specId}`,vatApplicable:item.vatApplicable,sourceStatus:'engineering-linked'});}
 const rules:[string,string,number,string,string][]=[['bom-mount','cat-mount',placedModuleCount,'module','1 mounting allowance per placed module'],['bom-dc','cat-dc',Number(installedDcKwp.toFixed(2)),'kWp','DC material allowance per installed kWp'],['bom-ac','cat-ac',electrical.inverters.length,'inverter','AC material allowance per R3 inverter'],['bom-prot','cat-prot',electrical.inverters.length,'inverter','Protection allowance per R3 inverter'],['bom-cable','cat-cable',placedModuleCount,'module','Cabling/connectors allowance per placed module'],['bom-monitor','cat-monitor',1,'project','1 monitoring allowance per project'],['bom-labor','cat-labor',placedModuleCount,'module','Installation labor allowance per placed module'],['bom-eng','cat-eng',1,'project','1 engineering/design allowance per project'],['bom-permit','cat-permit',1,'project','1 permits/interconnection allowance per project'],['bom-freight','cat-freight',1,'project','1 freight/logistics allowance per project'],['bom-cont','cat-cont',1,'project','1 miscellaneous/contingency allowance per project']];
 for(const [id,catalogId,quantity,unit,note] of rules){const item=catalogById(catalog,catalogId);if(item)lines.push({id,catalogItemId:item.id,description:item.description,category:item.category,quantity,unit,derivation:'rule-derived',derivationNote:note,vatApplicable:item.vatApplicable,sourceStatus:'editable-assumption'});}
 for(const m of manualLines)lines.push({id:m.id,description:m.description,category:m.category,quantity:m.quantity,unit:m.unit,derivation:'manual',derivationNote:'Manual project BOM line',vatApplicable:m.vatApplicable,unitCostOverride:m.unitCost,currencyOverride:m.currency,sourceStatus:'manual'});
 return{projectId,lines:lines.map(l=>{const o=overrides.find(x=>x.lineId===l.id);return o?{...l,quantityOverride:o.quantity,unitCostOverride:o.unitCost,currencyOverride:o.currency}:l}),generatedAt:new Date(0).toISOString()};}
export function lineQuantity(l:BomLineItem){return l.quantityOverride??l.quantity;}
export function lineUnitCostMxn(l:BomLineItem,catalog:EquipmentCatalogItem[],exchangeRate:number){const item=l.catalogItemId?catalogById(catalog,l.catalogItemId):undefined;const cost=l.unitCostOverride??item?.unitCost??0;const currency=l.currencyOverride??item?.currency??'MXN';return convertToMxn(cost,currency,exchangeRate);}
export function lineSubtotalMxn(l:BomLineItem,catalog:EquipmentCatalogItem[],exchangeRate:number){return lineQuantity(l)*lineUnitCostMxn(l,catalog,exchangeRate);}
export function calculateCostBreakdown(bom:ProjectBom,catalog:EquipmentCatalogItem[],basis:CostBasis):CostBreakdown{const byCategory=Object.fromEntries(categories.map(c=>[c,0])) as Record<EquipmentCategory,number>;let inputVat=0;for(const line of bom.lines){const subtotal=lineSubtotalMxn(line,catalog,basis.exchangeRateMxnPerUsd);byCategory[line.category]+=subtotal;if(line.vatApplicable)inputVat+=subtotal*basis.vatRatePct/100;}const equipmentCost=byCategory['pv-module']+byCategory.inverter;const materialsCost=byCategory.mounting+byCategory['dc-electrical']+byCategory['ac-electrical']+byCategory.protections+byCategory['cabling-connectors']+byCategory.monitoring;const laborCost=byCategory['installation-labor'];const engineeringCost=byCategory['engineering-design'];const logisticsCost=byCategory['freight-logistics'];const permitsCost=byCategory['permits-interconnection'];const contingencyCost=byCategory['misc-contingency'];const directProjectCost=equipmentCost+materialsCost+laborCost+engineeringCost+logisticsCost+permitsCost+contingencyCost;const overheadAllocation=basis.overheadType==='percent'?directProjectCost*basis.overheadValue/100:basis.overheadType==='fixed'?basis.overheadValue:0;const totalCostBeforeVat=directProjectCost+overheadAllocation;return{equipmentCost,materialsCost,laborCost,engineeringCost,logisticsCost,permitsCost,contingencyCost,directProjectCost,overheadAllocation,totalCostBeforeVat,inputVat,totalCashOutIncludingVat:totalCostBeforeVat+inputVat,byCategory};}
