import {describe,expect,it} from 'vitest';
import {DEFAULT_EQUIPMENT_CATALOG} from './catalog';
import {calculateCostBreakdown,convertToMxn,generateProjectBom,lineSubtotalMxn} from './bom';
import {calculateProjectPricing,priceBeforeVat} from './pricing';
import {calculateBaseline} from './baseline';
import {calculateSolarValue} from './solarValue';
import {buildCashFlows} from './cashflow';
import {calculateFinancialMetrics,irr,npv,simplePayback} from './metrics';
import {buildScenarios} from './scenarios';
import {calculateSensitivity} from './sensitivity';
import {createDefaultR4State,loadR4State,saveR4State} from './store';
import {deriveProjectEconomics} from './model';
import {defaultEnergyProfile} from '../energy/types';
import {createDefaultSiteDesign} from '../design/types';
import {createDefaultElectricalDesign} from '../electrical/store';
import {INVERTER_CATALOG} from '../electrical/catalog';
const electrical=createDefaultElectricalDesign();
const bom=(modules=20)=>generateProjectBom({projectId:'p',placedModuleCount:modules,installedDcKwp:modules*.64,electrical,inverterCatalog:INVERTER_CATALOG,catalog:DEFAULT_EQUIPMENT_CATALOG,manualLines:[],overrides:[]});
const basis={exchangeRateMxnPerUsd:18,overheadType:'percent' as const,overheadValue:5,vatRatePct:16};
const solar={months:[],annualAvoidedEnergyKwh:10000,annualSurplusKwh:1000,year1AvoidedElectricityCostMxn:30000,year1SurplusValueMxn:1000,year1TotalEnergyValueMxn:31000,exportRateMxnPerKwh:1};
const fin={analysisTermYears:25,electricityEscalationPct:4,pvDegradationPct:.5,annualOmCostMxn:1000,omEscalationPct:3,replacementEnabled:true,replacementYear:10,replacementCostMxn:5000,discountRatePct:10,analysisBasis:'before-vat' as const};
describe('R4 economics domain',()=>{
it('BOM module quantity follows R2 placements',()=>expect(bom(24).lines.find(x=>x.id==='bom-modules')?.quantity).toBe(24));
it('BOM inverter quantity follows R3 instances',()=>expect(bom().lines.find(x=>x.category==='inverter')?.quantity).toBe(1));
it('USD converts to MXN with editable exchange rate',()=>expect(convertToMxn(100,'USD',18)).toBe(1800));
it('module line subtotal uses USD conversion',()=>expect(lineSubtotalMxn(bom().lines.find(x=>x.id==='bom-modules')!,DEFAULT_EQUIPMENT_CATALOG,18)).toBe(36000));
it('manual BOM lines are retained as manual derivation',()=>{const b=generateProjectBom({projectId:'p',placedModuleCount:20,installedDcKwp:12.8,electrical,inverterCatalog:INVERTER_CATALOG,catalog:DEFAULT_EQUIPMENT_CATALOG,manualLines:[{id:'m',description:'Crane',category:'freight-logistics',quantity:1,unit:'job',unitCost:2000,currency:'MXN',vatApplicable:true}],overrides:[]});expect(b.lines.find(x=>x.id==='m')?.derivation).toBe('manual')});
it('quantity and cost overrides replace rule inputs transparently',()=>{const b=generateProjectBom({projectId:'p',placedModuleCount:20,installedDcKwp:12.8,electrical,inverterCatalog:INVERTER_CATALOG,catalog:DEFAULT_EQUIPMENT_CATALOG,manualLines:[],overrides:[{lineId:'bom-mount',quantity:25,unitCost:1000}]});const l=b.lines.find(x=>x.id==='bom-mount')!;expect(lineSubtotalMxn(l,DEFAULT_EQUIPMENT_CATALOG,18)).toBe(25000)});
it('cost model computes explicit VAT',()=>{const c=calculateCostBreakdown(bom(),DEFAULT_EQUIPMENT_CATALOG,basis);expect(c.inputVat).toBeGreaterThan(0);expect(c.totalCashOutIncludingVat).toBeCloseTo(c.totalCostBeforeVat+c.inputVat)});
it('markup pricing is cost times one plus markup',()=>expect(priceBeforeVat(100,{strategy:'markup',markupPct:30,targetGrossMarginPct:20,fixedSellPriceBeforeVat:0})).toBe(130));
it('target margin pricing solves sell price from cost',()=>expect(priceBeforeVat(100,{strategy:'target-margin',markupPct:0,targetGrossMarginPct:20,fixedSellPriceBeforeVat:0})).toBe(125));
it('gross margin is distinct from markup',()=>{const c=calculateCostBreakdown(bom(),DEFAULT_EQUIPMENT_CATALOG,basis);const p=calculateProjectPricing(c,{strategy:'markup',markupPct:25,targetGrossMarginPct:0,fixedSellPriceBeforeVat:0},{salesCommissionType:'percent',salesCommissionValue:3,cacAllowance:1000,projectOperatingAllowance:500},16,12.8);expect(p.markupPct).toBeCloseTo(25);expect(p.grossMarginPct).toBeCloseTo(20)});
it('commercial contribution is distinct from gross profit',()=>{const c=calculateCostBreakdown(bom(),DEFAULT_EQUIPMENT_CATALOG,basis);const p=calculateProjectPricing(c,{strategy:'markup',markupPct:25,targetGrossMarginPct:0,fixedSellPriceBeforeVat:0},{salesCommissionType:'percent',salesCommissionValue:3,cacAllowance:1000,projectOperatingAllowance:500},16,12.8);expect(p.contributionAfterCommercialCosts).toBeLessThan(p.grossProfit)});
it('historical blended tariff uses latest billed amounts',()=>{const b=calculateBaseline(defaultEnergyProfile.consumption,{mode:'historical',userBlendedRateMxnPerKwh:0,preservedDemandAnnualMxn:0,notes:''});expect(b.valid).toBe(true);expect(b.blendedRateMxnPerKwh).toBeCloseTo(3.02,1)});
it('preserved demand allowance is excluded from offsettable blended energy rate',()=>{const b0=calculateBaseline(defaultEnergyProfile.consumption,{mode:'historical',userBlendedRateMxnPerKwh:0,preservedDemandAnnualMxn:0,notes:''});const b1=calculateBaseline(defaultEnergyProfile.consumption,{mode:'historical',userBlendedRateMxnPerKwh:0,preservedDemandAnnualMxn:12000,notes:''});expect(b1.blendedRateMxnPerKwh).toBeLessThan(b0.blendedRateMxnPerKwh)});
it('user-entered blended tariff mode works',()=>expect(calculateBaseline(defaultEnergyProfile.consumption,{mode:'blended',userBlendedRateMxnPerKwh:4.2,preservedDemandAnnualMxn:0,notes:''}).blendedRateMxnPerKwh).toBe(4.2));
it('monthly avoided energy is min consumption and production',()=>{const s=calculateSolarValue([{month:1,label:'Jan',specificYieldInput:1,productionKwh:120,consumptionKwh:100,balanceKwh:20}],{mode:'blended',annualConsumptionKwh:100,annualBilledMxn:300,blendedRateMxnPerKwh:3,valid:true,message:''},{exportMode:'zero',customExportRateMxnPerKwh:0});expect(s.annualAvoidedEnergyKwh).toBe(100);expect(s.annualSurplusKwh).toBe(20)});
it('zero surplus mode assigns no export value',()=>expect(calculateSolarValue([{month:1,label:'Jan',specificYieldInput:1,productionKwh:120,consumptionKwh:100,balanceKwh:20}],{mode:'blended',annualConsumptionKwh:100,annualBilledMxn:300,blendedRateMxnPerKwh:3,valid:true,message:''},{exportMode:'zero',customExportRateMxnPerKwh:0}).year1SurplusValueMxn).toBe(0));
it('same-rate surplus mode values surplus at blended rate',()=>expect(calculateSolarValue([{month:1,label:'Jan',specificYieldInput:1,productionKwh:120,consumptionKwh:100,balanceKwh:20}],{mode:'blended',annualConsumptionKwh:100,annualBilledMxn:300,blendedRateMxnPerKwh:3,valid:true,message:''},{exportMode:'same-rate',customExportRateMxnPerKwh:0}).year1SurplusValueMxn).toBe(60));
it('custom surplus mode uses custom rate',()=>expect(calculateSolarValue([{month:1,label:'Jan',specificYieldInput:1,productionKwh:120,consumptionKwh:100,balanceKwh:20}],{mode:'blended',annualConsumptionKwh:100,annualBilledMxn:300,blendedRateMxnPerKwh:3,valid:true,message:''},{exportMode:'custom',customExportRateMxnPerKwh:1.5}).year1SurplusValueMxn).toBe(30));
it('year-over-year production degradation is applied',()=>{const r=buildCashFlows(100000,11000,solar,fin);expect(r[2].projectedProductionKwh).toBeCloseTo(r[1].projectedProductionKwh*.995)});
it('tariff escalation increases energy value holding degradation neutral',()=>{const r=buildCashFlows(100000,11000,solar,{...fin,pvDegradationPct:0});expect(r[2].avoidedElectricityValueMxn).toBeCloseTo(r[1].avoidedElectricityValueMxn*1.04)});
it('O&M escalation compounds annually',()=>{const r=buildCashFlows(100000,11000,solar,fin);expect(r[2].omCostMxn).toBeCloseTo(1030)});
it('replacement allowance appears only in configured year',()=>{const r=buildCashFlows(100000,11000,solar,fin);expect(r[10].replacementCostMxn).toBe(5000);expect(r[9].replacementCostMxn).toBe(0)});
it('cumulative cash flow begins with year-0 investment',()=>expect(buildCashFlows(100000,11000,solar,fin)[0].cumulativeCashFlowMxn).toBe(-100000));
it('discounted cash flow uses discount rate',()=>{const r=buildCashFlows(100000,11000,solar,fin);expect(r[1].discountedCashFlowMxn).toBeCloseTo(r[1].netAnnualBenefitMxn/1.1)});
it('fractional simple payback interpolates crossing year',()=>{const rows=[{year:0,projectedProductionKwh:0,avoidedElectricityValueMxn:0,exportValueMxn:0,omCostMxn:0,replacementCostMxn:0,netAnnualBenefitMxn:-100,cumulativeCashFlowMxn:-100,discountedCashFlowMxn:-100},{year:1,projectedProductionKwh:0,avoidedElectricityValueMxn:60,exportValueMxn:0,omCostMxn:0,replacementCostMxn:0,netAnnualBenefitMxn:60,cumulativeCashFlowMxn:-40,discountedCashFlowMxn:60},{year:2,projectedProductionKwh:0,avoidedElectricityValueMxn:80,exportValueMxn:0,omCostMxn:0,replacementCostMxn:0,netAnnualBenefitMxn:80,cumulativeCashFlowMxn:40,discountedCashFlowMxn:80}];expect(simplePayback(rows)).toBeCloseTo(1.5)});
it('ROI is deterministic',()=>{const r=buildCashFlows(100000,11000,solar,fin),m=calculateFinancialMetrics(r,100000,10);expect(m.year1SimpleRoiPct).toBeCloseTo(r[1].netAnnualBenefitMxn/1000)});
it('NPV formula discounts all periods including year zero',()=>expect(npv(10,[-100,60,60])).toBeCloseTo(4.132,2));
it('IRR returns normal conventional solution',()=>expect(irr([-100,60,60])).toBeCloseTo(13.066,2));
it('IRR returns unavailable for multiple sign changes',()=>expect(irr([-100,230,-132])).toBeNull());
it('scenario engine returns Conservative/Base/Optimistic',()=>expect(buildScenarios(fin,{exportMode:'zero',customExportRateMxnPerKwh:0}).map(x=>x.id)).toEqual(['conservative','base','optimistic']));
it('sensitivity recomputes nine deterministic cells',()=>expect(calculateSensitivity(100000,11000,solar,fin)).toHaveLength(9));
it('persistence round-trip restores editable project state',()=>{const mem=new Map<string,string>();const storage={getItem:(k:string)=>mem.get(k)||null,setItem:(k:string,v:string)=>{mem.set(k,v)}};const s=createDefaultR4State();s.costBasis.exchangeRateMxnPerUsd=19.5;s.selectedScenarioId='conservative';saveR4State(s,storage);const loaded=loadR4State(storage);expect(loaded.costBasis.exchangeRateMxnPerUsd).toBe(19.5);expect(loaded.selectedScenarioId).toBe('conservative')});
it('R3 resource change recalculates R4 production',()=>{const design=createDefaultSiteDesign();design.layout.placements=Array.from({length:20},(_,i)=>({id:`m${i}`,roofId:'roof-1',x:0,y:0,orientation:'portrait',rotation:0,valid:true}));const s=createDefaultR4State();const e=createDefaultElectricalDesign();const a=deriveProjectEconomics(defaultEnergyProfile,design,e,s).annualProductionKwh;e.resource=e.resource.map(r=>({...r,specificYieldKwhPerKwp:r.specificYieldKwhPerKwp*1.1}));const b=deriveProjectEconomics(defaultEnergyProfile,design,e,s).annualProductionKwh;expect(b).toBeGreaterThan(a)});
});
