import {useCallback,useEffect,useMemo,useState} from 'react';
import type {Dispatch,SetStateAction} from 'react';
import {DEFAULT_EQUIPMENT_CATALOG} from './catalog';
import type {R4ProjectState} from './types';
export const ECONOMICS_STORAGE_KEY='solar-platform-v2:r4:economics:SOL-2026-0184';
export function createDefaultR4State():R4ProjectState{return{version:4,projectId:'SOL-2026-0184',catalog:structuredClone(DEFAULT_EQUIPMENT_CATALOG),manualBomLines:[],bomOverrides:[],costBasis:{exchangeRateMxnPerUsd:18,overheadType:'percent',overheadValue:5,vatRatePct:16},pricingRule:{strategy:'target-margin',markupPct:30,targetGrossMarginPct:28,fixedSellPriceBeforeVat:280000},commercialCosts:{salesCommissionType:'percent',salesCommissionValue:3,cacAllowance:3500,projectOperatingAllowance:0},cfe:{mode:'historical',userBlendedRateMxnPerKwh:3.2,preservedDemandAnnualMxn:0,notes:'Historical billed amounts preferred when complete. Demand/PF effects are not assumed eliminated by PV.'},solarValue:{exportMode:'zero',customExportRateMxnPerKwh:0},financial:{analysisTermYears:25,electricityEscalationPct:4,pvDegradationPct:.45,annualOmCostMxn:4000,omEscalationPct:3,replacementEnabled:true,replacementYear:13,replacementCostMxn:45000,discountRatePct:10,analysisBasis:'before-vat'},marginWarningThresholdPct:20,selectedScenarioId:'base',updatedAt:new Date(0).toISOString()};}
export function loadR4State(storage:Pick<Storage,'getItem'>=localStorage):R4ProjectState{try{const raw=storage.getItem(ECONOMICS_STORAGE_KEY);return raw?JSON.parse(raw) as R4ProjectState:createDefaultR4State()}catch{return createDefaultR4State()}}
export function saveR4State(s:R4ProjectState,storage:Pick<Storage,'setItem'>=localStorage){storage.setItem(ECONOMICS_STORAGE_KEY,JSON.stringify(s));}
let sharedState:R4ProjectState|undefined;const subscribers=new Set<Dispatch<SetStateAction<R4ProjectState>>>();
function currentR4State(){if(!sharedState)sharedState=loadR4State();return sharedState;}
export function useR4State(){const [state,setLocal]=useState<R4ProjectState>(()=>currentR4State());useEffect(()=>{subscribers.add(setLocal);return()=>{subscribers.delete(setLocal)}},[]);const setState=useCallback<Dispatch<SetStateAction<R4ProjectState>>>((update)=>{const prev=currentR4State();const next=typeof update==='function'?(update as (p:R4ProjectState)=>R4ProjectState)(prev):update;sharedState=next;saveR4State(next);setLocal(next);for(const subscriber of subscribers)if(subscriber!==setLocal)subscriber(next);},[]);return useMemo(()=>({state,setState}),[state,setState]);}
