import {describe,expect,it} from 'vitest';
import {autoString} from './autoString';
import {INVERTER_CATALOG,moduleById} from './catalog';
import {coldVocPerModule,dcAcRatio,installedDcKwp,stringElectrical} from './calculations';
import {annualProductionSummary,combineLosses,monthlyProduction,MEXICO_RESOURCE_FIXTURE} from './production';
import {createDefaultElectricalDesign,loadElectricalDesign,saveElectricalDesign} from './store';
import {validateElectricalDesign} from './validation';
const mod=moduleById('mod-640');const ids=Array.from({length:24},(_,i)=>`m${i+1}`);
describe('R3 electrical core',()=>{
it('computes installed DC kWp from placed modules',()=>expect(installedDcKwp(20,mod)).toBeCloseTo(12.8));
it('computes DC/AC ratio',()=>expect(dcAcRatio(25.6,20)).toBeCloseTo(1.28));
it('computes string Voc/Vmp/current',()=>{const e=stringElectrical({id:'s',name:'S',colorIndex:0,moduleIds:ids.slice(0,10)},mod,-5,25);expect(e.vocV).toBeCloseTo(521);expect(e.vmpV).toBeCloseTo(440);expect(e.impA).toBeCloseTo(14.55)});
it('cold Voc rises at colder temperature for negative coefficient',()=>expect(coldVocPerModule(mod,-5,25)).toBeGreaterThan(mod.vocV));
it('flags max DC voltage violation',()=>{const d=createDefaultElectricalDesign();d.strings=[{id:'s1',name:'S1',colorIndex:0,moduleIds:ids.slice(0,24),inverterId:'inv-1',mpptIndex:0}];expect(validateElectricalDesign(d,mod,ids,640).some(i=>i.code==='cold-voc-high')).toBe(true)});
it('flags MPPT range violation',()=>{const d=createDefaultElectricalDesign();d.strings=[{id:'s1',name:'S1',colorIndex:0,moduleIds:ids.slice(0,2),inverterId:'inv-1',mpptIndex:0}];expect(validateElectricalDesign(d,mod,ids.slice(0,2),640).some(i=>i.code==='mppt-voltage-range')).toBe(true)});
it('flags current limit for parallel strings',()=>{const d=createDefaultElectricalDesign();d.strings=[{id:'s1',name:'S1',colorIndex:0,moduleIds:ids.slice(0,8),inverterId:'inv-1',mpptIndex:0},{id:'s2',name:'S2',colorIndex:1,moduleIds:ids.slice(8,16),inverterId:'inv-1',mpptIndex:0},{id:'s3',name:'S3',colorIndex:2,moduleIds:ids.slice(16,24),inverterId:'inv-1',mpptIndex:0}];expect(validateElectricalDesign(d,mod,ids,640).some(i=>i.code==='mppt-current'||i.code==='too-many-inputs')).toBe(true)});
it('detects duplicate assignment',()=>{const d=createDefaultElectricalDesign();d.strings=[{id:'s1',name:'S1',colorIndex:0,moduleIds:['m1'],inverterId:'inv-1',mpptIndex:0},{id:'s2',name:'S2',colorIndex:1,moduleIds:['m1'],inverterId:'inv-1',mpptIndex:1}];expect(validateElectricalDesign(d,mod,['m1'],640).some(i=>i.code==='duplicate-assignment')).toBe(true)});
it('reports unassigned modules',()=>{const d=createDefaultElectricalDesign();expect(validateElectricalDesign(d,mod,['m1'],640).some(i=>i.code==='unassigned-modules')).toBe(true)});
it('auto-string is deterministic',()=>{const d=createDefaultElectricalDesign();expect(autoString(ids,d,mod)).toEqual(autoString(ids,d,mod))});
it('auto-string assigns unique modules',()=>{const d=createDefaultElectricalDesign();const a=autoString(ids,d,mod).flatMap(s=>s.moduleIds);expect(new Set(a).size).toBe(a.length)});
it('persists round-trip',()=>{let raw='';const storage={getItem:()=>raw||null,setItem:(_:string,v:string)=>{raw=v}};const d=createDefaultElectricalDesign();d.assumptions.minimumDesignTempC=-10;saveElectricalDesign(d,storage);expect(loadElectricalDesign(storage).assumptions.minimumDesignTempC).toBe(-10)});
it('monthly production follows formula',()=>{const d=createDefaultElectricalDesign();const r=monthlyProduction(10,[MEXICO_RESOURCE_FIXTURE[0]],d.assumptions,[1000]);expect(r[0].productionKwh).toBeGreaterThan(1000)});
it('annual sum equals monthly sum',()=>{const d=createDefaultElectricalDesign();const r=monthlyProduction(10,MEXICO_RESOURCE_FIXTURE,d.assumptions,Array(12).fill(1000));const a=annualProductionSummary(10,r,d.assumptions);expect(a.annualProductionKwh).toBeCloseTo(r.reduce((s,x)=>s+x.productionKwh,0))});
it('combines losses multiplicatively',()=>{const d=createDefaultElectricalDesign();d.assumptions.soilingPct=10;d.assumptions.mismatchPct=10;d.assumptions.wiringPct=0;d.assumptions.availabilityPct=0;expect(combineLosses(d.assumptions).remainingFactor).toBeCloseTo(.81)});
it('specific yield derives from annual production/DC capacity',()=>{const d=createDefaultElectricalDesign();const r=monthlyProduction(10,MEXICO_RESOURCE_FIXTURE,d.assumptions,[]);expect(annualProductionSummary(10,r,d.assumptions).specificYieldKwhPerKwp).toBeCloseTo(r.reduce((s,x)=>s+x.productionKwh,0)/10)});
it('annual energy offset compares production and consumption without billing claims',()=>{const d=createDefaultElectricalDesign();const r=monthlyProduction(10,MEXICO_RESOURCE_FIXTURE,d.assumptions,Array(12).fill(1000));expect(annualProductionSummary(10,r,d.assumptions).energyOffsetPct).toBeGreaterThan(100)});
it('recalculates when module count/resource/loss changes',()=>{const d=createDefaultElectricalDesign();const base=annualProductionSummary(10,monthlyProduction(10,MEXICO_RESOURCE_FIXTURE,d.assumptions,[]),d.assumptions).annualProductionKwh;d.assumptions.soilingPct=10;const changed=annualProductionSummary(20,monthlyProduction(20,MEXICO_RESOURCE_FIXTURE.map(x=>({...x,specificYieldKwhPerKwp:x.specificYieldKwhPerKwp*.9})),d.assumptions,[]),d.assumptions).annualProductionKwh;expect(changed).not.toBeCloseTo(base)});
it('fixture inverter catalog contains MPPT constraints',()=>expect(INVERTER_CATALOG[0].mppt.count).toBeGreaterThan(0));
});
