import express from 'express';import cors from 'cors';import helmet from 'helmet';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import multer from 'multer';import {createHash} from 'node:crypto';import {z,ZodError} from 'zod';
import {env} from './env';import {pool,ping,tx} from './db';import {createSession,destroySession,requireAuth,requirePermission,verifyPassword} from './auth';import {signInSchema,brandUpdateSchema,preferenceSchema,projectStateSchema,proposalVersionSchema,migrationPreviewSchema} from './schemas';import {ConflictError,ImmutableError,NotFoundError,audit,createProposalVersion,getBrand,getProjectState,listProjects,putProjectState,updateBrand,updateProposalVersion,upsertBusinessRecord} from './repository';import type {CrmState,CrmProjectSummary} from '../src/domain/crm/types';import {moveOpportunity} from '../src/domain/crm/transitions';

const app=express();app.disable('x-powered-by');app.use(helmet({crossOriginResourcePolicy:{policy:'same-site'}}));app.use(cors({origin:env.APP_ORIGIN,credentials:true,methods:['GET','POST','PUT','PATCH','DELETE']}));app.use(cookieParser());app.use(express.json({limit:'3mb'}));app.use(rateLimit({windowMs:60_000,limit:env.API_RATE_LIMIT,standardHeaders:'draft-7',legacyHeaders:false}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const origin=req.get('origin');if(origin&&origin!==env.APP_ORIGIN)return res.status(403).json({error:{code:'ORIGIN_REJECTED'}})}next()});
const authLimiter=rateLimit({windowMs:60_000,limit:env.AUTH_RATE_LIMIT,standardHeaders:'draft-7',legacyHeaders:false});

app.get('/api/health',async(_req,res,next)=>{try{await ping();res.json({ok:true,service:'solar-platform-v2-api'})}catch(e){next(e)}});
app.post('/api/auth/sign-in',authLimiter,async(req,res,next)=>{try{const input=signInSchema.parse(req.body);const q=await pool.query(`select u.id,u.email,u.display_name,u.password_hash,o.id organization_id,o.slug,m.role,coalesce(p.locale,o.default_locale) locale from users u join memberships m on m.user_id=u.id and m.active join organizations o on o.id=m.organization_id left join user_preferences p on p.user_id=u.id and p.organization_id=o.id where lower(u.email)=lower($1) and u.active and ($2::text is null or o.slug=$2) order by o.created_at limit 1`,[input.email,input.organizationSlug??null]);if(!q.rowCount||!await verifyPassword(input.password,q.rows[0].password_hash))return res.status(401).json({error:{code:'INVALID_CREDENTIALS'}});const expiresAt=await createSession(q.rows[0].id,res,req);res.json({user:{id:q.rows[0].id,email:q.rows[0].email,displayName:q.rows[0].display_name},organization:{id:q.rows[0].organization_id,slug:q.rows[0].slug},role:q.rows[0].role,locale:q.rows[0].locale,expiresAt})}catch(e){next(e)}});
app.post('/api/auth/sign-out',requireAuth,async(req,res,next)=>{try{await destroySession(req,res);res.status(204).end()}catch(e){next(e)}});
app.get('/api/auth/me',requireAuth,(req,res)=>res.json(req.auth));

app.get('/api/orgs/:orgId/branding',requireAuth,requirePermission('org.settings.read'),async(req,res,next)=>{try{res.json(await getBrand(req.auth!.organizationId))}catch(e){next(e)}});
app.put('/api/orgs/:orgId/branding',requireAuth,requirePermission('org.settings.write'),async(req,res,next)=>{try{const input=brandUpdateSchema.parse(req.body);res.json(await tx(c=>updateBrand(req.auth!.organizationId,input,req.auth!.userId,c)))}catch(e){next(e)}});
app.put('/api/orgs/:orgId/preferences',requireAuth,async(req,res,next)=>{try{const input=preferenceSchema.parse(req.body);await pool.query(`insert into user_preferences(user_id,organization_id,locale) values($1,$2,$3) on conflict(user_id,organization_id) do update set locale=excluded.locale,updated_at=now()`,[req.auth!.userId,req.auth!.organizationId,input.locale]);await audit(req.auth!.organizationId,req.auth!.userId,'user-preference',req.auth!.userId,'locale-updated',null,{locale:input.locale});res.json(input)}catch(e){next(e)}});

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024,files:1},fileFilter(_req,file,cb){cb(null,['image/png','image/jpeg','image/webp'].includes(file.mimetype))}});
app.post('/api/orgs/:orgId/branding/logo',requireAuth,requirePermission('org.settings.write'),upload.single('logo'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:{code:'INVALID_LOGO',message:'PNG/JPEG/WebP required'}});const sha=createHash('sha256').update(req.file.buffer).digest('hex');const out=await tx(async c=>{const a=await c.query(`insert into organization_assets(organization_id,kind,filename,mime_type,byte_size,content,sha256) values($1,'logo',$2,$3,$4,$5,$6) on conflict(organization_id,sha256) do update set filename=excluded.filename returning id,filename,mime_type as "mimeType",byte_size as "byteSize",sha256`,[req.auth!.organizationId,req.file!.originalname,req.file!.mimetype,req.file!.size,req.file!.buffer,sha]);await c.query('update organization_branding set logo_asset_id=$2,updated_at=now(),version=version+1 where organization_id=$1',[req.auth!.organizationId,a.rows[0].id]);await audit(req.auth!.organizationId,req.auth!.userId,'organization-branding',req.auth!.organizationId,'logo-updated',null,{assetId:a.rows[0].id,sha256:sha},c);return a.rows[0]});res.status(201).json(out)}catch(e){next(e)}});
app.get('/api/orgs/:orgId/assets/:assetId',requireAuth,async(req,res,next)=>{try{const q=await pool.query('select mime_type,content from organization_assets where organization_id=$1 and id=$2',[req.auth!.organizationId,req.params.assetId]);if(!q.rowCount)throw new NotFoundError();res.set('Content-Type',q.rows[0].mime_type).set('Cache-Control','private,max-age=3600').send(q.rows[0].content)}catch(e){next(e)}});

app.get('/api/orgs/:orgId/projects',requireAuth,requirePermission('projects.read'),async(req,res,next)=>{try{res.json(await listProjects(req.auth!.organizationId))}catch(e){next(e)}});
app.get('/api/orgs/:orgId/projects/:projectId/state',requireAuth,requirePermission('projects.read'),async(req,res,next)=>{try{res.json(await getProjectState(req.auth!.organizationId,req.params.projectId))}catch(e){next(e)}});
app.put('/api/orgs/:orgId/projects/:projectId/state',requireAuth,requirePermission('projects.write'),async(req,res,next)=>{try{const input=projectStateSchema.parse(req.body);res.json(await tx(c=>putProjectState(req.auth!.organizationId,req.params.projectId,input,req.auth!.userId,c)))}catch(e){next(e)}});
app.get('/api/orgs/:orgId/projects/:projectId/economics',requireAuth,requirePermission('economics.read'),async(req,res,next)=>{try{const state=await getProjectState(req.auth!.organizationId,req.params.projectId);const r4:any=state.r4||{};const allowed=(await import('./rbac')).hasPermission(req.auth!.role,'economics.internal.read');if(allowed)return res.json(r4);const {costs,bom,costBreakdown,grossMarginPct,grossMarginMxn,...publicEconomics}=r4;res.json({...publicEconomics,internalFieldsRedacted:true})}catch(e){next(e)}});

app.post('/api/orgs/:orgId/projects/:projectId/proposals/versions',requireAuth,requirePermission('proposal.write'),async(req,res,next)=>{try{const input=proposalVersionSchema.parse(req.body);res.status(201).json(await tx(c=>createProposalVersion(req.auth!.organizationId,req.params.projectId,input,req.auth!.userId,c)))}catch(e){next(e)}});
app.put('/api/orgs/:orgId/proposals/:proposalId/versions/:version',requireAuth,requirePermission('proposal.write'),async(req,res,next)=>{try{const input=proposalVersionSchema.omit({proposalId:true,versionNumber:true}).parse(req.body);res.json(await tx(c=>updateProposalVersion(req.auth!.organizationId,req.params.proposalId,Number(req.params.version),input,req.auth!.userId,c)))}catch(e){next(e)}});

app.get('/api/orgs/:orgId/records/:type',requireAuth,async(req,res,next)=>{try{const permission=req.params.type==='handoff'?'handoff.read':req.params.type==='opportunity'?'crm.read':'projects.read';if(!(await import('./rbac')).hasPermission(req.auth!.role,permission as any))return res.status(403).json({error:{code:'FORBIDDEN'}});const q=await pool.query('select id,project_id as "projectId",status,owner_user_id as "ownerUserId",payload,version,updated_at as "updatedAt" from business_records where organization_id=$1 and record_type=$2 order by updated_at desc',[req.auth!.organizationId,req.params.type]);res.json(q.rows)}catch(e){next(e)}});
app.put('/api/orgs/:orgId/records/:type/:id',requireAuth,async(req,res,next)=>{try{const type=req.params.type,perm=type==='handoff'?'handoff.write':type==='opportunity'?'crm.write':type==='task'?'tasks.write':'projects.write';if(!(await import('./rbac')).hasPermission(req.auth!.role,perm as any))return res.status(403).json({error:{code:'FORBIDDEN'}});const body=z.object({payload:z.unknown(),status:z.string().nullable().optional(),projectId:z.string().nullable().optional(),ownerUserId:z.string().uuid().nullable().optional(),expectedVersion:z.number().int().positive().optional()}).strict().parse(req.body);res.json(await tx(c=>upsertBusinessRecord(req.auth!.organizationId,type,req.params.id,body.payload,body.status??null,body.projectId??null,body.ownerUserId??null,body.expectedVersion,req.auth!.userId,c)))}catch(e){next(e)}});

app.post('/api/orgs/:orgId/migrations/legacy/preview',requireAuth,requirePermission('projects.write'),async(req,res,next)=>{try{const input=migrationPreviewSchema.parse(req.body);const exists=await pool.query('select 1 from projects where organization_id=$1 and id=$2',[req.auth!.organizationId,input.projectId]);const frozen=Object.values(input.records).flatMap((v:any)=>Array.isArray(v?.versions)?v.versions:[]).filter((v:any)=>['Exported','Frozen'].includes(v?.status));res.json({ok:true,formatVersion:input.formatVersion,projectId:input.projectId,conflicts:exists.rowCount?[{code:'PROJECT_EXISTS',projectId:input.projectId}]:[],frozenProposalVersions:frozen.length,ownerMapping:{'u-dg':req.auth!.userId,'u-lm':null,'u-eng':null},willOverwrite:false})}catch(e){next(e)}});
app.post('/api/orgs/:orgId/migrations/legacy/import',requireAuth,requirePermission('projects.write'),async(req,res,next)=>{try{const input=migrationPreviewSchema.parse(req.body);const result=await tx(async c=>{const exists=await c.query('select 1 from projects where organization_id=$1 and id=$2',[req.auth!.organizationId,input.projectId]);if(exists.rowCount)throw new ConflictError('Legacy import will not overwrite an existing project');await c.query('insert into projects(id,organization_id,name,status) values($1,$2,$3,$4)',[input.projectId,req.auth!.organizationId,`Migrated ${input.projectId}`,'active']);const r:any=input.records;await c.query('insert into project_states(project_id,organization_id,schema_version,r1,r2,r3,r4,r5,r6) values($1,$2,1,$3,$4,$5,$6,$7,$8)',[input.projectId,req.auth!.organizationId,r.r1??{},r.r2??{},r.r3??{},r.r4??{},r.r5??{},r.r6??{}]);await audit(req.auth!.organizationId,req.auth!.userId,'legacy-import',input.projectId,'legacy-imported',null,{formatVersion:1},c);return{projectId:input.projectId,imported:true}});res.status(201).json(result)}catch(e){next(e)}});

app.post('/api/orgs/:orgId/crm/won',requireAuth,requirePermission('crm.write'),async(req,res,next)=>{try{const body=z.object({crmState:z.unknown(),opportunityId:z.string(),summary:z.unknown(),expectedVersion:z.number().int().positive()}).strict().parse(req.body);const result=await tx(async c=>{const current=await c.query(`select payload,version from business_records where organization_id=$1 and record_type='crm-state' and id='default' for update`,[req.auth!.organizationId]);if(!current.rowCount||current.rows[0].version!==body.expectedVersion)throw new ConflictError();const state=current.rows[0].payload as CrmState;const transition=moveOpportunity(state,body.opportunityId,'won',new Date().toISOString(),req.auth!.userId,body.summary as CrmProjectSummary,{explicitWin:true});if(!transition.ok)return{ok:false,issues:transition.issues};await c.query(`update business_records set payload=$2,version=version+1,updated_at=now() where organization_id=$1 and record_type='crm-state' and id='default'`,[req.auth!.organizationId,transition.state]);await audit(req.auth!.organizationId,req.auth!.userId,'opportunity',body.opportunityId,'won',state.opportunities.find(o=>o.id===body.opportunityId),transition.state.opportunities.find(o=>o.id===body.opportunityId),c);return{ok:true,state:transition.state,version:body.expectedVersion+1}});res.json(result)}catch(e){next(e)}});

app.get('/api/orgs/:orgId/audit',requireAuth,requirePermission('audit.read'),async(req,res,next)=>{try{const q=await pool.query('select id,actor_user_id as "actorUserId",resource_type as "resourceType",resource_id as "resourceId",event_type as "eventType",before_meta as "before",after_meta as "after",created_at as "createdAt" from audit_entries where organization_id=$1 order by created_at desc limit 200',[req.auth!.organizationId]);res.json(q.rows)}catch(e){next(e)}});

app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof ZodError)return res.status(400).json({error:{code:'VALIDATION_ERROR',issues:err.issues.map(i=>({path:i.path.join('.'),message:i.message}))}});if(err instanceof ConflictError)return res.status(409).json({error:{code:'CONFLICT',message:err.message}});if(err instanceof ImmutableError)return res.status(409).json({error:{code:'IMMUTABLE',message:err.message}});if(err instanceof NotFoundError)return res.status(404).json({error:{code:'NOT_FOUND'}});if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:{code:'LOGO_TOO_LARGE'}});console.error(err);res.status(500).json({error:{code:'INTERNAL_ERROR'}})});
export default app;
