import type {DbClient} from './db';import {pool} from './db';
export class ConflictError extends Error{code='CONFLICT' as const;constructor(message='Version conflict'){super(message)}}
export class NotFoundError extends Error{code='NOT_FOUND' as const;constructor(message='Not found'){super(message)}}
export class ImmutableError extends Error{code='IMMUTABLE' as const;constructor(message='Frozen/exported proposal version is immutable'){super(message)}}
export type Queryable={query:(text:string,params?:any[])=>Promise<any>};
export async function getBrand(orgId:string,db:Queryable=pool){const q=await db.query(`select o.id,o.slug,o.display_name as "displayName",o.short_name as "shortName",o.legal_name as "legalName",o.default_locale as "defaultLocale",o.default_currency as "defaultCurrency",o.timezone,b.tagline,b.primary_color as "primaryColor",b.secondary_color as "secondaryColor",b.accent_color as "accentColor",b.graphite_color as "graphiteColor",b.dark_graphite_color as "darkGraphiteColor",b.surface_color as "surfaceColor",b.website,b.email,b.phone,b.footer_text as "footerText",b.logo_asset_id as "logoAssetId",b.favicon_asset_id as "faviconAssetId",b.proposal_defaults as "proposalDefaults",greatest(o.version,b.version) version from organizations o join organization_branding b on b.organization_id=o.id where o.id=$1`,[orgId]);if(!q.rowCount)throw new NotFoundError();return q.rows[0]}
export async function updateBrand(orgId:string,input:any,actorId:string,db:Queryable=pool){const current=await getBrand(orgId,db);if(current.version!==input.expectedVersion)throw new ConflictError();const q=await db.query(`with ou as (update organizations set display_name=$2,short_name=$3,legal_name=$4,default_locale=$5,default_currency=$6,timezone=$7,updated_at=now(),version=version+1 where id=$1 returning version) update organization_branding set tagline=$8,primary_color=$9,secondary_color=$10,accent_color=$11,graphite_color=$12,dark_graphite_color=$13,surface_color=$14,website=nullif($15,''),email=nullif($16,''),phone=$17,footer_text=$18,updated_at=now(),version=version+1 where organization_id=$1 returning version`,[orgId,input.displayName,input.shortName,input.legalName??null,input.defaultLocale,input.defaultCurrency,input.timezone,input.tagline,input.primaryColor,input.secondaryColor,input.accentColor,input.graphiteColor,input.darkGraphiteColor,input.surfaceColor,input.website??null,input.email??null,input.phone??null,input.footerText??null]);await audit(orgId,actorId,'organization-branding',orgId,'branding-updated',{version:current.version},{version:q.rows[0].version},db);return getBrand(orgId,db)}
export async function getProjectState(orgId:string,projectId:string,db:Queryable=pool){const q=await db.query('select schema_version as "schemaVersion",r1,r2,r3,r4,r5,r6,version,updated_at as "updatedAt" from project_states where organization_id=$1 and project_id=$2',[orgId,projectId]);if(!q.rowCount)throw new NotFoundError();return q.rows[0]}
export async function putProjectState(orgId:string,projectId:string,input:any,actorId:string,db:Queryable=pool){const q=await db.query(`update project_states set schema_version=$3,r1=$4,r2=$5,r3=$6,r4=$7,r5=$8,r6=$9,updated_at=now(),version=version+1 where organization_id=$1 and project_id=$2 and version=$10 returning version,updated_at as "updatedAt"`,[orgId,projectId,input.schemaVersion,input.r1,input.r2,input.r3,input.r4,input.r5,input.r6,input.expectedVersion]);if(!q.rowCount)throw new ConflictError();await audit(orgId,actorId,'project-state',projectId,'project-state-updated',{version:input.expectedVersion},{version:q.rows[0].version},db);return getProjectState(orgId,projectId,db)}
export async function listProjects(orgId:string,db:Queryable=pool){const q=await db.query(`select id,name,customer_name as "customerName",location,status,version,updated_at as "updatedAt" from projects where organization_id=$1 order by updated_at desc`,[orgId]);return q.rows}
export async function audit(orgId:string,actorId:string|null,resourceType:string,resourceId:string,eventType:string,before:any,after:any,db:Queryable=pool){await db.query('insert into audit_entries(organization_id,actor_user_id,resource_type,resource_id,event_type,before_meta,after_meta) values($1,$2,$3,$4,$5,$6,$7)',[orgId,actorId,resourceType,resourceId,eventType,before??null,after??null])}
export async function createProposalVersion(orgId:string,projectId:string,input:any,actorId:string,db:Queryable=pool){const existing=await db.query('select 1 from proposal_versions where organization_id=$1 and proposal_id=$2 and version_number=$3',[orgId,input.proposalId,input.versionNumber]);if(existing.rowCount)throw new ConflictError('Proposal version already exists');const q=await db.query(`insert into proposal_versions(organization_id,project_id,proposal_id,version_number,status,canonical_snapshot,branding_snapshot,locale,pdf_sha256,exported_at,frozen_at,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,case when $5 in ('Exported','Frozen') then now() end,case when $5 in ('Exported','Frozen') then now() end,$10) returning *`,[orgId,projectId,input.proposalId,input.versionNumber,input.status,input.canonicalSnapshot,input.brandingSnapshot,input.locale,input.pdfSha256??null,actorId]);await audit(orgId,actorId,'proposal-version',`${input.proposalId}:${input.versionNumber}`,'proposal-version-created',null,{status:input.status},db);return q.rows[0]}
export async function updateProposalVersion(orgId:string,proposalId:string,versionNumber:number,payload:any,actorId:string,db:Queryable=pool){const cur=await db.query('select status from proposal_versions where organization_id=$1 and proposal_id=$2 and version_number=$3',[orgId,proposalId,versionNumber]);if(!cur.rowCount)throw new NotFoundError();if(['Exported','Frozen'].includes(cur.rows[0].status))throw new ImmutableError();const q=await db.query('update proposal_versions set status=$4,canonical_snapshot=$5,branding_snapshot=$6,locale=$7 where organization_id=$1 and proposal_id=$2 and version_number=$3 returning *',[orgId,proposalId,versionNumber,payload.status,payload.canonicalSnapshot,payload.brandingSnapshot,payload.locale]);await audit(orgId,actorId,'proposal-version',`${proposalId}:${versionNumber}`,'proposal-version-updated',{status:cur.rows[0].status},{status:payload.status},db);return q.rows[0]}
export async function upsertBusinessRecord(orgId:string,type:string,id:string,payload:any,status:string|null,projectId:string|null,ownerUserId:string|null,expectedVersion:number|undefined,actorId:string,db:Queryable=pool){if(expectedVersion===undefined){const q=await db.query(`insert into business_records(organization_id,record_type,id,project_id,status,owner_user_id,payload) values($1,$2,$3,$4,$5,$6,$7) on conflict do nothing returning version`,[orgId,type,id,projectId,status,ownerUserId,payload]);if(!q.rowCount)throw new ConflictError();await audit(orgId,actorId,type,id,'created',null,{status},db);return q.rows[0]}const q=await db.query(`update business_records set payload=$4,status=$5,project_id=$6,owner_user_id=$7,updated_at=now(),version=version+1 where organization_id=$1 and record_type=$2 and id=$3 and version=$8 returning version`,[orgId,type,id,payload,status,projectId,ownerUserId,expectedVersion]);if(!q.rowCount)throw new ConflictError();await audit(orgId,actorId,type,id,'updated',{version:expectedVersion},{version:q.rows[0].version},db);return q.rows[0]}
