import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Bot,CheckCircle2,FileSearch,History,LineChart,Loader2,ShieldCheck,Upload,WalletCards} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api,ApiError} from '../r7/api';
import {useAuth} from '../r7/auth';
import {platform} from '../platform';
import '../r8.css';

type Tab='capture'|'review'|'history'|'scenarios'|'copilot'|'usage';
export function AISolarIntelligence(){const {session}=useAuth(),[params]=useSearchParams(),projectId=params.get('project')||'SOL-2026-0184',[tab,setTab]=useState<Tab>('capture'),[documents,setDocuments]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[intel,setIntel]=useState<any>(null),[usage,setUsage]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[copilot,setCopilot]=useState<any>(null),[error,setError]=useState('');const org=session?.organizationId;
 const refresh=async()=>{if(!org)return;const [docs,next]=await Promise.all([api.aiDocuments(org,projectId),api.projectIntelligence(org,projectId).catch(()=>null)]);setDocuments(docs);setIntel(next);if(!selected&&docs[0])setSelected(docs[0])};useEffect(()=>{refresh().catch(()=>{})},[org,projectId]);
 const upload=async(camera=false)=>{if(!org)return;const file=camera?await platform.capturePhoto():await platform.pickFile(['application/pdf','image/jpeg','image/png']);if(!file)return;setBusy(true);setError('');try{const doc=await api.uploadBill(org,file,projectId);await api.extractBill(org,doc.id);await refresh();setTab('review')}catch(e){setError(e instanceof ApiError?e.code:'No se pudo procesar el documento')}finally{setBusy(false)}};
 const ask=async()=>{if(!org||!message.trim())return;setBusy(true);setError('');try{setCopilot(await api.copilot(org,{message,projectId}))}catch(e){setError(e instanceof ApiError?e.code:'Copilot no disponible')}finally{setBusy(false)}};
 const tabs:Tab[]=['capture','review','history','scenarios','copilot','usage'];const labels:any={capture:'Captura CFE',review:'Revisión',history:'Historial',scenarios:'Escenarios',copilot:'Copilot',usage:'Uso IA'};
 return <main className="page r8-page"><header className="r8-hero"><div><span className="eyebrow">R8 · AI SOLAR INTELLIGENCE</span><h1>Inteligencia CFE con verdad determinística</h1><p>La IA extrae y explica. Los motores R1–R4 siguen calculando ingeniería y economía.</p></div><div className="r8-gate"><ShieldCheck/><b>{intel?.readiness?.score??0}/100</b><span>{intel?.readiness?.ready?'Listo para cotizar':'Revisión requerida'}</span></div></header><nav className="r8-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{labels[x]}</button>)}</nav>{error&&<div className="r8-alert"><AlertTriangle/> {error}. El flujo manual permanece disponible.</div>}
 {tab==='capture'&&<section className="r8-grid"><article className="r8-card upload-card"><Upload/><h2>Sube o fotografía recibos CFE</h2><p>PDF, JPEG o PNG · hasta 15 MB · almacenamiento privado · deduplicación SHA-256.</p><div><button className="primary" onClick={()=>upload(false)} disabled={busy}>{busy?<Loader2 className="spin"/>:'Seleccionar archivo'}</button><button className="secondary" onClick={()=>upload(true)} disabled={busy}>Usar cámara</button></div></article><article className="r8-card"><h3>Controles antes de IA</h3><ul><li>Magic bytes y MIME</li><li>Nombre saneado y seguridad básica</li><li>Hash contra duplicados</li><li>Acceso por tenant y rol</li></ul></article></section>}
 {tab==='review'&&<Review documents={documents} selected={selected} onSelect={setSelected} org={org!} refresh={refresh}/>} 
 {tab==='history'&&<section className="r8-card"><div className="section-title"><History/><div><h2>Perfil normalizado</h2><p>Nunca se inventan meses ausentes.</p></div></div><div className="metric-row"><Metric label="Cobertura" value={`${Math.round((intel?.profile?.completeness??0)*100)}%`}/><Metric label="Días fuente" value={intel?.profile?.coveredDays??0}/><Metric label="kWh fuente" value={(intel?.profile?.totalKwh??0).toLocaleString()}/><Metric label="Anualizado" value={intel?.profile?.annualizedKwh?.toLocaleString()??'No defendible'}/></div><div className="billing-context"><b>Contexto de facturación</b><span>Tarifa {intel?.billingContext?.tariff??'por confirmar'} · fuente: {intel?.billingContext?.source??'unknown'}</span><small>{intel?.billingContext?.effectiveBlendedRate!=null?`Tasa efectiva del recibo: $${Number(intel.billingContext.effectiveBlendedRate).toFixed(4)}/kWh (total ÷ kWh fuente)`:'Sin tasa defendible; no se inventó una tarifa vigente.'}</small></div><div className="history-list">{intel?.profile?.entries?.map((x:any)=><div key={`${x.periodStart}-${x.periodEnd}`}><b>{x.periodStart} → {x.periodEnd}</b><span>{x.kwh.toLocaleString()} kWh</span><em>{x.provenance}</em></div>)||<p>Sin periodos validados.</p>}</div></section>}
 {tab==='scenarios'&&<section><div className="readiness"><h2>Quote readiness explicable</h2><strong>{intel?.readiness?.score??0}/100</strong><div>{Object.entries(intel?.readiness?.components||{}).map(([k,v])=><span key={k}><b>{String(k)}</b>{String(v)}</span>)}</div>{intel?.readiness?.recommendations?.map((x:string)=><p key={x}><AlertTriangle/> {x}</p>)}</div><div className="scenario-grid">{intel?.scenarios?.length?intel.scenarios.map((s:any)=><article className="r8-card" key={s.id}><small>{s.source}</small><h3>{s.name||s.id}</h3><pre>{JSON.stringify(s,null,2)}</pre></article>):<article className="r8-card empty"><LineChart/><h3>Aún no hay escenarios aceptados</h3><p>Primero resuelve la revisión y ejecuta los motores existentes R1–R4. R8 no fabrica cifras.</p></article>}</div></section>}
 {tab==='copilot'&&<section className="r8-card copilot"><div className="section-title"><Bot/><div><h2>Copilot con contexto autorizado</h2><p>Sin SQL directo, herramientas permitidas y respuestas con procedencia.</p></div></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="¿De dónde salió el consumo anual?"/><button className="primary" onClick={ask} disabled={busy}>Preguntar</button>{copilot&&<div className="copilot-answer"><p>{copilot.answer}</p><small>Fuentes: {copilot.citations?.join(', ')||'contexto autorizado'}</small></div>}</section>}
 {tab==='usage'&&<Usage org={org!} rows={usage} setRows={setUsage}/>}</main>}

function Review({documents,selected,onSelect,org,refresh}:{documents:any[];selected:any;onSelect:(x:any)=>void;org:string;refresh:()=>Promise<void>}){const [busy,setBusy]=useState(false);const active=useMemo(()=>documents.find(x=>x.id===selected?.id)||documents[0],[documents,selected]);const accept=async()=>{if(!active)return;setBusy(true);try{await api.acceptBill(org,active.id);await refresh()}finally{setBusy(false)}};const correct=async(key:string,current:unknown)=>{const value=window.prompt(`Valor normalizado para ${key}`,current==null?'':String(current));if(value===null)return;const normalized=typeof current==='number'?Number(value):value;setBusy(true);try{await api.correctBillField(org,active.id,{fieldPath:key,normalized,reason:'Corrección explícita del revisor'});await refresh()}finally{setBusy(false)}};const fields=Object.entries(active?.extraction?.fields||{});return <section className="review-layout"><aside className="r8-card doc-list"><h3>Documentos privados</h3>{documents.map(d=><button key={d.id} onClick={()=>onSelect(d)} className={active?.id===d.id?'active':''}><FileSearch/><span><b>{d.filename}</b><small>{d.status} · {d.sha256.slice(0,10)}…</small></span></button>)}</aside><article className="r8-card document-preview">{active?<><iframe title="Documento CFE" src={api.billContentUrl(org,active.id)}/><small>Documento original protegido por sesión y tenant.</small></>:<p>Sube un recibo para comenzar.</p>}</article><article className="r8-card extracted"><h2>Extracción y procedencia</h2>{fields.map(([key,value]:[string,any])=><div className="extracted-field" key={key}><div><b>{key}</b><span>{String(value.normalized??'Sin valor')}</span></div><small>Confianza {Math.round((value.confidence??0)*100)}% · {value.method} · pág. {value.provenance?.page??'—'} {value.provenance?.region?`· ${value.provenance.region.join(', ')}`:''}</small><em>{value.provenance?.text||value.raw||'Sin fragmento fuente'}</em><button className="secondary" disabled={busy} onClick={()=>correct(key,value.normalized)}>Corregir</button></div>)}{active?.validationIssues?.map((x:any)=><div className={x.severity==='blocking'?'issue blocking':'issue'} key={`${x.code}-${x.field}`}><AlertTriangle/><span><b>{x.code}</b>{x.message}</span></div>)}<div className="ready-line">{active&&!active.reviewBlocked?<CheckCircle2/>:<AlertTriangle/>}<b>{active&&!active.reviewBlocked?'Ready for project':'Bloqueado hasta resolver revisión'}</b></div><button className="primary" disabled={!active||active.reviewBlocked||busy} onClick={accept}>Aceptar y construir historial</button></article></section>}
function Usage({org,rows,setRows}:{org:string;rows:any[];setRows:(x:any[])=>void}){useEffect(()=>{api.aiUsage(org).then(setRows).catch(()=>setRows([]))},[org]);return <section className="r8-card"><div className="section-title"><WalletCards/><div><h2>Uso, costo y fallos de IA</h2><p>Metadatos operativos sin secretos ni chain-of-thought.</p></div></div><table><thead><tr><th>Día</th><th>Operación</th><th>Proveedor</th><th>Estado</th><th>Llamadas</th><th>Costo USD</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.day}</td><td>{r.operation}</td><td>{r.provider}</td><td>{r.status}</td><td>{r.calls}</td><td>{Number(r.costUsd).toFixed(4)}</td></tr>)}</tbody></table></section>}
function Metric({label,value}:{label:string;value:string|number}){return <div><small>{label}</small><b>{value}</b></div>}
