import {useMemo,useRef,useState} from 'react';
import {AlertTriangle,CheckCircle2,Download,FileText,Plus,Trash2,Upload} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {WorkflowStrip} from '../components/ProjectContext';
import {csvTemplate,parseConsumptionCsv} from '../domain/energy/csv';
import {deriveEnergyMetrics} from '../domain/energy/metrics';
import {generateSizingScenarios} from '../domain/energy/sizing';
import {useEnergyProfile} from '../domain/energy/store';
import {tariffs,tariffFamily,requiresDemand,supportsPowerFactor,type TariffCode,type ConsumptionEntry} from '../domain/energy/types';
import {dataQualityStatus,validateEnergyProfile} from '../domain/energy/validation';

const fmt=(n:number,d=0)=>n.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
export function Consumption(){const {profile,setProfile}=useEnergyProfile();const [sp]=useSearchParams();const initial=sp.get('view')||'manual';const [tab,setTab]=useState(initial==='csv'?'csv':initial==='sizing'?'sizing':'manual');const [csvText,setCsvText]=useState(csvTemplate);const [csvErrors,setCsvErrors]=useState<string[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 const issues=useMemo(()=>validateEnergyProfile(profile),[profile]);const quality=dataQualityStatus(issues);const metrics=useMemo(()=>deriveEnergyMetrics(profile),[profile]);const scenarios=useMemo(()=>generateSizingScenarios(metrics.annualKwh,profile.objective.targetOffset,profile.assumptions),[metrics.annualKwh,profile.objective.targetOffset,profile.assumptions]);const fam=tariffFamily(profile.service.tariff);
 const patch=(p:Partial<typeof profile>)=>setProfile(x=>({...x,...p,updatedAt:new Date().toISOString()}));const updateConsumption=(i:number,key:keyof ConsumptionEntry,value:string)=>{const next=[...profile.consumption];next[i]={...next[i],[key]:key==='period'?value:Number(value)};patch({consumption:next,source:{...profile.source,kind:'manual',status:'manually entered'}})};
 const addMonth=()=>{if(profile.consumption.length>=24)return;const last=[...profile.consumption].sort((a,b)=>a.period.localeCompare(b.period)).at(-1)?.period||'2026-01';const [y,m]=last.split('-').map(Number);const d=new Date(y,m,1);patch({consumption:[...profile.consumption,{period:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,kwh:0}]})};
 const importCsv=()=>{const r=parseConsumptionCsv(csvText);setCsvErrors(r.errors);if(!r.errors.length)patch({consumption:r.consumption,demand:r.demand,powerFactor:r.powerFactor,source:{kind:'csv',status:'validated'}})};
 const upload=(f?:File)=>{if(!f)return;patch({source:{kind:'document',status:'pending manual extraction',fileName:f.name,mimeType:f.type,size:f.size,uploadedAt:new Date().toISOString()}})};
 const selectScenario=(id:'conservative'|'recommended'|'maximum')=>patch({selectedScenarioId:id});
 return <main className="page project-page r1-consumption"><div className="page-header"><div><span className="eyebrow">CFE CONSUMPTION & SIZING</span><h1>Energy baseline</h1><p>Normalize CFE history, verify data quality and establish a transparent PV design basis.</p></div><div className={`quality-badge ${quality.toLowerCase().replaceAll(' ','-')}`}><small>DATA QUALITY</small><b>{quality}</b><span>{issues.filter(i=>i.severity!=='info').length} flags</span></div></div><WorkflowStrip active="Consumption"/>
 <section className="r1-controlbar"><label>Tariff<select value={profile.service.tariff} onChange={e=>{const tariff=e.target.value as TariffCode;patch({service:{...profile.service,tariff,siteType:tariffFamily(tariff)==='residential'?'Residential':tariffFamily(tariff)==='demand'?'Industrial':'Commercial'},demand:requiresDemand(tariff)?profile.consumption.map(x=>({period:x.period,kw:profile.demand.find(d=>d.period===x.period)?.kw??0})):[],powerFactor:supportsPowerFactor(tariff)?profile.consumption.map(x=>({period:x.period,value:profile.powerFactor.find(p=>p.period===x.period)?.value??.95})):[]})}}>{tariffs.map(t=><option key={t}>{t}</option>)}</select></label><span><small>SERVICE FAMILY</small><b>{fam==='residential'?'Residential':fam==='demand'?'Demand-based C&I':'Commercial / low voltage'}</b></span><span><small>SOURCE</small><b>{profile.source.kind.toUpperCase()} · {profile.source.status}</b></span><nav><button className={tab==='manual'?'active':''} onClick={()=>setTab('manual')}>Monthly data</button><button className={tab==='csv'?'active':''} onClick={()=>setTab('csv')}>CSV import</button><button className={tab==='sizing'?'active':''} onClick={()=>setTab('sizing')}>Sizing</button></nav></section>
 <section className="r1-metrics"><span><small>ANNUAL ENERGY</small><b>{fmt(metrics.annualKwh)} kWh</b></span><span><small>AVG MONTH</small><b>{fmt(metrics.avgMonthlyKwh)} kWh</b></span><span><small>PEAK MONTH</small><b>{metrics.peakMonth?.period} · {fmt(metrics.peakMonth?.kwh||0)}</b></span><span><small>ANNUAL BILL</small><b>{metrics.annualAmount?`MX$ ${fmt(metrics.annualAmount)}`:'—'}</b></span><span><small>BLENDED RATE</small><b>{metrics.blendedRate?`$${fmt(metrics.blendedRate,2)}/kWh`:'—'}</b></span>{requiresDemand(profile.service.tariff)&&<span><small>PEAK DEMAND</small><b>{fmt(metrics.peakDemand||0,1)} kW</b></span>}</section>
 {tab==='manual'&&<div className="r1-main-grid"><section className="r1-entry"><header><div><small>12–24 MONTH PROFILE</small><h2>Billing periods</h2></div><button className="secondary" disabled={profile.consumption.length>=24} onClick={addMonth}><Plus size={14}/>Add month</button></header><div className="entry-head"><span>Period</span><span>kWh</span><span>Amount MXN</span>{requiresDemand(profile.service.tariff)&&<span>Demand kW</span>}{supportsPowerFactor(profile.service.tariff)&&<span>PF</span>}<span/></div><div className="entry-scroll">{profile.consumption.map((x,i)=><div className="entry-row" key={`${x.period}-${i}`}><input value={x.period} onChange={e=>updateConsumption(i,'period',e.target.value)}/><input type="number" value={x.kwh} onChange={e=>updateConsumption(i,'kwh',e.target.value)}/><input type="number" value={x.amountMxn??''} onChange={e=>updateConsumption(i,'amountMxn',e.target.value)}/>{requiresDemand(profile.service.tariff)&&<input type="number" value={profile.demand.find(d=>d.period===x.period)?.kw??''} onChange={e=>{const demand=profile.demand.filter(d=>d.period!==x.period);demand.push({period:x.period,kw:Number(e.target.value)});patch({demand})}}/>}{supportsPowerFactor(profile.service.tariff)&&<input type="number" step="0.01" value={profile.powerFactor.find(p=>p.period===x.period)?.value??''} onChange={e=>{const powerFactor=profile.powerFactor.filter(p=>p.period!==x.period);powerFactor.push({period:x.period,value:Number(e.target.value)});patch({powerFactor})}}/>}<button onClick={()=>patch({consumption:profile.consumption.filter((_,j)=>j!==i)})}><Trash2 size={13}/></button></div>)}</div></section><aside className="quality-panel"><header><small>DETERMINISTIC CHECKS</small><h2>Data Quality</h2></header>{issues.slice(0,8).map(i=><div className={`quality-item ${i.severity}`} key={`${i.code}-${i.period||''}`} >{i.severity==='error'?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>}<span><b>{i.code.replaceAll('_',' ')}</b><small>{i.message}</small></span></div>)}</aside></div>}
 {tab==='csv'&&<section className="csv-panel"><div><small>DOCUMENTED CSV TEMPLATE</small><h2>Import CFE history</h2><p>Required: period, kwh. Optional: amount_mxn, demand_kw, power_factor. Period format is YYYY-MM.</p><textarea value={csvText} onChange={e=>setCsvText(e.target.value)}/><div className="csv-actions"><button className="primary" onClick={importCsv}><Upload size={14}/>Validate & import</button><button className="secondary" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csvTemplate],{type:'text/csv'}));a.download='cfe-consumption-template.csv';a.click()}}><Download size={14}/>Download template</button></div></div><aside><small>IMPORT VALIDATION</small><h3>{csvErrors.length?`${csvErrors.length} issue(s)`:'Ready to validate'}</h3>{csvErrors.map(e=><p className="csv-error" key={e}>{e}</p>)}</aside></section>}
 {tab==='sizing'&&<Sizing profile={profile} metrics={metrics} scenarios={scenarios} patch={patch} selectScenario={selectScenario}/>}
 <section className="source-document"><div><FileText size={18}/><span><small>CFE SOURCE DOCUMENT</small><b>{profile.source.fileName||'No bill attached'}</b><em>{profile.source.fileName?`${profile.source.status} · ${Math.round((profile.source.size||0)/1024)} KB`:'PDF/image upload stores metadata only. No AI/OCR parsing in R1.'}</em></span></div><input ref={fileRef} hidden type="file" accept=".pdf,image/*" onChange={e=>upload(e.target.files?.[0])}/><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={14}/>{profile.source.fileName?'Replace':'Upload'} CFE bill</button>{profile.source.fileName&&<button className="secondary" onClick={()=>patch({source:{kind:'manual',status:'manually entered'}})}>Remove</button>}</section>
 <section className="r1-charts"><div><small>MONTHLY ENERGY</small><h2>kWh profile</h2><ResponsiveContainer width="100%" height={220}><BarChart data={profile.consumption}><CartesianGrid vertical={false}/><XAxis dataKey="period" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Bar dataKey="kwh" fill="#2f6f5f" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></div>{metrics.annualAmount&&<div><small>BILLED AMOUNT</small><h2>MXN trend</h2><ResponsiveContainer width="100%" height={220}><LineChart data={profile.consumption}><CartesianGrid vertical={false}/><XAxis dataKey="period" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Line type="monotone" dataKey="amountMxn" stroke="#5f6f75" strokeWidth={2}/></LineChart></ResponsiveContainer></div>}</section>
 </main>}
function Sizing({profile,metrics,scenarios,patch,selectScenario}:any){const offsets=[50,70,80,90,95,100];return <section className="sizing-workspace"><header><div><small>ENERGY-BALANCE SIZING</small><h2>PV sizing objectives</h2></div><div className="objective-row">{offsets.map(o=><button className={profile.objective.targetOffset===o?'active':''} onClick={()=>patch({objective:{kind:'offset',targetOffset:o,label:`${o}% offset`}})} key={o}>{o}%</button>)}<input type="number" min="1" max="150" value={profile.objective.targetOffset} onChange={e=>patch({objective:{kind:'offset',targetOffset:Number(e.target.value),label:'Custom offset'}})}/></div></header><div className="assumptions"><label>Panel wattage<input type="number" value={profile.assumptions.panelWattage} onChange={e=>patch({assumptions:{...profile.assumptions,panelWattage:Number(e.target.value)}})}/><small>W/module</small></label><label>Specific yield<input type="number" value={profile.assumptions.specificYield} onChange={e=>patch({assumptions:{...profile.assumptions,specificYield:Number(e.target.value)}})}/><small>kWh/kWp/yr</small></label><label>Loss factor<input type="number" step="0.01" value={profile.assumptions.lossFactor} onChange={e=>patch({assumptions:{...profile.assumptions,lossFactor:Number(e.target.value)}})}/><small>1.00 = embedded in yield</small></label><label>Design margin<input type="number" value={profile.assumptions.designMargin} onChange={e=>patch({assumptions:{...profile.assumptions,designMargin:Number(e.target.value)}})}/><small>%</small></label><div className="formula"><small>FORMULA</small><b>target kWh ÷ (specific yield × loss factor) = required DC kWp</b><span>Panel count always rounds upward after optional design margin.</span></div></div><div className="scenario-grid">{scenarios.map((s:any)=><article className={`scenario ${profile.selectedScenarioId===s.id?'selected':''}`} key={s.id}><header><span><small>{s.name.toUpperCase()}</small><h3>{s.targetOffset}% target</h3></span>{profile.selectedScenarioId===s.id&&<b>Current Design Basis</b>}</header><dl><div><dt>Modules</dt><dd>{s.panelCount} × {profile.assumptions.panelWattage} W</dd></div><div><dt>DC size</dt><dd>{s.dcKwp.toFixed(2)} kWp</dd></div><div><dt>Annual production</dt><dd>{fmt(s.annualProduction)} kWh</dd></div><div><dt>Achieved offset</dt><dd>{s.achievedOffset.toFixed(1)}%</dd></div><div><dt>Target delta</dt><dd>{s.deltaToTarget>=0?'+':''}{s.deltaToTarget.toFixed(1)}%</dd></div></dl><button className="secondary" onClick={()=>selectScenario(s.id)}>Select as design basis</button></article>)}</div><div className="sizing-note">R1 sizing is annual energy-balance only. “Maximize savings” is intentionally limited to energy offset until economics/hourly simulation milestones.</div></section>}
