import {useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {BarChart3,ChevronDown,ChevronUp,Columns3,Filter,ListTodo,Plus,Search,Settings2,Table2,TriangleAlert} from 'lucide-react';
import {project} from '../data';
import {deriveAcceptedProjectOutputs} from '../domain/acceptedProjectOutputs';
import {createDefaultSiteDesign} from '../domain/design/types';
import {useSiteDesign} from '../domain/design/store';
import {useElectricalDesign} from '../domain/electrical/store';
import {useEnergyProfile} from '../domain/energy/store';
import {useR4State} from '../domain/economics/store';
import {useProposalState} from '../domain/proposal/store';
import {projectSummary,filteredRows,valueOfOpportunity} from '../domain/crm/selectors';
import {salesMetrics,funnelMetrics} from '../domain/crm/metrics';
import {stageById,orderedStages} from '../domain/crm/pipeline';
import {moveOpportunity} from '../domain/crm/transitions';
import {useCrmState} from '../domain/crm/store';
import {isOverdue} from '../domain/crm/tasks';
import {auditEntry} from '../domain/crm/audit';
import type {CrmProjectSummary,Opportunity,OpportunityStageId,TaskStatus} from '../domain/crm/types';

const NOW=()=>new Date().toISOString();
const money=(n:number)=>`MX$${Math.round(n).toLocaleString()}`;
type SortKey='updated'|'value-desc'|'close'|'stale-desc';
type TaskBucket='all'|'overdue'|'today'|'upcoming'|'completed';

export function Crm(){
 const {state,setState}=useCrmState(),nav=useNavigate();
 const [message,setMessage]=useState(''),[sortKey,setSortKey]=useState<SortKey>('updated'),[taskBucket,setTaskBucket]=useState<TaskBucket>('all'),[taskOwner,setTaskOwner]=useState('');
 const {profile}=useEnergyProfile(),{design}=useSiteDesign(createDefaultSiteDesign()),{electrical}=useElectricalDesign(),{state:r4}=useR4State(),{proposal}=useProposalState(project.id);
 const truth=useMemo(()=>projectSummary(deriveAcceptedProjectOutputs(profile,design,electrical,r4),proposal),[profile,design,electrical,r4,proposal]);
 const summaries=useMemo(()=>new Map<string,CrmProjectSummary>([[project.id,truth]]),[truth]);
 const rawRows=useMemo(()=>filteredRows(state,summaries,NOW()),[state,summaries]);
 const rows=useMemo(()=>[...rawRows].sort((a,b)=>sortKey==='value-desc'?b.value-a.value:sortKey==='close'?(a.o.expectedCloseDate||'9999').localeCompare(b.o.expectedCloseDate||'9999'):sortKey==='stale-desc'?b.stale.daysSinceActivity-a.stale.daysSinceActivity:b.o.updatedAt.localeCompare(a.o.updatedAt)),[rawRows,sortKey]);
 const metrics=useMemo(()=>salesMetrics(state,o=>valueOfOpportunity(o,summaries),NOW()),[state,summaries]);
 const funnel=useMemo(()=>funnelMetrics(state,NOW()),[state]);
 const mode=state.viewPrefs.mode;
 const setPrefs=(p:Partial<typeof state.viewPrefs>)=>setState(s=>({...s,viewPrefs:{...s.viewPrefs,...p}}));
 const move=(o:Opportunity,to:OpportunityStageId)=>{const result=moveOpportunity(state,o.id,to,NOW(),'u-dg',o.projectId?summaries.get(o.projectId):undefined);if(!result.ok){setMessage(result.issues.map(i=>i.message).join(' '));return}setState(result.state);setMessage(`Stage moved to ${stageById(state.pipeline,to).label}.`)};
 const createLead=()=>{const n=state.opportunities.length+1,id=`opp-${n}`,aid=`acct-${n}`,cid=`contact-${n}`,at=NOW();setState(s=>({...s,accounts:[...s.accounts,{id:aid,displayName:`New solar lead ${n}`,type:'residential',notes:'',tags:[],projectIds:[]}],contacts:[...s.contacts,{id:cid,accountId:aid,name:`New contact ${n}`,role:'',phone:'',email:'',preferredChannel:'Phone',notes:'',primary:true}],opportunities:[...s.opportunities,{id,accountId:aid,primaryContactId:cid,name:`Solar opportunity ${n}`,stageId:'new',status:'open',ownerId:'u-dg',sourceId:'other',nextAction:'Qualify solar opportunity',nextActionDate:at.slice(0,10),notes:'',createdAt:at,updatedAt:at}],stageHistory:[...s.stageHistory,{id:`stage-${id}-new`,opportunityId:id,stageId:'new',enteredAt:at}],audit:[...s.audit,{id:`audit-${id}`,eventType:'opportunity-created',entityId:id,occurredAt:at,actorId:'u-dg',after:{stageId:'new'}}],updatedAt:at}));nav(`/crm/opportunities/${id}`)};
 const updateStageConfig=(id:OpportunityStageId,patch:{label?:string;probabilityPct?:number;staleAfterDays?:number})=>{const at=NOW();setState(s=>{const before=s.pipeline.stages.find(x=>x.id===id);return{...s,pipeline:{...s.pipeline,stages:s.pipeline.stages.map(x=>x.id===id?{...x,...patch}:x)},audit:[...s.audit,auditEntry('pipeline-config-changed',id,at,'u-dg',before,{...before,...patch})],updatedAt:at}})};
 const shiftStage=(id:OpportunityStageId,dir:-1|1)=>{const sorted=orderedStages(state.pipeline),i=sorted.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=sorted.length)return;const a=sorted[i],b=sorted[j];if(a.semantic==='terminal'||b.semantic==='terminal')return;const at=NOW();setState(s=>({...s,pipeline:{...s.pipeline,stages:s.pipeline.stages.map(x=>x.id===a.id?{...x,order:b.order}:x.id===b.id?{...x,order:a.order}:x)},audit:[...s.audit,auditEntry('pipeline-config-changed',state.pipeline.id,at,'u-dg',{order:sorted.map(x=>x.id)},{moved:id,direction:dir})],updatedAt:at}))};
 const today=NOW().slice(0,10);const visibleTasks=useMemo(()=>state.tasks.filter(t=>(!taskOwner||t.ownerId===taskOwner)&&(taskBucket==='all'||taskBucket==='completed'?taskBucket==='all'||t.status==='completed':t.status==='open'&&(taskBucket==='overdue'?isOverdue(t,NOW()):taskBucket==='today'?t.dueDate===today:taskBucket==='upcoming'?t.dueDate>today:false))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[state.tasks,taskOwner,taskBucket,today]);
 const completeTask=(id:string,status:TaskStatus)=>{const at=NOW();setState(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,status,completedAt:status==='completed'?at:undefined}:t),audit:[...s.audit,auditEntry('task-completed',id,at,'u-dg','open',status)],updatedAt:at}))};

 return <main className="page r6-page" data-testid="crm-page">
  <div className="r6-head"><div><span className="eyebrow">SOLAR OPERATIONS · R6</span><h1>Commercial pipeline</h1><p>Operate opportunities around real solar projects; engineering, production, economics and proposals remain read-through from R1–R5.</p></div><button className="primary" onClick={createLead}><Plus size={15}/>New solar opportunity</button></div>
  <section className="r6-health-strip"><div><small>OPEN OPPORTUNITIES</small><b>{metrics.openOpportunities}</b></div><div><small>PIPELINE VALUE</small><b>{money(metrics.pipelineValue)}</b></div><div><small>WEIGHTED PIPELINE</small><b>{money(metrics.weightedPipeline)}</b></div><div><small>OVERDUE TASKS</small><b>{metrics.overdueTasks}</b></div><div><small>WIN RATE</small><b>{metrics.winRatePct===null?'Insufficient data':`${metrics.winRatePct.toFixed(1)}%`}</b></div></section>
  <div className="r6-toolbar"><div className="r6-mode"><button className={mode==='table'?'active':''} onClick={()=>setPrefs({mode:'table'})}><Table2 size={14}/>Table</button><button className={mode==='board'?'active':''} onClick={()=>setPrefs({mode:'board'})}><Columns3 size={14}/>Board</button><button className={mode==='tasks'?'active':''} onClick={()=>setPrefs({mode:'tasks'})}><ListTodo size={14}/>Tasks</button><button className={mode==='analytics'?'active':''} onClick={()=>setPrefs({mode:'analytics'})}><BarChart3 size={14}/>Analytics</button></div><label className="r6-search"><Search size={14}/><input aria-label="Search opportunities" value={state.viewPrefs.search} onChange={e=>setPrefs({search:e.target.value})} placeholder="Search opportunity, account or project"/></label><select aria-label="Filter stage" value={state.viewPrefs.stageId||''} onChange={e=>setPrefs({stageId:(e.target.value||undefined) as OpportunityStageId|undefined})}><option value="">All stages</option>{orderedStages(state.pipeline).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select aria-label="Filter owner" value={state.viewPrefs.ownerId||''} onChange={e=>setPrefs({ownerId:e.target.value||undefined})}><option value="">All owners</option>{state.owners.filter(x=>x.active).map(o=><option key={o.id} value={o.id}>{o.displayName}</option>)}</select><select aria-label="Filter source" value={state.viewPrefs.sourceId||''} onChange={e=>setPrefs({sourceId:(e.target.value||undefined) as any})}><option value="">All sources</option>{state.sources.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select aria-label="Filter status" value={state.viewPrefs.status||'all'} onChange={e=>setPrefs({status:e.target.value as any})}><option value="all">Open + closed</option><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select><select aria-label="Filter proposal" value={state.viewPrefs.proposalFilter} onChange={e=>setPrefs({proposalFilter:e.target.value as any})}><option value="all">Any proposal</option><option value="sent">Proposal exported</option><option value="not-sent">Proposal not exported</option></select><select aria-label="Sort opportunities" value={sortKey} onChange={e=>setSortKey(e.target.value as SortKey)}><option value="updated">Last updated</option><option value="value-desc">Value high → low</option><option value="close">Expected close</option><option value="stale-desc">Stale days</option></select><label className="r6-check"><input type="checkbox" checked={state.viewPrefs.overdueOnly} onChange={e=>setPrefs({overdueOnly:e.target.checked})}/>Overdue</label><label className="r6-check"><input type="checkbox" checked={state.viewPrefs.staleOnly} onChange={e=>setPrefs({staleOnly:e.target.checked})}/>Stale</label></div>
  {message&&<div className="r6-message" role="status"><TriangleAlert size={15}/>{message}<button onClick={()=>setMessage('')}>Dismiss</button></div>}

  {mode==='table'&&<section className="crm-table-wrap" data-testid="crm-opportunities-table"><table className="crm-table"><thead><tr><th>Opportunity / account</th><th>Solar project</th><th>Stage</th><th>Owner / source</th><th>Project value</th><th>Proposal</th><th>Next action</th><th>Close</th><th>Stale</th><th>Readiness</th></tr></thead><tbody>{rows.map(r=><tr key={r.o.id}><td><Link to={`/crm/opportunities/${r.o.id}`}><b>{r.o.name}</b><span>{r.account?.displayName}</span></Link></td><td>{r.o.projectId?<Link to={`/projects/${r.o.projectId}`}>{r.o.projectId}<span>{r.summary?.installedDcKwp.toFixed(2)} kWp · {r.summary?.placedModules} modules</span></Link>:<span className="muted">Not linked yet</span>}</td><td><select aria-label={`Stage ${r.o.name}`} value={r.o.stageId} onChange={e=>move(r.o,e.target.value as OpportunityStageId)}>{orderedStages(state.pipeline).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></td><td><b>{r.owner?.displayName}</b><span>{state.sources.find(s=>s.id===r.o.sourceId)?.label}</span></td><td>{r.value?money(r.value):<span className="muted">Awaiting R4</span>}</td><td><b>{r.summary?.proposalStatus||'—'}</b><span>{r.summary?.proposalVersion?`v${r.summary.proposalVersion}`:'No version'}</span></td><td><b className={r.overdueCount?'danger-text':''}>{r.nextTask?.title||r.o.nextAction||'—'}</b><span>{r.nextTask?.dueDate||r.o.nextActionDate||''}{r.overdueCount?` · ${r.overdueCount} overdue`:''}</span></td><td>{r.o.expectedCloseDate||'—'}</td><td><b>{r.stale.daysSinceActivity}d</b><span>{r.stale.stale?'Needs attention':'Active'}</span></td><td>{r.summary?.blockers.some(b=>b.severity==='error')?<span className="status-label blocked">Blocked</span>:<span className="status-label ready">Ready / pre-project</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="r6-empty"><Filter size={20}/><b>No opportunities match the current filters.</b></div>}</section>}

  {mode==='board'&&<section className="pipeline-board" data-testid="crm-pipeline-board">{orderedStages(state.pipeline).filter(s=>!['won','lost'].includes(s.id)).map(stage=>{const cards=rows.filter(r=>r.o.stageId===stage.id);return <div className="pipeline-column" key={stage.id}><header><div><b>{stage.label}</b><span>{cards.length} opps</span></div><strong>{money(cards.reduce((sum,r)=>sum+r.value,0))}</strong></header><div className="pipeline-cards">{cards.map(r=><article key={r.o.id} className="pipeline-card"><Link to={`/crm/opportunities/${r.o.id}`}><b>{r.o.name}</b><span>{r.account?.displayName}</span></Link><div><strong>{r.value?money(r.value):'Awaiting R4'}</strong><span>{r.summary?`${r.summary.installedDcKwp.toFixed(1)} kWp`:'Lead stage'}</span></div><small>{r.nextTask?.title||r.o.nextAction||'No next action'}</small><label>Move stage<select aria-label={`Move ${r.o.name} stage`} value={r.o.stageId} onChange={e=>move(r.o,e.target.value as OpportunityStageId)}>{orderedStages(state.pipeline).filter(s=>!['won','lost'].includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label></article>)}</div></div>})}</section>}

  {mode==='tasks'&&<section className="crm-task-operations" data-testid="crm-task-operations"><header><div><small>PROJECT-CENTERED WORK QUEUE</small><h2>Tasks and next actions</h2><p>Local operating tasks linked to opportunities, projects, accounts and contacts.</p></div><div className="task-view-filters"><select aria-label="Task bucket" value={taskBucket} onChange={e=>setTaskBucket(e.target.value as TaskBucket)}><option value="all">All tasks</option><option value="overdue">Overdue</option><option value="today">Due today</option><option value="upcoming">Upcoming</option><option value="completed">Completed</option></select><select aria-label="Task owner" value={taskOwner} onChange={e=>setTaskOwner(e.target.value)}><option value="">All owners</option>{state.owners.map(o=><option key={o.id} value={o.id}>{o.displayName}</option>)}</select></div></header><table><thead><tr><th>Status</th><th>Task</th><th>Due</th><th>Owner</th><th>Priority</th><th>Solar project / opportunity</th></tr></thead><tbody>{visibleTasks.map(t=>{const o=t.link.opportunityId?state.opportunities.find(x=>x.id===t.link.opportunityId):undefined;return <tr key={t.id} className={isOverdue(t,NOW())?'overdue':''}><td><button aria-label={`${t.status==='completed'?'Reopen':'Complete'} ${t.title}`} onClick={()=>completeTask(t.id,t.status==='completed'?'open':'completed')}>{t.status==='completed'?'Completed':'Open'}</button></td><td><b>{t.title}</b><span>{t.category}</span></td><td>{t.dueDate}{isOverdue(t,NOW())&&<em> OVERDUE</em>}</td><td>{state.owners.find(x=>x.id===t.ownerId)?.displayName||t.ownerId}</td><td>{t.priority}</td><td>{t.link.projectId&&<Link to={`/projects/${t.link.projectId}`}>{t.link.projectId}</Link>}{o&&<Link to={`/crm/opportunities/${o.id}`}>{o.name}</Link>}</td></tr>})}</tbody></table>{!visibleTasks.length&&<div className="r6-empty"><ListTodo size={20}/><b>No tasks in this view.</b></div>}</section>}

  {mode==='analytics'&&<section className="crm-analytics" data-testid="crm-analytics"><div className="analytics-grid"><article><small>PIPELINE / OUTCOMES</small><dl><div><dt>Open value</dt><dd>{money(metrics.pipelineValue)}</dd></div><div><dt>Weighted value</dt><dd>{money(metrics.weightedPipeline)}</dd></div><div><dt>Won value</dt><dd>{money(metrics.wonValue)}</dd></div><div><dt>Lost value</dt><dd>{money(metrics.lostValue)}</dd></div><div><dt>Avg sales cycle</dt><dd>{metrics.averageSalesCycleDays===null?'Insufficient data':`${metrics.averageSalesCycleDays.toFixed(1)} days`}</dd></div><div><dt>Proposal → won</dt><dd>{metrics.proposalToWonPct===null?'Insufficient data':`${metrics.proposalToWonPct.toFixed(1)}%`}</dd></div></dl></article><article><small>LEAD SOURCE ATTRIBUTION</small><table><thead><tr><th>Source</th><th>Opps</th><th>Wins</th><th>Value</th></tr></thead><tbody>{state.sources.map(s=>{const x=metrics.bySource.get(s.id);return <tr key={s.id}><td>{s.label}</td><td>{x?.opportunities||0}</td><td>{x?.wins||0}</td><td>{money(x?.value||0)}</td></tr>})}</tbody></table></article></div><article className="funnel" data-testid="crm-funnel"><header><small>DETERMINISTIC FUNNEL · LOCAL STAGE HISTORY</small><span>Rates use recorded local stage entries; incomplete history is not cohort-perfect attribution.</span></header>{funnel.map(f=><div className="funnel-row" key={f.stageId}><b>{f.label}</b><div className="funnel-bar"><i style={{width:`${Math.max(8,Math.min(100,f.entered*15))}%`}}/></div><span>{f.entered} entered</span><span>{f.progressed} progressed</span><span>{f.conversionPct===null?'—':`${f.conversionPct.toFixed(0)}%`}</span><span>{f.averageDays===null?'—':`${f.averageDays.toFixed(1)}d avg`}</span></div>)}</article></section>}

  <details className="pipeline-settings" data-testid="crm-pipeline-settings"><summary><Settings2 size={14}/> Pipeline configuration</summary><p>Stable stage IDs remain fixed for deterministic lifecycle rules. Labels, probability assumptions, stale thresholds and non-terminal order are locally configurable.</p><div className="pipeline-config-grid">{orderedStages(state.pipeline).map((s,i)=><div key={s.id}><code>{s.id}</code><input aria-label={`Stage label ${s.id}`} value={s.label} onChange={e=>updateStageConfig(s.id,{label:e.target.value})}/><label>Probability %<input aria-label={`Stage probability ${s.id}`} type="number" min="0" max="100" value={s.probabilityPct} onChange={e=>updateStageConfig(s.id,{probabilityPct:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label><label>Stale after days<input aria-label={`Stage stale days ${s.id}`} type="number" min="1" value={s.staleAfterDays} onChange={e=>updateStageConfig(s.id,{staleAfterDays:Math.max(1,Number(e.target.value))})}/></label><button aria-label={`Move ${s.label} earlier`} disabled={i===0||s.semantic==='terminal'} onClick={()=>shiftStage(s.id,-1)}><ChevronUp size={14}/></button><button aria-label={`Move ${s.label} later`} disabled={i===state.pipeline.stages.length-1||s.semantic==='terminal'||orderedStages(state.pipeline)[i+1]?.semantic==='terminal'} onClick={()=>shiftStage(s.id,1)}><ChevronDown size={14}/></button></div>)}</div></details>
 </main>;
}
