import {AlertTriangle,CheckCircle2,Plus,Settings2} from 'lucide-react';
import {WorkflowStrip} from '../components/ProjectContext';
import {useEnergyProfile} from '../domain/energy/store';
import {createDefaultSiteDesign} from '../domain/design/types';
import {useSiteDesign} from '../domain/design/store';
import {useElectricalDesign} from '../domain/electrical/store';
import {moduleById,inverterById} from '../domain/electrical/catalog';
import {deriveProjectEconomics} from '../domain/economics/model';
import {lineQuantity,lineUnitCostMxn} from '../domain/economics/bom';
import {useR4State} from '../domain/economics/store';
import type {BomOverride,EquipmentCategory} from '../domain/economics/types';
const mx=(n:number)=>`MX$ ${Math.round(n).toLocaleString()}`;
const categoryLabel=(c:string)=>c.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase());
export function Equipment(){const {profile}=useEnergyProfile();const {design}=useSiteDesign(createDefaultSiteDesign());const {electrical}=useElectricalDesign();const {state,setState}=useR4State();const model=deriveProjectEconomics(profile,design,electrical,state);const module=moduleById(electrical.selectedModuleSpecId);const inverterModels=electrical.inverters.map(i=>inverterById(i.specId).model).join(', ');
const setOverride=(lineId:string,key:'quantity'|'unitCost',value:number)=>setState(s=>{const found=s.bomOverrides.find(o=>o.lineId===lineId);const next:BomOverride=found?{...found,[key]:value}:{lineId,[key]:value};return{...s,bomOverrides:[...s.bomOverrides.filter(o=>o.lineId!==lineId),next],updatedAt:new Date().toISOString()}});
const addManual=()=>setState(s=>({...s,manualBomLines:[...s.manualBomLines,{id:`manual-${Date.now()}`,description:'Manual project allowance',category:'misc-contingency' as EquipmentCategory,quantity:1,unit:'project',unitCost:1000,currency:'MXN',vatApplicable:true}],updatedAt:new Date().toISOString()}));
return <main className="page project-page r4-page" data-testid="r4-equipment"><div className="page-header"><div><span className="eyebrow">R4 · ENGINEERING → BOM → COST</span><h1>Equipment BOM</h1><p>Real project quantities from R2/R3 with editable commercial cost assumptions and explicit derivation states.</p></div><span className={`r4-ready ${model.readiness.toLowerCase().replace(' ','-')}`}>{model.readiness==='Ready'?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} Economics {model.readiness}</span></div><WorkflowStrip active="Equipment"/>
<section className="r4-basis-strip"><div><small>R2 PLACED MODULES</small><b>{model.placedModuleCount}</b><span>{module.model} · {module.pmaxW} W</span></div><div><small>R3 INVERTERS</small><b>{model.inverterCount}</b><span>{inverterModels||'None selected'}</span></div><div><small>INSTALLED DC</small><b>{model.installedDcKwp.toFixed(2)} kWp</b><span>authoritative engineering quantity</span></div><div><small>USD → MXN</small><label>Exchange rate<input aria-label="Exchange rate" type="number" step="0.1" value={state.costBasis.exchangeRateMxnPerUsd} onChange={e=>setState(s=>({...s,costBasis:{...s.costBasis,exchangeRateMxnPerUsd:+e.target.value}}))}/></label></div></section>
<section className="r4-panel equipment-bom-panel"><header><div><small>PROJECT BOM</small><h2>Design-derived + rule-derived + manual lines</h2></div><button className="secondary" onClick={addManual}><Plus size={14}/> Add manual line</button></header><div className="bom-table"><div className="bom-row bom-head"><span>Item / derivation</span><span>Category</span><span>Qty</span><span>Unit</span><span>Unit cost MXN</span><span>Subtotal</span></div>{model.bom.lines.map(line=>{const q=lineQuantity(line);const unitCost=lineUnitCostMxn(line,state.catalog,state.costBasis.exchangeRateMxnPerUsd);return <div className="bom-row" key={line.id} data-line={line.id}><span><b>{line.description}</b><em className={`derive ${line.derivation}`}>{line.derivation}</em><small>{line.derivationNote}</small></span><span>{categoryLabel(line.category)}</span><span><input aria-label={`Quantity ${line.description}`} type="number" step="0.01" value={q} onChange={e=>setOverride(line.id,'quantity',+e.target.value)}/></span><span>{line.unit}</span><span><input aria-label={`Cost ${line.description}`} type="number" step="1" value={Math.round(unitCost)} onChange={e=>setOverride(line.id,'unitCost',+e.target.value)}/></span><span><b>{mx(q*unitCost)}</b><small>{line.vatApplicable?'VAT applies':'No VAT'}</small></span></div>})}</div><footer className="bom-disclaimer"><Settings2 size={15}/><span><b>Allowance discipline:</b> DC/AC material, protections and cable quantities are planning allowances, not engineered takeoffs. Electrical substitutions remain locked to R3 and require engineering revalidation.</span></footer></section>
<div className="r4-cost-grid"><section className="r4-panel cost-breakdown"><header><div><small>COST BASIS</small><h2>Project cost stack</h2></div></header>{[['Equipment',model.costs.equipmentCost],['Materials',model.costs.materialsCost],['Installation labor',model.costs.laborCost],['Engineering/design',model.costs.engineeringCost],['Logistics',model.costs.logisticsCost],['Permits/interconnection',model.costs.permitsCost],['Contingency',model.costs.contingencyCost]].map(([l,v])=><div className="cost-line" key={l as string}><span>{l}</span><b>{mx(v as number)}</b></div>)}<div className="cost-line"><span>Direct project cost</span><b>{mx(model.costs.directProjectCost)}</b></div><div className="cost-line"><span>Overhead allocation</span><b>{mx(model.costs.overheadAllocation)}</b></div><div className="cost-line total"><span>Total cost before VAT</span><b>{mx(model.costs.totalCostBeforeVat)}</b></div><div className="cost-line"><span>Input VAT modeled</span><b>{mx(model.costs.inputVat)}</b></div></section><section className="r4-panel assumption-editor"><header><div><small>COMMERCIAL COST CONTROLS</small><h2>Overhead & VAT basis</h2></div></header><label>Overhead treatment<select aria-label="Overhead treatment" value={state.costBasis.overheadType} onChange={e=>setState(s=>({...s,costBasis:{...s.costBasis,overheadType:e.target.value as 'none'|'fixed'|'percent'}}))}><option value="none">None</option><option value="percent">% of direct cost</option><option value="fixed">Fixed MXN</option></select></label><label>Overhead value<input aria-label="Overhead value" type="number" value={state.costBasis.overheadValue} onChange={e=>setState(s=>({...s,costBasis:{...s.costBasis,overheadValue:+e.target.value}}))}/></label><label>VAT rate %<input aria-label="VAT rate" type="number" value={state.costBasis.vatRatePct} onChange={e=>setState(s=>({...s,costBasis:{...s.costBasis,vatRatePct:+e.target.value}}))}/></label><p>Default VAT is 16% and editable. Cost before VAT, input VAT and cash including VAT are kept separate.</p></section></div></main>}
