import {ArrowLeft,ArrowRight,Check,MapPin,Zap} from 'lucide-react';
import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {api,ApiError} from '../r7/api';
import {useAuth} from '../r7/auth';

const initial={id:`SOL-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,name:'Nuevo proyecto solar',customerName:'Nuevo cliente',location:'Mérida, Yucatán',serviceAddress:'Mérida, Yucatán',utility:'CFE',serviceType:'Residential',phase:'Three-phase',voltage:'220 V',tariff:'DAC',annualKwh:'21840',annualBillMxn:'66050',targetOffsetPct:'95'};

export function NewProject(){
 const [step,setStep]=useState(1),[form,setForm]=useState(initial),[status,setStatus]=useState<'idle'|'saving'|'error'>('idle'),[error,setError]=useState('');const nav=useNavigate(),{session}=useAuth();
 const field=(key:keyof typeof initial)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value});
 const create=async()=>{if(!session)return;setStatus('saving');setError('');try{await api.createProject(session.organizationId,{...form,annualKwh:Number(form.annualKwh),annualBillMxn:Number(form.annualBillMxn),targetOffsetPct:Number(form.targetOffsetPct)});nav('/projects')}catch(e){const apiError=e as ApiError;setStatus('error');setError(apiError.code==='CONFLICT'?'La referencia del proyecto ya existe.':'No fue posible crear el proyecto. Revisa los campos e inténtalo de nuevo.')}};
 return <main className="page new-project-page"><div className="backline"><Link to="/projects"><ArrowLeft size={14}/>Projects</Link><span>New solar project</span></div><div className="new-project-grid"><aside className="step-rail">{[['Project','Customer & project identity'],['Site','Electrical service & address'],['Energy','CFE baseline & target']].map((s,i)=><div className={`${step===i+1?'active':''} ${step>i+1?'done':''}`} key={s[0]}><i>{step>i+1?<Check size={12}/>:i+1}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></div>)}</aside><section className="setup-panel">
  {step===1&&<><header><small>STEP 1 / PROJECT</small><h1>Identify the solar project</h1><p>Create the project and customer context that engineering will use.</p></header><div className="field-grid"><label className="span2">Project name<input value={form.name} onChange={field('name')}/></label><label>Customer<input value={form.customerName} onChange={field('customerName')}/></label><label>Project reference<input value={form.id} onChange={field('id')}/></label></div></>}
  {step===2&&<><header><small>STEP 2 / SITE & SERVICE</small><h1>Define the electrical site</h1><p>Capture the location and service configuration before sizing.</p></header><div className="field-grid"><label className="span2">Service address<input value={form.serviceAddress} onChange={field('serviceAddress')}/></label><label>Location<input value={form.location} onChange={field('location')}/></label><label>Utility<input value={form.utility} onChange={field('utility')}/></label><label>Service type<select value={form.serviceType} onChange={field('serviceType')}><option>Residential</option><option>Commercial</option><option>Industrial</option></select></label><label>Phase<select value={form.phase} onChange={field('phase')}><option>Single-phase</option><option>Three-phase</option></select></label><label>Voltage<input value={form.voltage} onChange={field('voltage')}/></label></div><div className="site-locator"><MapPin size={18}/><span><b>{form.location}</b><small>Project location persisted with the active tenant</small></span></div></>}
  {step===3&&<><header><small>STEP 3 / CFE BASELINE</small><h1>Set the energy target</h1><p>Establish the baseline that will open the engineering workflow.</p></header><div className="field-grid"><label>CFE tariff<select value={form.tariff} onChange={field('tariff')}><option>DAC</option><option>PDBT</option><option>GDMTO</option><option>GDMTH</option></select></label><label>Annual consumption (kWh)<input type="number" min="1" value={form.annualKwh} onChange={field('annualKwh')}/></label><label>Annual CFE bill (MXN)<input type="number" min="0" value={form.annualBillMxn} onChange={field('annualBillMxn')}/></label><label>Target offset (%)<input type="number" min="0" max="100" value={form.targetOffsetPct} onChange={field('targetOffsetPct')}/></label></div><div className="engineering-ready"><Zap size={17}/><span><b>Baseline ready for consumption setup</b><small>The project and its initial R1 state will be stored in PostgreSQL.</small></span></div>{status==='error'&&<p role="alert">{error}</p>}</>}
  <footer><button className="secondary" onClick={()=>step===1?nav('/projects'):setStep(step-1)}>Back</button>{step<3?<button className="primary" onClick={()=>setStep(step+1)}>Continue <ArrowRight size={14}/></button>:<button className="primary" disabled={status==='saving'} onClick={create}>{status==='saving'?'Creating…':'Create project'} <ArrowRight size={14}/></button>}</footer>
 </section></div></main>;
}
