import { ArrowLeft, ArrowRight, Check, MapPin, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { project } from '../data';

export function NewProject(){
  const [step,setStep]=useState(1); const nav=useNavigate();
  return <main className="page new-project-page"><div className="backline"><Link to="/projects"><ArrowLeft size={14}/>Projects</Link><span>New solar project</span></div><div className="new-project-grid"><aside className="step-rail">{[['Project','Customer & project identity'],['Site','Electrical service & address'],['Energy','CFE baseline & target']].map((s,i)=><div className={`${step===i+1?'active':''} ${step>i+1?'done':''}`} key={s[0]}><i>{step>i+1?<Check size={12}/>:i+1}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></div>)}</aside><section className="setup-panel">
    {step===1&&<><header><small>STEP 1 / PROJECT</small><h1>Identify the solar project</h1><p>Create the project and customer context that engineering will use.</p></header><div className="field-grid"><label className="span2">Project name<input defaultValue={project.name}/></label><label>Customer<input defaultValue={project.customer}/></label><label>Project reference<input defaultValue={project.id}/></label></div></>}
    {step===2&&<><header><small>STEP 2 / SITE & SERVICE</small><h1>Define the electrical site</h1><p>Capture the location and service configuration before sizing.</p></header><div className="field-grid"><label className="span2">Service address<input defaultValue={project.address}/></label><label>Utility<input defaultValue="CFE"/></label><label>Service type<select defaultValue="Residential"><option>Residential</option><option>Commercial</option><option>Industrial</option></select></label><label>Phase<select defaultValue="Three-phase"><option>Single-phase</option><option>Three-phase</option></select></label><label>Voltage<input defaultValue="220 V"/></label></div><div className="site-locator"><MapPin size={18}/><span><b>Mérida, Yucatán</b><small>20.9849, -89.6186 · Site location mock</small></span></div></>}
    {step===3&&<><header><small>STEP 3 / CFE BASELINE</small><h1>Set the energy target</h1><p>Establish the baseline that will open the engineering workflow.</p></header><div className="field-grid"><label>CFE tariff<select defaultValue="DAC"><option>DAC</option><option>PDBT</option><option>GDMTO</option><option>GDMTH</option></select></label><label>Annual consumption<input defaultValue="21,840 kWh"/></label><label>Annual CFE bill<input defaultValue="$66,050 MXN"/></label><label>Target offset<input defaultValue="95%"/></label></div><div className="engineering-ready"><Zap size={17}/><span><b>Baseline ready for consumption setup</b><small>The next screen starts the solar engineering workflow with monthly CFE data.</small></span></div></>}
    <footer><button className="secondary" onClick={()=>step===1?nav('/projects'):setStep(step-1)}>Back</button>{step<3?<button className="primary" onClick={()=>setStep(step+1)}>Continue <ArrowRight size={14}/></button>:<button className="primary" onClick={()=>nav(`/projects/${project.id}/consumption`)}>Open consumption setup <ArrowRight size={14}/></button>}</footer>
  </section></div></main>;
}
