import {ArrowRight,CheckCircle2,MapPin,Zap} from 'lucide-react';
import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {WorkflowStrip} from '../components/ProjectContext';
import {project} from '../data';
import {api} from '../r7/api';
import {useAuth} from '../r7/auth';
import {Workspace} from './Workspace';

const mx=(n:number)=>`MX$ ${Math.round(n).toLocaleString()}`;
export function ProjectWorkspace(){const {id}=useParams();return id&&id!==project.id?<DraftWorkspace projectId={id}/>:<Workspace/>}
function DraftWorkspace({projectId}:{projectId:string}){const {session}=useAuth(),[record,setRecord]=useState<any>(null),[state,setState]=useState<any>(null),[failed,setFailed]=useState(false);useEffect(()=>{let active=true;if(!session)return;Promise.all([api.projects(session.organizationId),api.projectState(session.organizationId,projectId)]).then(([rows,next])=>{if(active){setRecord(rows.find((row:any)=>row.id===projectId)||null);setState(next)}}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[session?.organizationId,projectId]);if(failed)return <main className="r7-state"><h1>Project unavailable</h1><p>The persisted project workspace could not be loaded.</p></main>;if(!record||!state)return <main className="r7-state"><div className="r7-spinner"/><p>Loading project workspace…</p></main>;const r1=state.r1||{};return <main className="page project-page r4-page"><div className="workspace-head"><div><span className="eyebrow">SOLAR PROJECT COCKPIT · R1 · {projectId}</span><h1>{record.name}</h1><p><MapPin size={13}/>{r1.serviceAddress||record.location} · {r1.utility||'CFE'} {r1.tariff||'—'} · {r1.serviceType||'—'}</p></div><div className="workspace-actions"><Link className="secondary" to="/crm">Solar CRM</Link><Link className="primary" to={`/projects/${projectId}/consumption`}>Continue R1 <ArrowRight size={14}/></Link></div></div><WorkflowStrip active="Consumption"/><section className="cockpit-summary r4-cockpit"><div><small>ANNUAL CONSUMPTION</small><b>{Number(r1.annualKwh||0).toLocaleString()} <em>kWh</em></b><span>persisted R1 baseline</span></div><div><small>ANNUAL CFE BILL</small><b className="small-value">{mx(Number(r1.annualBillMxn||0))}</b><span>{r1.tariff||'—'} tariff</span></div><div><small>TARGET OFFSET</small><b>{Number(r1.targetOffsetPct||0)} <em>%</em></b><span>engineering target</span></div><div><small>STATUS</small><b className="small-value">{r1.quality||'Draft'}</b><span>ready to continue R1–R7</span></div></section><section className="engineering-panel"><header><div><small>POSTGRESQL PROJECT WORKSPACE</small><h2>Project created and ready for consumption setup</h2></div><CheckCircle2 size={20}/></header><div className="engineering-checklist"><span className="done"><CheckCircle2 size={16}/><b>Project identity</b><small>{record.customerName} · {record.location}</small></span><span className="done"><CheckCircle2 size={16}/><b>Electrical service</b><small>{r1.phase} · {r1.voltage} · {r1.utility}</small></span><span className="active"><Zap size={16}/><b>R1 consumption</b><small>Continue with monthly CFE data before R2 sizing</small></span></div><Link className="next-action" to={`/projects/${projectId}/consumption`}>Open consumption setup <ArrowRight size={15}/></Link></section></main>}
