import {ArrowDown,ArrowUp,CheckCircle2,Download,Eye,FilePlus2,History,ImagePlus,LockKeyhole,Save,Settings2,TriangleAlert,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {WorkflowStrip} from '../components/ProjectContext';
import {ProposalDocument} from '../components/ProposalDocument';
import {project} from '../data';
import {deriveAcceptedProjectOutputs} from '../domain/acceptedProjectOutputs';
import {createDefaultSiteDesign} from '../domain/design/types';
import {useSiteDesign} from '../domain/design/store';
import {useElectricalDesign} from '../domain/electrical/store';
import {useEnergyProfile} from '../domain/energy/store';
import {useR4State} from '../domain/economics/store';
import {buildProposalDocumentModel} from '../domain/proposal/document';
import {proposalSourceFingerprint} from '../domain/proposal/fingerprint';
import {downloadProposalPdf} from '../domain/proposal/pdf';
import {buildProposalSnapshot} from '../domain/proposal/snapshot';
import {useProposalState} from '../domain/proposal/store';
import type {ProposalSectionKey,ProposalVersion} from '../domain/proposal/types';
import {proposalReadiness,validateProposal} from '../domain/proposal/validation';
import {createNextVersion,createProposal,recordProposalExport,setVersionStatus,updateActiveDraft} from '../domain/proposal/versioning';

const sectionCopy:Partial<Record<ProposalSectionKey,ProposalVersion['contentBlocks'][number]['key']>>={'executive-summary':'executive-summary','assumptions':'assumptions','scope':'scope','exclusions':'exclusions','warranties':'warranties','next-steps':'next-steps','disclaimers':'disclaimer'};
export function Proposal(){
 const {profile}=useEnergyProfile(),{design}=useSiteDesign(createDefaultSiteDesign()),{electrical}=useElectricalDesign(),{state:r4}=useR4State();
 const outputs=useMemo(()=>deriveAcceptedProjectOutputs(profile,design,electrical,r4),[profile,design,electrical,r4]);
 const fingerprint=useMemo(()=>proposalSourceFingerprint(outputs),[outputs]);
 const snapshot=useMemo(()=>buildProposalSnapshot(outputs),[outputs]);
 const {proposal,setProposal}=useProposalState(project.id);const [preview,setPreview]=useState(false),[selectedSection,setSelectedSection]=useState<ProposalSectionKey>('cover'),[notice,setNotice]=useState('');
 useEffect(()=>{if(!proposal)setProposal(createProposal(project.id,snapshot,fingerprint));},[proposal,setProposal,snapshot,fingerprint]);
 const active=proposal?.versions.find(v=>v.id===proposal.activeVersionId)||proposal?.versions.at(-1);const issues=active?validateProposal(active,fingerprint,outputs):[];const readiness=proposalReadiness(issues);const outdated=!!active&&active.sourceFingerprint!==fingerprint;const frozen=!!active?.frozen;const model=active?buildProposalDocumentModel(active):null;
 const mutate=(fn:(v:ProposalVersion)=>ProposalVersion)=>{if(!proposal)return;const next=updateActiveDraft(proposal,fn);if(next===proposal&&frozen){setNotice('This exported proposal is frozen. Create a new version to edit.');return;}setProposal(next);};
 const changeSection=(key:ProposalSectionKey,patch:Partial<ProposalVersion['sections'][number]>)=>mutate(v=>({...v,sections:v.sections.map(s=>s.key===key?{...s,...patch}:s)}));
 const moveSection=(key:ProposalSectionKey,dir:-1|1)=>mutate(v=>{const ordered=[...v.sections].sort((a,b)=>a.order-b.order),i=ordered.findIndex(x=>x.key===key),j=i+dir;if(i<0||j<0||j>=ordered.length)return v;const a=ordered[i],b=ordered[j];if(a.required&&['cover'].includes(a.key))return v;const ao=a.order;a.order=b.order;b.order=ao;return{...v,sections:ordered};});
 const updateValidity=(days:number)=>mutate(v=>{const d=new Date(`${v.customer.proposalDate}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+Math.max(1,days));return{...v,validity:{validityDays:Math.max(1,days),validUntil:d.toISOString().slice(0,10)}};});
 const markReady=()=>{if(!proposal||!active||issues.some(x=>x.severity==='error'))return;setProposal(setVersionStatus(proposal,active.id,'Ready'));setNotice('Proposal marked Ready.');};
 const newVersion=()=>{if(!proposal)return;setProposal(createNextVersion(proposal,snapshot,fingerprint));setNotice(`Created proposal v${Math.max(...proposal.versions.map(x=>x.versionNumber))+1} from current R1–R4 state.`);setPreview(false);};
 const exportPdf=async()=>{if(!proposal||!active||!model||issues.some(x=>x.severity==='error'))return;try{const r=await downloadProposalPdf(model);const meta={...r,exportedAt:new Date().toISOString(),status:'success' as const};setProposal(recordProposalExport(proposal,active.id,meta));setNotice(`Exported ${r.filename} · ${(r.sizeBytes/1024).toFixed(1)} KB · ${r.pageCount} pages`);}catch(e){const meta={filename:`proposal-${project.id}-v${active.versionNumber}.pdf`,exportedAt:new Date().toISOString(),sizeBytes:0,pageCount:0,mimeType:'application/pdf' as const,status:'failed' as const,error:e instanceof Error?e.message:String(e)};setProposal(recordProposalExport(proposal,active.id,meta));setNotice(`PDF export failed: ${meta.error}`);}};
 if(!active||!model)return <main className="page project-page"><p>Preparing proposal workspace…</p></main>;
 if(preview)return <main className="r5-customer-preview" data-testid="customer-preview"><button className="preview-exit" onClick={()=>setPreview(false)}><X size={15}/>Exit preview</button><ProposalDocument model={model}/></main>;
 const selected=active.sections.find(x=>x.key===selectedSection)||active.sections[0],copyKey=sectionCopy[selectedSection],copyBlock=copyKey?active.contentBlocks.find(x=>x.key===copyKey):undefined;
 return <main className="page project-page r5-page"><div className="r5-topbar"><div><span className="eyebrow">CUSTOMER DOCUMENT · R5</span><h1>Proposal Builder</h1><p>Versioned customer document generated from accepted R1–R4 project truth.</p></div><div className="r5-version-actions"><select aria-label="Proposal version" value={active.id} onChange={e=>setProposal(p=>p?{...p,activeVersionId:e.target.value}:p)}>{proposal?.versions.map(v=><option value={v.id} key={v.id}>v{v.versionNumber} · {v.status}{v.frozen?' · frozen':''}</option>)}</select><span className={`proposal-status ${active.status.toLowerCase()}`}>{frozen&&<LockKeyhole size={12}/>} {active.status}</span><button className="secondary" onClick={()=>setNotice('Draft settings are persisted locally as you edit.')}><Save size={14}/>Save</button><button className="secondary" onClick={()=>setPreview(true)}><Eye size={14}/>Customer preview</button><button className="secondary" onClick={newVersion}><FilePlus2 size={14}/>New version</button><button className="primary" onClick={exportPdf} disabled={issues.some(x=>x.severity==='error')}><Download size={14}/>Export PDF</button></div></div><WorkflowStrip active="Proposal"/>
 {(outdated||notice)&&<div className={`r5-banner ${outdated?'warning':'info'}`}>{outdated?<><TriangleAlert size={16}/><b>Source changed · Proposal out of date.</b><span>The active snapshot is unchanged. Create a new version to capture the current R1–R4 state.</span></>:<><CheckCircle2 size={16}/><span>{notice}</span></>}<button onClick={()=>setNotice('')} aria-label="Dismiss notice"><X size={14}/></button></div>}
 <div className="proposal-builder-grid"><aside className="proposal-section-nav" data-testid="proposal-section-nav"><header><small>DOCUMENT</small><b>Sections</b><span>{active.sections.filter(x=>x.visible).length} visible</span></header><div className="section-list">{[...active.sections].sort((a,b)=>a.order-b.order).map((s,i)=><button key={s.key} className={selectedSection===s.key?'active':''} onClick={()=>setSelectedSection(s.key)}><i>{String(i+1).padStart(2,'0')}</i><span>{s.title}</span><input aria-label={`Show ${s.title}`} type="checkbox" checked={s.visible} disabled={s.required||frozen} onClick={e=>e.stopPropagation()} onChange={e=>changeSection(s.key,{visible:e.target.checked})}/></button>)}</div><div className="version-history"><small><History size={13}/>VERSION HISTORY</small>{[...(proposal?.versions||[])].reverse().map(v=><button key={v.id} onClick={()=>setProposal(p=>p?{...p,activeVersionId:v.id}:p)}><b>v{v.versionNumber}</b><span>{v.status}</span><em>{new Date(v.createdAt).toLocaleDateString()}</em></button>)}</div></aside>
 <section className="proposal-live-canvas" data-testid="proposal-live-preview"><div className="preview-ruler"><span>A4 · CUSTOMER PREVIEW</span><span>Snapshot {active.snapshot.capturedAt.slice(0,10)} · source {active.sourceFingerprint}</span></div><ProposalDocument model={model}/></section>
 <aside className="proposal-inspector"><header><Settings2 size={15}/><div><small>SELECTED SECTION</small><b>{selected.title}</b></div></header>{frozen&&<div className="frozen-note"><LockKeyhole size={14}/>Exported version is immutable. Create a new version to edit.</div>}<div className="inspector-actions"><button onClick={()=>moveSection(selected.key,-1)} disabled={frozen||selected.key==='cover'}><ArrowUp size={14}/>Move up</button><button onClick={()=>moveSection(selected.key,1)} disabled={frozen||selected.key==='cover'}><ArrowDown size={14}/>Move down</button></div>{copyBlock&&<label>Section copy<textarea aria-label={`${selected.title} copy`} rows={8} value={copyBlock.body} disabled={frozen} onChange={e=>mutate(v=>({...v,contentBlocks:v.contentBlocks.map(b=>b.id===copyBlock.id?{...b,body:e.target.value,templateContent:false}:b)}))}/></label>}
 <details open={selectedSection==='cover'}><summary>Customer & project</summary><label>Customer / company<input aria-label="Customer name" value={active.customer.customerName} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,customerName:e.target.value}}))}/></label><label>Contact name<input aria-label="Contact name" value={active.customer.contactName} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,contactName:e.target.value}}))}/></label><label>Project/site name<input aria-label="Project name" value={active.customer.projectName} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,projectName:e.target.value}}))}/></label><label>Site address<textarea aria-label="Site address" rows={2} value={active.customer.siteAddress} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,siteAddress:e.target.value}}))}/></label><div className="two-inputs"><label>Proposal date<input type="date" aria-label="Proposal date" value={active.customer.proposalDate} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,proposalDate:e.target.value}}))}/></label><label>Validity days<input type="number" min="1" aria-label="Validity days" value={active.validity.validityDays} disabled={frozen} onChange={e=>updateValidity(Number(e.target.value))}/></label></div><label>Advisor name<input aria-label="Advisor name" value={active.customer.advisorName} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,advisorName:e.target.value}}))}/></label><label>Advisor contact<input aria-label="Advisor contact" value={active.customer.advisorContact} disabled={frozen} onChange={e=>mutate(v=>({...v,customer:{...v.customer,advisorContact:e.target.value}}))}/></label></details>
 <details open={selectedSection==='cover'} data-testid="branding-settings"><summary>Branding</summary><label>Company display name<input aria-label="Company display name" value={active.branding.companyDisplayName} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,companyDisplayName:e.target.value}}))}/></label><div className="two-inputs"><label>Primary<input aria-label="Primary color" type="color" value={active.branding.primaryColor} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,primaryColor:e.target.value}}))}/></label><label>Accent<input aria-label="Accent color" type="color" value={active.branding.accentColor} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,accentColor:e.target.value}}))}/></label></div><label className="logo-upload"><ImagePlus size={15}/>Logo<input aria-label="Logo upload" type="file" accept="image/png,image/jpeg,image/webp" disabled={frozen} onChange={e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>mutate(v=>({...v,branding:{...v.branding,logoDataUrl:String(reader.result)}}));reader.readAsDataURL(f);}}/></label><label>Cover tagline<input aria-label="Cover tagline" value={active.branding.coverTagline} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,coverTagline:e.target.value}}))}/></label><label>Footer text<input aria-label="Footer text" value={active.branding.footerText} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,footerText:e.target.value}}))}/></label><label>Website<input aria-label="Website" value={active.branding.website} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,website:e.target.value}}))}/></label><label>Phone<input aria-label="Phone" value={active.branding.phone} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,phone:e.target.value}}))}/></label><label>Email<input aria-label="Email" value={active.branding.email} disabled={frozen} onChange={e=>mutate(v=>({...v,branding:{...v.branding,email:e.target.value}}))}/></label></details>
 <details open={selectedSection==='terms'}><summary>Commercial terms</summary><label>Payment terms<textarea aria-label="Payment terms" rows={3} value={active.commercialTerms.paymentTerms} disabled={frozen} onChange={e=>mutate(v=>({...v,commercialTerms:{...v.commercialTerms,paymentTerms:e.target.value}}))}/></label><label>Schedule / lead time<textarea aria-label="Schedule text" rows={3} value={active.commercialTerms.scheduleText} disabled={frozen} onChange={e=>mutate(v=>({...v,commercialTerms:{...v.commercialTerms,scheduleText:e.target.value}}))}/></label><label>Customer responsibilities<textarea aria-label="Customer responsibilities" rows={3} value={active.commercialTerms.customerResponsibilities} disabled={frozen} onChange={e=>mutate(v=>({...v,commercialTerms:{...v.commercialTerms,customerResponsibilities:e.target.value}}))}/></label><label>Utility caveat<textarea aria-label="Utility caveat" rows={3} value={active.commercialTerms.utilityCaveat} disabled={frozen} onChange={e=>mutate(v=>({...v,commercialTerms:{...v.commercialTerms,utilityCaveat:e.target.value}}))}/></label></details>
 <details open><summary>Readiness</summary><div className={`readiness-chip ${readiness.toLowerCase().replace(' ','-')}`}>{readiness}</div><div className="proposal-issues">{issues.length?issues.map(i=><div key={i.id} className={i.severity}><b>{i.severity}</b><span>{i.message}</span></div>):<p>No validation issues.</p>}</div><button className="primary wide" onClick={markReady} disabled={frozen||issues.some(x=>x.severity==='error')}><CheckCircle2 size={14}/>Mark Ready</button></details>
 </aside></div></main>;
}
