import {ArrowRight,CheckCircle2,MapPin,PanelTop,Zap} from 'lucide-react';
import {Link} from 'react-router-dom';
import {WorkflowStrip} from '../components/ProjectContext';
import {project} from '../data';
import {deriveEnergyMetrics} from '../domain/energy/metrics';
import {generateSizingScenarios} from '../domain/energy/sizing';
import {useEnergyProfile} from '../domain/energy/store';
import {dataQualityStatus,validateEnergyProfile} from '../domain/energy/validation';

export function Workspace(){const {profile}=useEnergyProfile();const metrics=deriveEnergyMetrics(profile);const issues=validateEnergyProfile(profile);const quality=dataQualityStatus(issues);const scenarios=generateSizingScenarios(metrics.annualKwh,profile.objective.targetOffset,profile.assumptions);const selected=scenarios.find(s=>s.id===profile.selectedScenarioId);const complete=quality==='Ready for sizing'&&!!selected;
 return <main className="page project-page"><div className="workspace-head"><div><span className="eyebrow">SOLAR PROJECT COCKPIT · R1</span><h1>{project.name}</h1><p><MapPin size={13}/>{project.address} · CFE {profile.service.tariff} · {profile.service.siteType}</p></div><Link className="primary" to={`/projects/${project.id}/design`}>Open design <ArrowRight size={14}/></Link></div><WorkflowStrip active={complete?'Design':'Consumption'}/>
 <section className="cockpit-summary"><div><small>ANNUAL CONSUMPTION</small><b>{(metrics.annualKwh/1000).toFixed(2)} <em>MWh</em></b><span>CFE normalized profile</span></div><div><small>DATA QUALITY</small><b className="small-value">{quality}</b><span>{profile.consumption.length} billing periods</span></div><div><small>DESIGN BASIS</small><b>{selected?selected.panelCount:'—'} <em>modules</em></b><span>{selected?`${profile.assumptions.panelWattage} W each`:'Select sizing scenario'}</span></div><div><small>TARGET DC</small><b>{selected?selected.dcKwp.toFixed(2):'—'} <em>kWp</em></b><span>{selected?`${selected.targetOffset}% target offset`:'Awaiting sizing'}</span></div><div><small>EXPECTED PRODUCTION</small><b>{selected?(selected.annualProduction/1000).toFixed(2):'—'} <em>MWh</em></b><span>{selected?`${selected.achievedOffset.toFixed(1)}% achieved offset`:'—'}</span></div></section>
 <div className="cockpit-grid"><section className="engineering-panel"><header><div><small>CURRENT ENGINEERING STATE</small><h2>{complete?'Consumption basis ready for Design':'Consumption needs engineering review'}</h2></div><PanelTop size={20}/></header><div className="engineering-checklist"><span className={quality==='Ready for sizing'?'done':'active'}>{quality==='Ready for sizing'?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>CFE consumption</b><small>{profile.service.tariff} · {metrics.annualKwh.toLocaleString()} kWh · {quality}</small></span><span className={selected?'done':'active'}>{selected?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>Sizing basis</b><small>{selected?`${selected.name}: ${selected.panelCount} panels · ${selected.dcKwp.toFixed(2)} kWp`:'Select one scenario in Consumption'}</small></span><span className={complete?'active':''}><i/> <b>Solar design</b><small>{complete?'Design receives target basis; roof scene remains R0.1 illustrative':'Blocked until consumption basis is ready'}</small></span><span><i/> <b>Equipment / Economics</b><small>Remain outside R1 calculation scope</small></span></div><Link className="next-action" to={`/projects/${project.id}/${complete?'design':'consumption'}`}>{complete?'Continue to Solar Designer':'Resolve consumption'} <ArrowRight size={15}/></Link></section>
 <section className="technical-panel"><header><small>R1 ENERGY BASIS</small><h2>Current project assumptions</h2></header><dl><div><dt>CFE tariff</dt><dd>{profile.service.tariff}</dd></div><div><dt>Consumption source</dt><dd>{profile.source.kind} · {profile.source.status}</dd></div><div><dt>Target offset</dt><dd>{profile.objective.targetOffset}%</dd></div><div><dt>Panel assumption</dt><dd>{profile.assumptions.panelWattage} W</dd></div><div><dt>Specific yield</dt><dd>{profile.assumptions.specificYield} kWh/kWp/yr</dd></div><div><dt>Design basis</dt><dd>{selected?`${selected.panelCount} modules / ${selected.dcKwp.toFixed(2)} kWp`:'Not selected'}</dd></div></dl></section></div></main>}
