import {ArrowRight,CheckCircle2,FileText,MapPin,PanelTop,ReceiptText,TrendingUp,Zap} from 'lucide-react';
import {Link} from 'react-router-dom';
import {WorkflowStrip} from '../components/ProjectContext';
import {project} from '../data';
import {deriveAcceptedProjectOutputs} from '../domain/acceptedProjectOutputs';
import {deriveEnergyMetrics} from '../domain/energy/metrics';
import {useEnergyProfile} from '../domain/energy/store';
import {dataQualityStatus,validateEnergyProfile} from '../domain/energy/validation';
import {createDefaultSiteDesign} from '../domain/design/types';
import {useSiteDesign} from '../domain/design/store';
import {INVERTER_CATALOG,moduleById} from '../domain/electrical/catalog';
import {dcAcRatio,installedDcKwp,inverterAcKw} from '../domain/electrical/calculations';
import {annualProductionSummary,monthlyProduction} from '../domain/electrical/production';
import {useElectricalDesign} from '../domain/electrical/store';
import {electricalState,validateElectricalDesign} from '../domain/electrical/validation';
import {useR4State} from '../domain/economics/store';
import {deriveProjectEconomics} from '../domain/economics/model';
import {proposalSourceFingerprint} from '../domain/proposal/fingerprint';
import {useProposalState} from '../domain/proposal/store';
const mx=(n:number)=>`MX$ ${Math.round(n).toLocaleString()}`;
export function Workspace(){const {profile}=useEnergyProfile();const {design}=useSiteDesign(createDefaultSiteDesign());const {electrical}=useElectricalDesign();const {state}=useR4State();const {proposal}=useProposalState(project.id);const metrics=deriveEnergyMetrics(profile);const quality=dataQualityStatus(validateEnergyProfile(profile));const module=moduleById(electrical.selectedModuleSpecId),placedIds=design.layout.placements.map(m=>m.id),dc=installedDcKwp(placedIds.length,module),ac=inverterAcKw(electrical,INVERTER_CATALOG),ratio=dcAcRatio(dc,ac);const eIssues=validateElectricalDesign(electrical,module,placedIds,design.panelWattage),eState=electricalState(eIssues),assigned=new Set(electrical.strings.flatMap(s=>s.moduleIds)).size;const monthly=monthlyProduction(dc,electrical.resource,electrical.assumptions,profile.consumption.slice(-12).map(x=>x.kwh)),prod=annualProductionSummary(dc,monthly,electrical.assumptions);const econ=deriveProjectEconomics(profile,design,electrical,state);const engineeringComplete=design.roofs.length>0&&placedIds.length>0&&!eIssues.some(i=>i.severity==='error');const economicsComplete=econ.readiness==='Ready';const accepted=deriveAcceptedProjectOutputs(profile,design,electrical,state);const currentFingerprint=proposalSourceFingerprint(accepted);const activeProposal=proposal?.versions.find(v=>v.id===proposal.activeVersionId);const proposalOutdated=!!activeProposal&&activeProposal.sourceFingerprint!==currentFingerprint;const proposalState=!activeProposal?'Not started':proposalOutdated?'Out of date':activeProposal.status;
return <main className="page project-page r4-page"><div className="workspace-head"><div><span className="eyebrow">SOLAR PROJECT COCKPIT · R5</span><h1>{project.name}</h1><p><MapPin size={13}/>{project.address} · CFE {profile.service.tariff} · {profile.service.siteType}</p></div><div className="workspace-actions"><Link className="secondary" to={`/projects/${project.id}/equipment`}>BOM <ReceiptText size={14}/></Link><Link className="secondary" to={`/projects/${project.id}/economics`}>Economics <TrendingUp size={14}/></Link><Link className="primary" to={`/projects/${project.id}/proposal`}>Proposal <FileText size={14}/></Link></div></div><WorkflowStrip active="Proposal"/>
<section className="cockpit-summary r4-cockpit"><div><small>PLACED DC</small><b>{dc.toFixed(2)} <em>kWp</em></b><span>{placedIds.length} × {module.pmaxW} W</span></div><div><small>ANNUAL PRODUCTION</small><b>{(prod.annualProductionKwh/1000).toFixed(2)} <em>MWh</em></b><span>R3 planning estimate</span></div><div><small>SELL PRICE PRE-VAT</small><b className="small-value">{mx(econ.pricing.sellPriceBeforeVat)}</b><span>customer total {mx(econ.pricing.customerTotal)}</span></div><div><small>YEAR-1 AVOIDED COST</small><b className="small-value">{mx(econ.solarValue.year1AvoidedElectricityCostMxn)}</b><span>{Math.round(econ.solarValue.annualAvoidedEnergyKwh).toLocaleString()} kWh valued</span></div><div><small>SIMPLE PAYBACK</small><b>{econ.metrics.simplePaybackYears===null?'N/A':econ.metrics.simplePaybackYears.toFixed(2)} <em>yr</em></b><span>R4 accepted case</span></div><div><small>IRR</small><b>{econ.metrics.irrPct===null?'N/A':econ.metrics.irrPct.toFixed(1)} <em>%</em></b><span>{state.selectedScenarioId} case</span></div><div><small>NPV</small><b className="small-value">{mx(econ.metrics.npvMxn)}</b><span>@ {state.financial.discountRatePct}% discount</span></div><div><small>PROPOSAL</small><b className="small-value">{proposalState}</b><span>{activeProposal?`v${activeProposal.versionNumber}${activeProposal.frozen?' · frozen':''}`:'Create customer document'}</span></div></section>
<div className="cockpit-grid"><section className="engineering-panel"><header><div><small>ENGINEERING → COMMERCIAL → DOCUMENT READINESS</small><h2>{proposalState==='Exported'?'Customer proposal exported':proposalOutdated?'Proposal needs a new source snapshot':'Project ready for proposal workflow'}</h2></div><PanelTop size={20}/></header><div className="engineering-checklist"><span className={quality==='Ready for sizing'?'done':'active'}>{quality==='Ready for sizing'?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>CFE consumption</b><small>{metrics.annualKwh.toLocaleString()} kWh · {quality}</small></span><span className={placedIds.length?'done':'active'}>{placedIds.length?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>Physical layout</b><small>{placedIds.length} placed modules · {dc.toFixed(2)} kWp</small></span><span className={engineeringComplete?'done':'active'}>{engineeringComplete?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>Electrical + production</b><small>{eState} · {assigned}/{placedIds.length} assigned · {Math.round(prod.annualProductionKwh).toLocaleString()} kWh/yr</small></span><span className={economicsComplete?'done':'active'}>{economicsComplete?<CheckCircle2 size={16}/>:<Zap size={16}/>}<b>Economics</b><small>{econ.readiness} · {econ.scenarios.find(s=>s.scenario.id===state.selectedScenarioId)?.scenario.name}</small></span><span className={activeProposal&&!proposalOutdated?'done':'active'}>{activeProposal&&!proposalOutdated?<CheckCircle2 size={16}/>:<FileText size={16}/>}<b>Customer proposal</b><small>{proposalState}{activeProposal?.exportMetadata?.filename?` · ${activeProposal.exportMetadata.filename}`:''}</small></span></div><Link className="next-action" to={`/projects/${project.id}/proposal`}>{activeProposal?'Review proposal workspace':'Create customer proposal'} <ArrowRight size={15}/></Link></section><section className="technical-panel"><header><small>R5 PROPOSAL TRACEABILITY</small><h2>Accepted source chain</h2></header><dl><div><dt>R1</dt><dd>Consumption · v{profile.version} · {quality}</dd></div><div><dt>R2</dt><dd>{design.layout.placements.length} modules · geometry snapshot</dd></div><div><dt>R3</dt><dd>{Math.round(prod.annualProductionKwh).toLocaleString()} kWh/yr · {eState}</dd></div><div><dt>R4</dt><dd>{econ.readiness} · {state.selectedScenarioId} economic case</dd></div><div><dt>Proposal</dt><dd>{proposalState}</dd></div><div><dt>Source fingerprint</dt><dd>{currentFingerprint}</dd></div></dl><p>R5 consumes and freezes accepted project outputs. It does not implement a second sizing, production, BOM or financial engine.</p></section></div></main>}
