import { project } from '../data';

export function ProposalDocument(){
  return <article className="proposal-document">
    <section className="proposal-cover"><div className="proposal-brand">HELIO <span>solar engineering</span></div><div><small>SOLAR ENERGY PROPOSAL</small><h1>{project.name}</h1><p>{project.customer}<br/>{project.address}</p></div><div className="cover-system"><span><small>PROPOSED PV</small><b>{project.kwp} kWp</b></span><span><small>ANNUAL PRODUCTION</small><b>{(project.production/1000).toFixed(1)} MWh</b></span><span><small>ENERGY OFFSET</small><b>{project.offset}%</b></span></div><footer>Prepared September 2026 · {project.id}</footer></section>
    <section className="proposal-section"><header><span>01</span><div><small>SYSTEM SUMMARY</small><h2>Designed around your CFE energy profile</h2></div></header><div className="proposal-kpis"><span><small>ANNUAL CONSUMPTION</small><b>21.84 MWh</b></span><span><small>SYSTEM SIZE</small><b>12.80 kWp</b></span><span><small>MODULES</small><b>20 × 640 W</b></span><span><small>OFFSET</small><b>95.6%</b></span></div></section>
    <section className="proposal-section split"><div><header><span>02</span><div><small>PRODUCTION</small><h2>20.89 MWh / year</h2></div></header><p>Illustrative R0 production scenario based on the current project design and annual energy baseline.</p><div className="production-bars">{[58,61,68,76,84,91,94,90,80,72,63,58].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></div><div><header><span>03</span><div><small>ECONOMICS</small><h2>Project impact</h2></div></header><dl><div><dt>Investment</dt><dd>MX$ 278,400</dd></div><div><dt>Annual savings</dt><dd>MX$ 58,520</dd></div><div><dt>Simple payback</dt><dd>4.7 years</dd></div><div><dt>25-year savings</dt><dd>MX$ 1.46M</dd></div></dl></div></section>
    <section className="proposal-section"><header><span>04</span><div><small>EQUIPMENT</small><h2>Selected technical package</h2></div></header><div className="proposal-equipment"><span><small>PV MODULE</small><b>Jinko Solar Tiger Neo 640 W</b><em>20 modules · N-type · 23.0% efficiency</em></span><span><small>INVERTER</small><b>Huawei SUN2000-12K-MAP0</b><em>12 kW · 2 MPPT · 1100 V max DC</em></span><span><small>STORAGE</small><b>Not included</b><em>Battery-ready scenario</em></span></div></section>
    <section className="proposal-section terms"><header><span>05</span><div><small>TERMS</small><h2>Commercial notes</h2></div></header><p>Values shown in this R0.1 proposal preview are illustrative mock data. Final engineering, production and financial assumptions will be validated in later authorized milestones.</p></section>
  </article>;
}
