import {useMemo,useRef,useState} from 'react';
import {Ban,Copy,Grid3X3,Layers3,Minus,MousePointer2,Move,PanelTop,PencilRuler,Plus,Redo2,Save,Trash2,Undo2} from 'lucide-react';
import {deriveEnergyMetrics} from '../domain/energy/metrics';
import {generateSizingScenarios} from '../domain/energy/sizing';
import {useEnergyProfile} from '../domain/energy/store';
import {autoLayout} from '../domain/design/layout';
import {moduleSize,offsetPolygon,polygonArea,polygonSelfIntersects,snap,translatePoints} from '../domain/design/math';
import {summarizeDesign} from '../domain/design/summary';
import {createDefaultSiteDesign,type Coordinate2D,type ModulePlacement,type Orientation,type SiteDesign} from '../domain/design/types';
import {useSiteDesign} from '../domain/design/store';
import {validatePlacement} from '../domain/design/collision';
import {project} from '../data';

type Tool='select'|'roof'|'obstruction'|'zone'|'modules'|'pan';
type Drag={kind:'vertex'|'roof'|'module'|'obstruction'|'restricted'|'pan';id:string;vertexId?:string;start:Coordinate2D;original:SiteDesign};
const tools:[Tool,string,React.ReactNode][]=[['select','Select',<MousePointer2 size={17}/>],['roof','Roof',<PencilRuler size={17}/>],['obstruction','Obstacle',<Grid3X3 size={17}/>],['zone','Restricted',<Ban size={17}/>],['modules','Modules',<PanelTop size={17}/>],['pan','Pan',<Move size={17}/>]];
const pts=(a:{x:number;y:number}[])=>a.map(p=>`${p.x},${p.y}`).join(' ');
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
export function SolarDesigner(){
 const {profile}=useEnergyProfile();const energy=deriveEnergyMetrics(profile);const scenarios=generateSizingScenarios(energy.annualKwh,profile.objective.targetOffset,profile.assumptions);const basis=scenarios.find(s=>s.id===profile.selectedScenarioId);const fallback=useMemo(()=>createDefaultSiteDesign(profile.assumptions.panelWattage,basis?.panelCount||0,basis?.dcKwp||0,basis?.targetOffset||profile.objective.targetOffset),[]);
 const {design,setDesign}=useSiteDesign(fallback);const [tool,setTool]=useState<Tool>('select');const [draft,setDraft]=useState<Coordinate2D[]>([]);const [feedback,setFeedback]=useState('World geometry ready');const [invalid,setInvalid]=useState<{m:ModulePlacement;reason:string}|null>(null);const [past,setPast]=useState<SiteDesign[]>([]);const [future,setFuture]=useState<SiteDesign[]>([]);const drag=useRef<Drag|null>(null);const svgRef=useRef<SVGSVGElement>(null);const summary=useMemo(()=>summarizeDesign(design),[design]);
 const commit=(next:SiteDesign,msg?:string)=>{setPast(p=>[...p,structuredClone(design)]);setFuture([]);setDesign({...next,updatedAt:new Date().toISOString()});if(msg)setFeedback(msg)};
 const undo=()=>{if(!past.length)return;const prev=past.at(-1)!;setFuture(f=>[structuredClone(design),...f]);setPast(p=>p.slice(0,-1));setDesign(prev);setFeedback('Undo applied')};const redo=()=>{if(!future.length)return;const next=future[0];setPast(p=>[...p,structuredClone(design)]);setFuture(f=>f.slice(1));setDesign(next);setFeedback('Redo applied')};
 const toWorld=(e:{clientX:number;clientY:number})=>{const r=svgRef.current!.getBoundingClientRect();const bx=(e.clientX-r.left)/r.width*30,by=(e.clientY-r.top)/r.height*20;return{x:snap((bx-design.camera.panX)/design.camera.zoom,design.camera.snap),y:snap((by-design.camera.panY)/design.camera.zoom,design.camera.snap)}};
 const select=(type:SiteDesign['selected']['type'],ids:string[])=>setDesign(d=>({...d,selected:{type,ids}}));
 const canvasClick=(e:React.MouseEvent<SVGSVGElement>)=>{if(e.target!==e.currentTarget&&!(e.target as Element).classList.contains('r2-grid-bg'))return;const p=toWorld(e);if(tool==='roof'){setDraft(d=>[...d,p]);setFeedback(`${draft.length+1} roof vertices · click Close roof when ready`);return;}if(tool==='obstruction'){const o={id:uid('obs'),kind:'rect' as const,name:'New obstruction',type:'other' as const,x:p.x-1,y:p.y-.75,width:2,height:1.5,heightM:1};commit({...design,obstructions:[...design.obstructions,o],selected:{type:'obstruction',ids:[o.id]}},'Rectangular obstruction created');return;}if(tool==='zone'){const z={id:uid('rz'),name:'No-module zone',type:'no-module' as const,points:[{id:uid('p'),x:p.x-1.5,y:p.y-.6},{id:uid('p'),x:p.x+1.5,y:p.y-.6},{id:uid('p'),x:p.x+1.5,y:p.y+.6},{id:uid('p'),x:p.x-1.5,y:p.y+.6}]};commit({...design,restrictedZones:[...design.restrictedZones,z],selected:{type:'restricted',ids:[z.id]}},'Restricted polygon created');return;}if(tool==='modules'){const roof=design.roofs[0];if(!roof){setFeedback('Create a roof before placing modules');return;}const s=moduleSize(design.moduleDimensions,design.layout.orientation);const m:ModulePlacement={id:uid('mod'),roofId:roof.id,x:snap(p.x-s.width/2,design.camera.snap),y:snap(p.y-s.height/2,design.camera.snap),orientation:design.layout.orientation,rotation:design.layout.orientation==='portrait'?0:90,valid:true};const v=validatePlacement(m,design);if(!v.valid){setInvalid({m,reason:v.reason||'invalid placement'});setFeedback(`Placement rejected: ${v.reason}`);return;}setInvalid(null);commit({...design,layout:{...design.layout,placements:[...design.layout.placements,m]},selected:{type:'module',ids:[m.id]}},'Module placed in usable roof area');}}
 const closeRoof=()=>{if(draft.length<3){setFeedback('Roof requires at least 3 vertices');return;}if(polygonArea(draft)<.1){setFeedback('Roof rejected: polygon area is zero');return;}if(polygonSelfIntersects(draft)){setFeedback('Roof rejected: self-intersection detected');return;}const id=uid('roof'),roof={id,name:`Roof ${design.roofs.length+1}`,points:draft.map((p,i)=>({...p,id:`${id}-v${i}`})),azimuth:180,tilt:10,roofType:'flat' as const,setback:.6};commit({...design,roofs:[...design.roofs,roof],selected:{type:'roof',ids:[id]}},`Roof created · ${polygonArea(roof.points).toFixed(1)} m²`);setDraft([]);setTool('select')};
 const startDrag=(kind:Drag['kind'],id:string,e:React.PointerEvent,vertexId?:string)=>{e.stopPropagation();if(tool!=='select'&&kind!=='pan')return;drag.current={kind,id,vertexId,start:toWorld(e),original:structuredClone(design)};(e.currentTarget as Element).setPointerCapture?.(e.pointerId)};
 const onMove=(e:React.PointerEvent<SVGSVGElement>)=>{if(!drag.current)return;const d=drag.current,p=toWorld(e),dx=p.x-d.start.x,dy=p.y-d.start.y,o=d.original;if(d.kind==='vertex')setDesign({...o,roofs:o.roofs.map(r=>r.id===d.id?{...r,points:r.points.map(v=>v.id===d.vertexId?{...v,x:v.x+dx,y:v.y+dy}:v)}:r)});if(d.kind==='roof')setDesign({...o,roofs:o.roofs.map(r=>r.id===d.id?{...r,points:translatePoints(r.points,dx,dy)}:r),layout:{...o.layout,placements:o.layout.placements.map(m=>m.roofId===d.id?{...m,x:m.x+dx,y:m.y+dy}:m)}});if(d.kind==='module')setDesign({...o,layout:{...o.layout,placements:o.layout.placements.map(m=>m.id===d.id?{...m,x:snap(m.x+dx,o.camera.snap),y:snap(m.y+dy,o.camera.snap)}:m)}});if(d.kind==='obstruction')setDesign({...o,obstructions:o.obstructions.map(x=>x.id===d.id?{...x,x:(x.x||0)+dx,y:(x.y||0)+dy}:x)});if(d.kind==='restricted')setDesign({...o,restrictedZones:o.restrictedZones.map(z=>z.id===d.id?{...z,points:translatePoints(z.points,dx,dy)}:z)});if(d.kind==='pan'){const r=svgRef.current!.getBoundingClientRect();setDesign({...o,camera:{...o.camera,panX:o.camera.panX+(e.clientX-(e.nativeEvent as any).movementX-r.left)*0+dx*o.camera.zoom,panY:o.camera.panY+dy*o.camera.zoom}})}};
 const endDrag=()=>{if(!drag.current)return;const d=drag.current;let next=design;if(d.kind==='module'){const m=design.layout.placements.find(x=>x.id===d.id)!;const v=validatePlacement(m,design,[m.id]);if(!v.valid){next=d.original;setFeedback(`Move rejected: ${v.reason}`)}else setFeedback('Geometry moved');}if(d.kind==='vertex'){const r=design.roofs.find(x=>x.id===d.id);if(!r||polygonArea(r.points)<.1||polygonSelfIntersects(r.points)){next=d.original;setFeedback('Vertex edit rejected: invalid/self-intersecting roof')}else setFeedback('Roof vertex updated');}if(JSON.stringify(next)!==JSON.stringify(d.original)){setPast(p=>[...p,d.original]);setFuture([]);setDesign({...next,updatedAt:new Date().toISOString()})}else setDesign(next);drag.current=null};
 const selectedRoof=design.selected.type==='roof'?design.roofs.find(r=>design.selected.ids.includes(r.id)):undefined;const selectedModules=design.selected.type==='module'?design.layout.placements.filter(m=>design.selected.ids.includes(m.id)):[];const selectedObs=design.selected.type==='obstruction'?design.obstructions.find(o=>design.selected.ids.includes(o.id)):undefined;const selectedZone=design.selected.type==='restricted'?design.restrictedZones.find(z=>design.selected.ids.includes(z.id)):undefined;
 const auto=(o:Orientation)=>{const roof=selectedRoof||design.roofs[0];if(!roof)return;const next={...design,layout:{...design.layout,orientation:o,placements:[]}};const placements=autoLayout(next,roof,o);commit({...next,layout:{...next.layout,placements},selected:{type:'module',ids:placements.slice(0,1).map(m=>m.id)}},`Auto-fill ${o}: ${placements.length} modules fit`)};const clear=()=>commit({...design,layout:{...design.layout,placements:[]},selected:{type:null,ids:[]}},'Layout cleared');
 const orientSelected=(o:Orientation)=>{if(!selectedModules.length)return;const changed=design.layout.placements.map(m=>selectedModules.some(s=>s.id===m.id)?{...m,orientation:o,rotation:o==='portrait'?0:90}:m);const temp={...design,layout:{...design.layout,placements:changed}};const invalids=changed.filter(m=>selectedModules.some(s=>s.id===m.id)&&!validatePlacement(m,temp,[m.id]).valid);if(invalids.length){setFeedback('Orientation change rejected: geometry collision');return;}commit(temp,`Selected modules changed to ${o}`)};
 const deleteSelection=()=>{const s=design.selected;let next=design;if(s.type==='roof')next={...next,roofs:next.roofs.filter(r=>!s.ids.includes(r.id)),layout:{...next.layout,placements:next.layout.placements.filter(m=>!s.ids.includes(m.roofId))}};if(s.type==='module')next={...next,layout:{...next.layout,placements:next.layout.placements.filter(m=>!s.ids.includes(m.id))}};if(s.type==='obstruction')next={...next,obstructions:next.obstructions.filter(o=>!s.ids.includes(o.id))};if(s.type==='restricted')next={...next,restrictedZones:next.restrictedZones.filter(z=>!s.ids.includes(z.id))};commit({...next,selected:{type:null,ids:[]}},'Selection deleted')};
 const duplicateModules=()=>{if(!selectedModules.length)return;const additions=selectedModules.map(m=>({...m,id:uid('mod'),x:m.x+.3,y:m.y+.3}));const temp={...design,layout:{...design.layout,placements:[...design.layout.placements,...additions]}};if(additions.some(m=>!validatePlacement(m,temp,[m.id,...selectedModules.map(s=>s.id)]).valid)){setFeedback('Duplicate rejected: no collision-free offset');return;}commit({...temp,selected:{type:'module',ids:additions.map(m=>m.id)}},'Selected modules duplicated')};
 return <main className="designer-page r2-designer"><div className="design-basis-banner"><b>R1 design basis:</b><span>{design.targetPanelCount} × {design.panelWattage} W · {design.targetDcKwp.toFixed(2)} kWp · target {design.targetOffset}% offset</span><em>R2 geometry controls physical roof capacity only</em></div><div className="designer-top"><div><small>{project.id} / R2 GEOMETRY</small><b>{project.name}</b><span>{feedback}</span></div><div className="designer-actions"><button onClick={undo} className={!past.length?'disabled':''}><Undo2 size={15}/>Undo</button><button onClick={redo} className={!future.length?'disabled':''}><Redo2 size={15}/>Redo</button><button><Save size={15}/>Persisted</button></div></div>
 <div className="designer-body"><aside className="tool-rail">{tools.map(([id,label,icon])=><button key={id} title={label} className={tool===id?'active':''} onClick={()=>{setTool(id);if(id!=='roof')setDraft([])}}>{icon}<span>{label}</span></button>)}</aside><section className="design-stage"><div className="r2-canvas-toolbar"><div><b>WORLD 2D · meters</b><span>Snap {design.camera.snap.toFixed(2)} m</span></div><div className="r2-layout-actions">{draft.length>0&&<button className="primary" onClick={closeRoof}>Close roof ({draft.length})</button>}<button onClick={()=>auto('portrait')}>Auto-fill portrait</button><button onClick={()=>auto('landscape')}>Auto-fill landscape</button><button onClick={clear}>Clear layout</button></div></div><div className="r2-canvas-shell"><svg ref={svgRef} className="r2-canvas" viewBox="0 0 30 20" onClick={canvasClick} onPointerMove={onMove} onPointerUp={endDrag} onPointerLeave={endDrag} onWheel={e=>{e.preventDefault();setDesign(d=>({...d,camera:{...d.camera,zoom:Math.min(2.5,Math.max(.6,d.camera.zoom+(e.deltaY<0?.1:-.1)))}}))}}><defs><pattern id="grid" width={design.camera.snap*10} height={design.camera.snap*10} patternUnits="userSpaceOnUse"><path d={`M ${design.camera.snap*10} 0 L 0 0 0 ${design.camera.snap*10}`} fill="none" stroke="#d9e1df" strokeWidth=".02"/></pattern></defs><rect className="r2-grid-bg" width="30" height="20" fill={design.layers.grid?'url(#grid)':'#eef2f1'}/><g transform={`translate(${design.camera.panX} ${design.camera.panY}) scale(${design.camera.zoom})`}>
 {design.layers.roofs&&design.roofs.map(r=><g key={r.id}><polygon className={`r2-roof ${design.selected.type==='roof'&&design.selected.ids.includes(r.id)?'selected':''}`} points={pts(r.points)} onClick={e=>{e.stopPropagation();select('roof',[r.id])}} onPointerDown={e=>startDrag('roof',r.id,e)}/>{design.layers.setbacks&&<polygon className="r2-setback" points={pts(offsetPolygon(r.points,r.setback))}/>} {design.layers.labels&&<text x={r.points[0]?.x} y={(r.points[0]?.y||0)-.25}>{r.name} · {polygonArea(r.points).toFixed(1)} m²</text>}{design.selected.type==='roof'&&design.selected.ids.includes(r.id)&&r.points.map(v=><circle key={v.id} className="r2-vertex" cx={v.x} cy={v.y} r=".13" onPointerDown={e=>startDrag('vertex',r.id,e,v.id)}/>)}</g>)}
 {design.layers.obstructions&&design.obstructions.map(o=>o.kind==='rect'?<g key={o.id}><rect className={`r2-obstruction ${design.selected.type==='obstruction'&&design.selected.ids.includes(o.id)?'selected':''}`} x={o.x} y={o.y} width={o.width} height={o.height} onClick={e=>{e.stopPropagation();select('obstruction',[o.id])}} onPointerDown={e=>startDrag('obstruction',o.id,e)}/>{design.layers.labels&&<text x={(o.x||0)+.1} y={(o.y||0)+.35}>{o.name}</text>}</g>:<polygon key={o.id} className="r2-obstruction" points={pts(o.points||[])} />)}
 {design.layers.obstructions&&design.restrictedZones.map(z=><g key={z.id}><polygon className={`r2-zone ${design.selected.type==='restricted'&&design.selected.ids.includes(z.id)?'selected':''}`} points={pts(z.points)} onClick={e=>{e.stopPropagation();select('restricted',[z.id])}} onPointerDown={e=>startDrag('restricted',z.id,e)}/>{design.layers.labels&&<text x={z.points[0].x} y={z.points[0].y+.35}>{z.name}</text>}</g>)}
 {design.layers.modules&&design.layout.placements.map(m=>{const s=moduleSize(design.moduleDimensions,m.orientation);const sel=design.selected.type==='module'&&design.selected.ids.includes(m.id);return <g key={m.id}><rect className={`r2-module ${sel?'selected':''}`} x={m.x} y={m.y} width={s.width} height={s.height} onClick={e=>{e.stopPropagation();const ids=e.shiftKey&&design.selected.type==='module'?Array.from(new Set([...design.selected.ids,m.id])):[m.id];select('module',ids)}} onPointerDown={e=>startDrag('module',m.id,e)}/>{design.layers.labels&&sel&&<text className="module-label" x={m.x} y={m.y-.08}>{m.orientation} · {m.x.toFixed(1)},{m.y.toFixed(1)}</text>}</g>})}
 {draft.length>0&&<><polyline className="r2-draft" points={pts(draft)}/>{draft.map((p,i)=><circle key={i} className="r2-draft-point" cx={p.x} cy={p.y} r=".11"/>)}</>}{invalid&&(()=>{const s=moduleSize(design.moduleDimensions,invalid.m.orientation);return <rect className="r2-invalid-module" x={invalid.m.x} y={invalid.m.y} width={s.width} height={s.height}/>})()}</g></svg><div className="r2-zoom"><button onClick={()=>setDesign(d=>({...d,camera:{...d.camera,zoom:Math.max(.6,d.camera.zoom-.1)}}))}><Minus size={13}/></button><b>{Math.round(design.camera.zoom*100)}%</b><button onClick={()=>setDesign(d=>({...d,camera:{...d.camera,zoom:Math.min(2.5,d.camera.zoom+.1)}}))}><Plus size={13}/></button></div>{invalid&&<div className="r2-invalid-feedback">Placement blocked · {invalid.reason}</div>}</div></section>
 <aside className="inspector r2-inspector"><div className="inspector-head"><small>GEOMETRY INSPECTOR</small><h3>{design.selected.type?`${design.selected.ids.length} ${design.selected.type}${design.selected.ids.length>1?'s':''}`:'Nothing selected'}</h3><span>World-coordinate properties</span></div>{selectedRoof&&<RoofInspector roof={selectedRoof} design={design} commit={commit}/>} {selectedModules.length===1&&<ModuleInspector m={selectedModules[0]} design={design}/>} {selectedModules.length>1&&<div className="r2-properties"><label>Selected modules<b>{selectedModules.length}</b></label><label>Total DC<b>{(selectedModules.length*design.panelWattage/1000).toFixed(2)} kWp</b></label><div className="segmented"><button onClick={()=>orientSelected('portrait')}>Portrait</button><button onClick={()=>orientSelected('landscape')}>Landscape</button></div><button className="secondary" onClick={duplicateModules}><Copy size={13}/>Duplicate</button></div>} {selectedObs&&<ObstructionInspector o={selectedObs}/>} {selectedZone&&<div className="r2-properties"><label>Restricted zone<b>{selectedZone.name}</b></label><label>Area<b>{polygonArea(selectedZone.points).toFixed(2)} m²</b></label><label>Type<b>{selectedZone.type}</b></label></div>} {design.selected.type&&<button className="danger-action" onClick={deleteSelection}><Trash2 size={14}/>Delete selection</button>}<div className="r2-layers"><small>LAYERS</small>{Object.entries(design.layers).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={()=>setDesign(d=>({...d,layers:{...d.layers,[k]:!v}}))}/>{k}</label>)}</div></aside></div>
 <footer className="designer-kpis r2-kpis"><span><small>ROOF GROSS</small><b>{summary.grossArea.toFixed(1)} m²</b></span><span><small>USABLE AREA</small><b>{summary.usableArea.toFixed(1)} m²</b></span><span><small>PLACED / CAPACITY</small><b>{summary.placedCount} / {summary.capacity}</b></span><span><small>PLACED DC</small><b>{summary.placedDcKwp.toFixed(2)} kWp</b></span><span><small>TARGET DC</small><b>{summary.targetDcKwp.toFixed(2)} kWp</b></span><span className={summary.status.replace(' ','-').toLowerCase()}><small>TARGET DELTA</small><b>{summary.deltaPanels>0?'+':''}{summary.deltaPanels} modules</b><em>{summary.status}</em></span></footer></main>}
function RoofInspector({roof,design,commit}:{roof:any;design:SiteDesign;commit:(n:SiteDesign,m?:string)=>void}){const patch=(p:any)=>commit({...design,roofs:design.roofs.map(r=>r.id===roof.id?{...r,...p}:r)},'Roof property updated');const addVertex=()=>{const a=roof.points[0],b=roof.points[1],v={id:uid('v'),x:(a.x+b.x)/2,y:(a.y+b.y)/2};patch({points:[a,v,...roof.points.slice(1)]})};const removeVertex=()=>roof.points.length>3&&patch({points:roof.points.slice(0,-1)});return <div className="r2-properties"><label>Name<input value={roof.name} onChange={e=>patch({name:e.target.value})}/></label><label>Gross area<b>{polygonArea(roof.points).toFixed(2)} m²</b></label><label>Azimuth<input type="number" value={roof.azimuth} onChange={e=>patch({azimuth:Number(e.target.value)})}/></label><label>Tilt<input type="number" value={roof.tilt} onChange={e=>patch({tilt:Number(e.target.value)})}/></label><label>Roof type<select value={roof.roofType} onChange={e=>patch({roofType:e.target.value})}><option>flat</option><option>metal</option><option>tile</option><option>concrete</option></select></label><label>Edge setback<input type="number" step="0.1" min="0" value={roof.setback} onChange={e=>patch({setback:Number(e.target.value)})}/><small>meters · usable boundary recalculates</small></label><div className="r2-inline"><button className="secondary" onClick={addVertex}>Insert vertex</button><button className="secondary" disabled={roof.points.length<=3} onClick={removeVertex}>Remove vertex</button></div></div>}
function ModuleInspector({m,design}:{m:ModulePlacement;design:SiteDesign}){const s=moduleSize(design.moduleDimensions,m.orientation);const v=validatePlacement(m,design,[m.id]);return <div className="r2-properties"><label>Module model<b>Project basis · {design.panelWattage} W</b></label><label>Physical dimensions<b>{s.width.toFixed(2)} × {s.height.toFixed(2)} m</b></label><label>Orientation<b>{m.orientation}</b></label><label>Design position<b>x {m.x.toFixed(2)} · y {m.y.toFixed(2)} m</b></label><label>Rotation<b>{m.rotation}°</b></label><label>Validity<b className={v.valid?'valid':'invalid'}>{v.valid?'Valid':'Invalid · '+v.reason}</b></label></div>}
function ObstructionInspector({o}:{o:any}){return <div className="r2-properties"><label>Obstruction<b>{o.name}</b></label><label>Type<b>{o.type}</b></label><label>Dimensions<b>{(o.width||0).toFixed(2)} × {(o.height||0).toFixed(2)} m</b></label><label>Area<b>{((o.width||0)*(o.height||0)).toFixed(2)} m²</b></label><label>Height placeholder<b>{o.heightM||0} m</b></label></div>}
