import{chromium}from'playwright';import{mkdir,writeFile,readFile}from'node:fs/promises';import{createHash}from'node:crypto';
const base=process.env.R8_BASE_URL||'http://127.0.0.1:4173',out='artifacts/r8';await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true});
const doc={id:'11111111-1111-4111-8111-111111111111',projectId:'SOL-2026-0184',filename:'recibo-cfe-sintetico.pdf',mimeType:'application/pdf',byteSize:48211,sha256:'a'.repeat(64),status:'needs-review',schemaVersion:1,reviewBlocked:true,validationIssues:[{code:'LOW_CONFIDENCE_CRITICAL',severity:'blocking',field:'totalBill',message:'totalBill requiere revisión por baja confianza.'},{code:'TOTAL_RECONCILIATION',severity:'blocking',message:'Cargos e importe total no reconcilian dentro de 1%.'}]};
const intelligence={documents:[doc],profile:{entries:[{periodStart:'2025-03-01',periodEnd:'2025-04-30',kwh:3120,provenance:'bill'},{periodStart:'2025-05-01',periodEnd:'2025-06-30',kwh:3640,provenance:'bill'}],totalKwh:6760,coveredDays:122,annualizedKwh:null,completeness:.334,missingPeriods:true,allocationMethod:'none-no-invented-months'},readiness:{score:49,ready:false,components:{extraction:15,history:7,address:10,resource:7,electrical:15,pricing:0,tariff:10},blockers:2,recommendations:['Completar historial de consumo','Resolver revisiones bloqueantes']},scenarios:[],scenarioSource:'accepted-r1-r4-engines-only'};
async function page(viewport={width:1440,height:1000}){const p=await browser.newPage({viewport});await p.route('**/api/**',async route=>{const u=new URL(route.request().url()),path=u.pathname;if(path==='/api/auth/me')return route.fulfill({json:{userId:'u1',email:'admin@example.test',displayName:'Daniel G.',organizationId:'00000000-0000-4000-8000-000000000001',organizationSlug:'buenos-dias-sol',role:'Admin',locale:'es-MX'}});if(path.endsWith('/projects'))return route.fulfill({json:[{id:'SOL-2026-0184',name:'Residencia Montebello'}]});if(path.includes('/ai/projects/'))return route.fulfill({json:intelligence});if(path.endsWith('/ai/documents'))return route.fulfill({json:[doc]});if(path.endsWith('/ai/usage'))return route.fulfill({json:[{day:'2026-09-25',operation:'cfe-extraction',provider:'mock',status:'succeeded',calls:128,inputTokens:0,outputTokens:0,costUsd:0}]});if(path.endsWith('/ai/copilot'))return route.fulfill({json:{answer:'El consumo proviene de dos periodos CFE validados. No existe base suficiente para anualizar.',citations:['utility_documents:1111','consumption_history_entries'],toolCalls:[],trace:{provider:'mock'}}});if(path.includes('/content'))return route.fulfill({status:200,contentType:'application/pdf',body:Buffer.from('%PDF-1.4 synthetic')});return route.fulfill({json:{}})});await p.goto(`${base}/ai?project=SOL-2026-0184`,{waitUntil:'networkidle'});return p}
const specs=[
 ['bill-upload-mobile.png','Captura CFE',390,844],['bill-extraction.png','Revisión',1440,1000],['bill-review.png','Revisión',1440,1000],['bill-provenance.png','Revisión',1280,900],['consumption-history.png','Historial',1440,1000],['autonomous-project.png','Escenarios',1440,1000],['scenario-comparison.png','Escenarios',1440,1000],['quote-readiness.png','Escenarios',1280,900],['copilot-project.png','Copilot',1440,1000],['copilot-provenance.png','Copilot',1280,900],['ai-usage-admin.png','Uso IA',1440,1000],['proposal-ai-draft.png','Copilot',1440,1000],['mobile-scenario.png','Escenarios',390,844],['tablet-review.png','Revisión',1024,1366]
];
for(const[name,tab,w,h]of specs){const p=await page({width:w,height:h});if(tab!=='Captura CFE')await p.getByRole('button',{name:tab,exact:true}).click();if(tab==='Copilot'){await p.getByPlaceholder('¿De dónde salió el consumo anual?').fill('¿De dónde salió el consumo anual?');await p.getByRole('button',{name:'Preguntar'}).click()}await p.screenshot({path:`${out}/${name}`,fullPage:true});await p.close()}
await browser.close();const files=[];for(const[name]of specs){const b=await readFile(`${out}/${name}`);files.push({name,sha256:createHash('sha256').update(b).digest('hex'),bytes:b.length})}const manifest={schemaVersion:1,sourceRevision:process.env.GITHUB_SHA||'local',generatedAt:new Date().toISOString(),note:'Synthetic/mock evidence only; no customer documents or provider secrets.',files};await writeFile(`${out}/evidence-manifest.json`,JSON.stringify(manifest,null,2)+'\n');await writeFile(`${out}/SHA256SUMS.txt`,files.map(x=>`${x.sha256}  ${x.name}`).join('\n')+'\n');
