import {chromium} from 'playwright';import fs from 'node:fs/promises';
const base=process.env.R2_BASE_URL||'http://127.0.0.1:4173';const out='artifacts/screenshots/r2';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true});
async function session(){const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1});const page=await context.newPage();await page.goto(`${base}/projects/SOL-2026-0184/design`,{waitUntil:'networkidle'});await page.evaluate(()=>localStorage.removeItem('solar-platform-v2:r2:site-design:SOL-2026-0184'));await page.reload({waitUntil:'networkidle'});return{context,page}}
async function wc(page,x,y){const b=await page.locator('.r2-canvas').boundingBox();await page.mouse.click(b.x+b.width*x/30,b.y+b.height*y/20)}async function shot(name,fn){const {context,page}=await session();await fn(page);await page.screenshot({path:`${out}/${name}.png`,fullPage:false});await context.close()}
await shot('roof-create',async p=>{await p.getByTitle('Roof').click();await wc(p,2,2);await wc(p,4.5,2);await wc(p,4.5,3.7);await wc(p,2,3.7);await p.getByRole('button',{name:/Close roof/}).click()});
await shot('roof-edit',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();const az=p.locator('.r2-properties label').filter({hasText:'Azimuth'}).locator('input');await az.fill('205');const tilt=p.locator('.r2-properties label').filter({hasText:'Tilt'}).locator('input');await tilt.fill('15')});
await shot('setback-obstacles',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();const sb=p.locator('.r2-properties label').filter({hasText:'Edge setback'}).locator('input');await sb.fill('0.9');await p.getByTitle('Obstacle').click();await wc(p,10,8);await p.getByTitle('Restricted').click();await wc(p,17,9.5)});
await shot('manual-placement-valid',async p=>{await p.getByTitle('Modules').click();await wc(p,8,6);await p.getByTitle('Select').click();await p.locator('.r2-module').last().click()});
await shot('manual-placement-invalid',async p=>{await p.getByTitle('Modules').click();await wc(p,1,1);await p.waitForTimeout(80)});
await shot('auto-layout-portrait',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();await p.getByRole('button',{name:'Auto-fill portrait'}).click()});
await shot('auto-layout-landscape',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();await p.getByRole('button',{name:'Auto-fill landscape'}).click()});
await shot('target-capacity-delta',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();await p.getByRole('button',{name:'Auto-fill portrait'}).click()});
await shot('designer-persisted',async p=>{await p.getByTitle('Select').click();await p.locator('.r2-roof').first().click();await p.getByRole('button',{name:'Auto-fill landscape'}).click();const count=await p.locator('.r2-module').count();await p.reload({waitUntil:'networkidle'});if(await p.locator('.r2-module').count()!==count)throw new Error('persistence screenshot state failed')});
await browser.close();console.log('Captured nine R2 screenshots from real browser states at 1600x1000.');
