import pg from 'pg';
import {MockAIProvider} from '../server/ai/provider';
import {acceptDocument,correctField,documentContent,extractDocument,listDocuments,storeDocument} from '../server/ai/service';

const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is required');const pool=new pg.Pool({connectionString:url});const ok=(v:unknown,m:string)=>{if(!v)throw new Error(m)};
const org=(await pool.query(`select id from organizations where slug='buenos-dias-sol'`)).rows[0]?.id,other=(await pool.query(`select id from organizations where slug='tenant-lab'`)).rows[0]?.id,admin=(await pool.query(`select id from users where email='admin@buenosdiassol.local'`)).rows[0]?.id;ok(org&&other&&admin,'seed identities missing');
const migration=await pool.query(`select 1 from schema_migrations where version='003_r8_ai_intelligence'`);ok(migration.rowCount===1,'R8 migration missing');
const config=await pool.query('select enabled,provider,automation_level from organization_ai_config where organization_id=$1',[org]);ok(config.rows[0]?.enabled&&config.rows[0]?.provider==='mock'&&config.rows[0]?.automation_level==='assist','safe organization AI defaults missing');
const body=Buffer.from('%PDF-1.7\nSYNTHETIC CFE FIXTURE\n%%EOF');const uploaded=await storeDocument(org,admin,'SOL-2026-0184',{mimetype:'application/pdf',buffer:body,size:body.length,originalname:'r8-db-fixture.pdf'},pool as any);const extracted=await extractDocument(org,admin,uploaded.id,new MockAIProvider(),pool as any);ok(extracted.status==='validated','mock extraction did not validate');await correctField(org,admin,uploaded.id,{fieldPath:'customerName',normalized:'Cliente sintético revisado',reason:'DB validation'},pool as any);await acceptDocument(org,admin,uploaded.id,pool as any);
const docs=await listDocuments(org,'SOL-2026-0184',pool as any);ok(docs.some((x:any)=>x.id===uploaded.id&&x.extraction?.fields?.customerName?.status==='corrected'),'extraction/provenance/correction did not persist');let isolated=false;try{await documentContent(other,uploaded.id,pool as any)}catch{isolated=true}ok(isolated,'cross-tenant document content leaked');const history=await pool.query('select provenance from consumption_history_entries where organization_id=$1 and document_id=$2',[org,uploaded.id]);ok(history.rowCount===1&&history.rows[0].provenance==='bill','accepted history did not persist with provenance');const audit=await pool.query(`select event_type from audit_entries where organization_id=$1 and resource_id=$2 and event_type in ('uploaded','extracted','field-corrected','review-accepted')`,[org,uploaded.id]);ok(new Set(audit.rows.map(x=>x.event_type)).size===4,'R8 audit trail incomplete');
await pool.end();console.log('R8 DB validation passed: migration, safe defaults, private document, MockAI extraction, deterministic review, correction, history provenance, tenant isolation, and audit.');
