import {chromium} from 'playwright';
const base=process.env.R3_BASE_URL||'http://127.0.0.1:4173',url=`${base}/projects/SOL-2026-0184/design`;const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1600,height:1000}});const page=await context.newPage();const assert=(v,m)=>{if(!v)throw new Error(m)};
const placements=Array.from({length:24},(_,i)=>({id:`m${i+1}`,roofId:'roof-1',x:6+(i%8)*1.7,y:5+Math.floor(i/8)*2.4,orientation:'portrait',rotation:0,valid:true}));
async function seed(){await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(({placements})=>{localStorage.setItem('solar-platform-v2:r2:site-design:SOL-2026-0184',JSON.stringify({version:2,projectId:'SOL-2026-0184',designBasisId:'recommended',roofs:[{id:'roof-1',name:'Main roof',points:[{id:'v1',x:5,y:4},{id:'v2',x:22,y:4},{id:'v3',x:23,y:15},{id:'v4',x:6,y:16}],azimuth:184,tilt:11,roofType:'flat',setback:.6}],obstructions:[],restrictedZones:[],layout:{placements,orientation:'portrait',gap:.08,rowSpacing:.12},moduleDimensions:{width:1.13,height:2.28},panelWattage:640,targetPanelCount:24,targetDcKwp:15.36,targetOffset:95,layers:{roofs:true,setbacks:true,modules:true,obstructions:true,grid:true,labels:true},camera:{zoom:1,panX:0,panY:0,snap:.1},selected:{type:'roof',ids:['roof-1']},updatedAt:new Date().toISOString()}));localStorage.removeItem('solar-platform-v2:r3:electrical:SOL-2026-0184');},{placements});await page.reload({waitUntil:'networkidle'});}
await seed();assert((await page.locator('.r3-canvas-meta').innerText()).includes('PLACED 24'),'R2 placed modules not driving R3');assert((await page.locator('.issues').innerText()).includes('unassigned-modules'),'unassigned state missing');
await page.getByRole('button',{name:/Auto-string/}).click();await page.waitForTimeout(100);assert((await page.locator('.r3-canvas-meta').innerText()).includes('UNASSIGNED 0'),'auto-string left modules unassigned');assert(await page.locator('.string-list button').count()>=2,'auto-string did not create strings');assert((await page.locator('.electrical-state').innerText()).includes('Electrically valid'),'valid electrical state not reached');
await page.locator('.string-list button').first().click();assert((await page.locator('.string-editor').innerText()).includes('Voc cold'),'string electrical inspector missing');await page.getByLabel('String MPPT').selectOption('1');assert((await page.locator('.string-list').innerText()).includes('MPPT 2'),'MPPT reassignment failed');
await page.getByLabel('Minimum design temperature').fill('-100');assert((await page.locator('.issues').innerText()).includes('cold-voc-high'),'cold Voc violation missing');await page.getByLabel('Minimum design temperature').fill('-5');
await page.getByLabel('Electrical module').selectOption('mod-585');assert((await page.locator('.issues').innerText()).includes('basis-module-mismatch'),'R1/module wattage mismatch warning missing');await page.getByLabel('Electrical module').selectOption('mod-640');await page.getByRole('button',{name:/Auto-string/}).click();
const persisted=await page.evaluate(()=>localStorage.getItem('solar-platform-v2:r3:electrical:SOL-2026-0184'));assert(!!persisted,'electrical state not persisted');await page.reload({waitUntil:'networkidle'});assert((await page.locator('.r3-canvas-meta').innerText()).includes('UNASSIGNED 0'),'electrical state did not survive refresh');
await page.getByRole('button',{name:/Production · R3/}).click();const before=await page.locator('.r3-summary b').innerText();await page.getByLabel('Resource Jan').fill('180');await page.getByLabel('Soiling').fill('5');const after=await page.locator('.r3-summary b').innerText();assert(before!==after,'production did not recalculate after resource/loss change');assert((await page.locator('.r3-production').innerText()).includes('not self-consumption'),'energy-balance disclaimer missing');
await page.goto(`${base}/projects/SOL-2026-0184`,{waitUntil:'networkidle'});const ws=await page.locator('.project-page').innerText();assert(ws.includes('SOLAR PROJECT COCKPIT · R3')&&ws.includes('DC/AC')&&ws.includes('ANNUAL PRODUCTION'),'Workspace R3 outputs missing');await browser.close();console.log('R3 browser validation passed: R2 capacity source, stringing/MPPT, electrical validation, basis mismatch, persistence, production recalculation and Workspace integration.');
