import {chromium} from 'playwright';
const base=process.env.R2_BASE_URL||'http://127.0.0.1:4173';const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1600,height:1000}});const page=await context.newPage();const url=`${base}/projects/SOL-2026-0184/design`;
const assert=(v,msg)=>{if(!v)throw new Error(msg)};async function reset(){await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>localStorage.removeItem('solar-platform-v2:r2:site-design:SOL-2026-0184'));await page.reload({waitUntil:'networkidle'})}async function worldClick(x,y){const b=await page.locator('.r2-canvas').boundingBox();if(!b)throw new Error('canvas missing');await page.mouse.click(b.x+b.width*x/30,b.y+b.height*y/20)}
// Baseline + physical settings + pan invariance.
await reset();assert(await page.locator('.r2-roof').count()===1,'default roof missing');assert((await page.locator('.r2-kpis').innerText()).includes('m²'),'geometry KPI missing');await page.getByLabel('Module width').fill('1.20');await page.getByLabel('Module height').fill('2.30');await page.getByLabel('Module gap').fill('0.10');await page.getByLabel('Row spacing').fill('0.15');await page.getByLabel('Snap grid').fill('0.05');await page.waitForTimeout(60);let state=JSON.parse(await page.evaluate(()=>localStorage.getItem('solar-platform-v2:r2:site-design:SOL-2026-0184')));assert(state.moduleDimensions.width===1.2&&state.moduleDimensions.height===2.3&&state.layout.gap===.1&&state.layout.rowSpacing===.15&&state.camera.snap===.05,'physical settings not persisted');const originalRoof=await page.locator('.r2-roof').first().getAttribute('points');await page.getByTitle('Pan').click();const box=await page.locator('.r2-canvas').boundingBox();await page.mouse.move(box.x+150,box.y+150);await page.mouse.down();await page.mouse.move(box.x+230,box.y+190);await page.mouse.up();await page.waitForTimeout(60);state=JSON.parse(await page.evaluate(()=>localStorage.getItem('solar-platform-v2:r2:site-design:SOL-2026-0184')));assert(Math.abs(state.camera.panX)>0||Math.abs(state.camera.panY)>0,'pan camera did not change');assert(await page.locator('.r2-roof').first().getAttribute('points')===originalRoof,'pan mutated world geometry');
// Roof create/edit/undo-redo in clean state.
await reset();await page.getByTitle('Roof').click();await worldClick(2,2);await worldClick(4,2);await worldClick(4,3.5);await worldClick(2,3.5);await page.getByRole('button',{name:/Close roof/}).click();assert(await page.locator('.r2-roof').count()===2,'roof create failed');assert((await page.locator('.r2-inspector').innerText()).includes('Gross area'),'roof inspector missing');await page.getByRole('button',{name:'Undo'}).click();assert(await page.locator('.r2-roof').count()===1,'undo roof create failed');await page.getByRole('button',{name:'Redo'}).click();assert(await page.locator('.r2-roof').count()===2,'redo roof create failed');await page.getByTitle('Select').click();await page.locator('.r2-roof').first().click();const az=page.locator('.r2-properties label').filter({hasText:'Azimuth'}).locator('input');await az.fill('205');const tilt=page.locator('.r2-properties label').filter({hasText:'Tilt'}).locator('input');await tilt.fill('15');assert((await page.locator('.r2-inspector').innerText()).includes('205'),'roof property edit failed');const vertexCount=await page.locator('.r2-vertex').count();await page.getByRole('button',{name:'Insert vertex'}).click();assert(await page.locator('.r2-vertex').count()===vertexCount+1,'insert vertex failed');await page.getByRole('button',{name:'Remove vertex'}).click();assert(await page.locator('.r2-vertex').count()===vertexCount,'remove vertex failed');
// Setback + blocked-zone creation in clean state.
await reset();await page.getByTitle('Select').click();await page.locator('.r2-roof').first().click();const setback=page.locator('.r2-properties label').filter({hasText:'Edge setback'}).locator('input');await setback.fill('0.9');assert(await page.locator('.r2-setback').count()>=1,'setback boundary missing');await page.getByTitle('Obstacle').click();await worldClick(10,8);assert(await page.locator('.r2-obstruction').count()>=2,'obstruction create failed');await page.getByTitle('Restricted').click();await worldClick(17,10);assert(await page.locator('.r2-zone').count()>=2,'restricted zone create failed');
// Manual placement: one known-valid point and one outside roof.
await reset();await page.getByTitle('Modules').click();const before=await page.locator('.r2-module').count();await worldClick(9,6.5);assert(await page.locator('.r2-module').count()===before+1,'valid manual module placement failed');await worldClick(1,1);assert((await page.locator('.designer-top').innerText()).includes('Placement rejected'),'invalid placement feedback missing');await page.getByTitle('Select').click();await page.locator('.r2-module').last().click();assert((await page.locator('.r2-inspector').innerText()).includes('Position'),'module inspector missing');
// Auto layout + target + persistence + multi-select in clean state.
await reset();await page.getByTitle('Select').click();await page.locator('.r2-roof').first().click();await page.getByRole('button',{name:'Auto-fill portrait'}).click();const portraitCount=await page.locator('.r2-module').count();assert(portraitCount>0,'portrait auto-layout empty');await page.getByRole('button',{name:'Undo'}).click();await page.getByRole('button',{name:'Redo'}).click();assert(await page.locator('.r2-module').count()===portraitCount,'auto-layout undo/redo failed');await page.getByTitle('Select').click();await page.locator('.r2-roof').first().click();await page.getByRole('button',{name:'Auto-fill landscape'}).click();const landscapeCount=await page.locator('.r2-module').count();assert(landscapeCount>0,'landscape auto-layout empty');const banner=await page.locator('.design-basis-banner').innerText();assert(banner.includes('R1 design basis')&&banner.includes('640 W'),'R1 target basis missing');assert((await page.locator('.r2-kpis').innerText()).includes('TARGET DELTA'),'target capacity delta missing');await page.waitForTimeout(60);const saved=await page.evaluate(()=>localStorage.getItem('solar-platform-v2:r2:site-design:SOL-2026-0184'));assert(!!saved,'design was not persisted');await page.reload({waitUntil:'networkidle'});assert(await page.locator('.r2-module').count()===landscapeCount,'module layout did not survive refresh');assert(await page.locator('.r2-roof').count()===1,'roof geometry did not survive refresh');await page.getByTitle('Select').click();const mods=page.locator('.r2-module');if(await mods.count()>1){await mods.nth(0).click();await mods.nth(1).click({modifiers:['Shift']});assert((await page.locator('.r2-inspector').innerText()).includes('Total DC'),'multi-select inspector missing')}
await browser.close();console.log('R2 browser validation passed: settings, pan invariance, roof create/edit, setbacks/exclusions, manual placement, auto-layout, target delta, persistence and undo/redo.');
