import {chromium} from 'playwright';import {seedR6,PROJECT} from './r6-fixture.mjs';
const base=process.env.R6_BASE_URL||'http://127.0.0.1:4173',assert=(v,m)=>{if(!v)throw new Error(m)};const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true}),page=await context.newPage();await seedR6(page,base);await page.goto(`${base}/crm`,{waitUntil:'networkidle'});await page.waitForSelector('[data-testid="crm-opportunities-table"]');assert((await page.locator('.crm-table tbody tr').count())>=3,'CRM opportunity table not populated');
// Full table filtering contract: source, proposal, status and search.
await page.getByLabel('Filter source').selectOption('referral');assert((await page.locator('.crm-table tbody tr').count())>=1,'source filter returned no fixture rows');await page.getByLabel('Filter source').selectOption('');await page.getByLabel('Filter proposal').selectOption('sent');assert((await page.locator('.crm-table').innerText()).includes('Exported'),'proposal sent filter failed');await page.getByLabel('Filter proposal').selectOption('all');await page.getByLabel('Sort opportunities').selectOption('value-desc');
// Configurable pipeline preserves stable IDs and persists presentation/operating assumptions.
await page.locator('[data-testid="crm-pipeline-settings"]').click();const label=page.getByLabel('Stage label contacted');await label.fill('Contacted / discovery');await page.getByLabel('Stage stale days contacted').fill('6');await page.reload({waitUntil:'networkidle'});assert(await page.getByLabel('Stage label contacted').inputValue()==='Contacted / discovery','pipeline label did not persist');assert(await page.getByLabel('Stage stale days contacted').inputValue()==='6','pipeline stale threshold did not persist');
await page.getByRole('button',{name:/New solar opportunity/}).click();await page.waitForSelector('[data-testid="crm-opportunity-detail"]');assert((await page.getByLabel('Account name').inputValue()).startsWith('New solar lead'),'create opportunity failed');await page.getByLabel('Account name').fill('Browser Validation Solar Lead');await page.getByLabel('Contact name').fill('Validation Contact');await page.getByLabel('Contact email').fill('validation@example.test');await page.goto(`${base}/crm`,{waitUntil:'networkidle'});assert((await page.locator('.crm-table').innerText()).includes('Browser Validation Solar Lead'),'account/contact edit persistence missing');
await page.getByRole('button',{name:'Board'}).click();assert(await page.locator('[data-testid="crm-pipeline-board"]').isVisible(),'pipeline board missing');const leadCard=page.locator('.pipeline-card').filter({hasText:'Browser Validation Solar Lead'});await leadCard.getByLabel(/Move .* stage/).selectOption('proposal-sent');assert((await page.locator('.r6-message').innerText()).includes('Proposal Sent requires'),'invalid stage movement not blocked');
await page.goto(`${base}/crm/opportunities/opp-montebello`,{waitUntil:'networkidle'});assert((await page.locator('[data-testid="crm-opportunity-detail"]').innerText()).includes(PROJECT),'linked solar project missing');assert((await page.locator('[data-testid="crm-proposal-followup"]').innerText()).includes('Exported'),'R5 proposal follow-up missing');await page.getByLabel('Opportunity stage').selectOption('negotiation');assert((await page.locator('[data-testid="crm-opportunity-detail"]').innerText()).includes('Negotiation'),'valid stage movement failed');
await page.getByLabel('Activity note').fill('Validated commercial call with customer.');await page.getByRole('button',{name:'Add activity'}).click();assert((await page.locator('[data-testid="crm-activity-timeline"]').innerText()).includes('Validated commercial call'),'activity creation failed');await page.getByLabel('Task title').fill('Validation follow-up task');await page.getByLabel('Task due date').fill('2026-09-08');await page.getByLabel('Task priority').selectOption('urgent');await page.getByRole('button',{name:/Add task/}).click();assert((await page.locator('[data-testid="crm-tasks"]').innerText()).includes('OVERDUE'),'overdue task state missing');
// Global task operations: overdue/project-linked task, keyboard-accessible completion control.
await page.goto(`${base}/crm`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Tasks'}).click();await page.getByLabel('Task bucket').selectOption('overdue');const taskOps=page.locator('[data-testid="crm-task-operations"]');assert((await taskOps.innerText()).includes('Validation follow-up task'),'global overdue task view missing project task');await taskOps.getByRole('button',{name:'Complete Validation follow-up task'}).focus();await page.keyboard.press('Enter');assert((await taskOps.innerText()).includes('Completed')||!(await taskOps.innerText()).includes('Validation follow-up task'),'keyboard task completion failed');
await page.goto(`${base}/crm/opportunities/opp-montebello`,{waitUntil:'networkidle'});assert((await page.locator('[data-testid="crm-activity-timeline"]').innerText()).includes('Validated commercial call'),'timeline did not persist');
await page.getByLabel('Loss reason').selectOption('loss-1');await page.getByRole('button',{name:/Mark lost/}).click();assert((await page.locator('.detail-status-strip').innerText()).includes('Lost'),'mark lost failed');await page.getByRole('button',{name:/Reopen opportunity/}).click();assert((await page.locator('.detail-status-strip').innerText()).includes('Negotiation'),'reopen failed');await page.getByRole('button',{name:/Mark won/}).click();const checklist=page.locator('[data-testid="crm-handoff-checklist"]');assert((await checklist.innerText()).includes('Sold / handoff pending'),'won did not create handoff pending');assert((await checklist.getByLabel('Delivery state').inputValue())==='Sold / handoff pending','won incorrectly auto-advanced installation readiness');
for(const itemLabel of ['Customer/contact data complete','Site information complete','Payment/contract status manually recorded','Interconnection/document requirements manually reviewed']){const sel=checklist.getByLabel(`Handoff ${itemLabel}`);await sel.selectOption('complete');}await checklist.getByLabel('Delivery state').selectOption('Commercial handoff complete');await checklist.getByLabel('Delivery state').selectOption('Technical handoff ready');assert((await checklist.getByLabel('Delivery state').inputValue())==='Technical handoff ready','handoff transition after required checklist failed');
await page.evaluate(()=>{const k='solar-platform-v2:r1:energy-profile',p=JSON.parse(localStorage.getItem(k));p.consumption=p.consumption.slice(0,2);p.updatedAt=new Date().toISOString();localStorage.setItem(k,JSON.stringify(p));});await page.reload({waitUntil:'networkidle'});assert((await page.locator('[data-testid="crm-blockers"]').innerText()).includes('r1-consumption'),'inherited R1 blocker not propagated');await page.goto(`${base}/projects/${PROJECT}`,{waitUntil:'networkidle'});assert(await page.locator('[data-testid="workspace-r6"]').isVisible(),'Workspace R6 strip missing');await page.goto(`${base}/crm`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Analytics'}).click();assert(await page.locator('[data-testid="crm-funnel"]').isVisible(),'analytics/funnel missing');await page.reload({waitUntil:'networkidle'});assert(await page.locator('[data-testid="crm-funnel"]').isVisible(),'CRM view preference persistence failed');await browser.close();console.log('R6 browser validation passed: project-centered table/search/source/proposal filters, configurable pipeline persistence, board accessible stage changes, detail/account/contact, timeline, global tasks/overdue/keyboard completion, R5 follow-up, lost/reopen/won, explicit handoff, inherited blockers, Workspace persistence and analytics/funnel.');
