import type {Coordinate2D,ModuleDimensions,Orientation,PolygonPoint} from './types';
export const EPS=1e-8;
export function signedPolygonArea(points:Coordinate2D[]){let sum=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];sum+=a.x*b.y-b.x*a.y;}return sum/2;}
export function polygonArea(points:Coordinate2D[]){return Math.abs(signedPolygonArea(points));}
export function pointInPolygon(p:Coordinate2D,poly:Coordinate2D[]){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(pointOnSegment(p,b,a))return true;const hit=((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x);if(hit)inside=!inside;}return inside;}
export function pointOnSegment(p:Coordinate2D,a:Coordinate2D,b:Coordinate2D){const cross=(p.y-a.y)*(b.x-a.x)-(p.x-a.x)*(b.y-a.y);if(Math.abs(cross)>1e-7)return false;const dot=(p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y);if(dot<0)return false;const len=(b.x-a.x)**2+(b.y-a.y)**2;return dot<=len+EPS;}
function orient(a:Coordinate2D,b:Coordinate2D,c:Coordinate2D){return Math.sign((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));}
export function segmentsIntersect(a:Coordinate2D,b:Coordinate2D,c:Coordinate2D,d:Coordinate2D){const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);if(o1!==o2&&o3!==o4)return true;return (o1===0&&pointOnSegment(c,a,b))||(o2===0&&pointOnSegment(d,a,b))||(o3===0&&pointOnSegment(a,c,d))||(o4===0&&pointOnSegment(b,c,d));}
export function polygonSelfIntersects(poly:Coordinate2D[]){if(poly.length<4)return false;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];for(let j=i+1;j<poly.length;j++){if(j===i||j===(i+1)%poly.length||i===(j+1)%poly.length)continue;if(i===0&&j===poly.length-1)continue;const c=poly[j],d=poly[(j+1)%poly.length];if(segmentsIntersect(a,b,c,d))return true;}}return false;}
function lineIntersection(a:Coordinate2D,b:Coordinate2D,c:Coordinate2D,d:Coordinate2D):Coordinate2D|null{const den=(a.x-b.x)*(c.y-d.y)-(a.y-b.y)*(c.x-d.x);if(Math.abs(den)<EPS)return null;const t=((a.x-c.x)*(c.y-d.y)-(a.y-c.y)*(c.x-d.x))/den;return{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)};}
export function offsetPolygon(points:PolygonPoint[],distance:number):PolygonPoint[]{if(points.length<3||distance<=0)return points.map(p=>({...p}));const ccw=signedPolygonArea(points)>0;const shifted:{a:Coordinate2D;b:Coordinate2D}[]=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;const nx=(ccw?-dy:dy)/len,ny=(ccw?dx:-dx)/len;shifted.push({a:{x:a.x+nx*distance,y:a.y+ny*distance},b:{x:b.x+nx*distance,y:b.y+ny*distance}});}return shifted.map((curr,i)=>{const prev=shifted[(i-1+shifted.length)%shifted.length];const p=lineIntersection(prev.a,prev.b,curr.a,curr.b)??curr.a;return{id:`off-${i}`,x:p.x,y:p.y};});}
export function bounds(points:Coordinate2D[]){return{minX:Math.min(...points.map(p=>p.x)),maxX:Math.max(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxY:Math.max(...points.map(p=>p.y))};}
export function moduleSize(dim:ModuleDimensions,o:Orientation){return o==='portrait'?{width:dim.width,height:dim.height}:{width:dim.height,height:dim.width};}
export function rectCorners(x:number,y:number,width:number,height:number){return[{x,y},{x:x+width,y},{x:x+width,y:y+height},{x,y:y+height}];}
export function rectInsidePolygon(x:number,y:number,width:number,height:number,poly:Coordinate2D[]){return rectCorners(x,y,width,height).every(p=>pointInPolygon(p,poly));}
export function polygonsOverlap(a:Coordinate2D[],b:Coordinate2D[]){if(a.some(p=>pointInPolygon(p,b))||b.some(p=>pointInPolygon(p,a)))return true;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++)if(segmentsIntersect(a[i],a[(i+1)%a.length],b[j],b[(j+1)%b.length]))return true;return false;}
export function translatePoints<T extends Coordinate2D>(pts:T[],dx:number,dy:number){return pts.map(p=>({...p,x:p.x+dx,y:p.y+dy}));}
export function snap(v:number,grid:number){return grid>0?Math.round(v/grid)*grid:v;}
