import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import App from './App';
import {I18nProvider} from './r7/i18n';
import {AuthProvider} from './r7/auth';
import {BrandProvider} from './r7/brand';
import {LegacyLocalizationBridge} from './r7/LegacyLocalizationBridge';
import './styles.css';
import './r1.css';
import './r2.css';
import './r2-fixes.css';
import './r3.css';
import './r4.css';
import './r5.css';
import './r6.css';
import './r7.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><I18nProvider><AuthProvider><BrandProvider><LegacyLocalizationBridge/><App/></BrandProvider></AuthProvider></I18nProvider></BrowserRouter></React.StrictMode>);
