import type {AcceptedProjectOutputs} from '../acceptedProjectOutputs';
import type {Proposal} from '../proposal/types';
import {proposalSourceFingerprint} from '../proposal/fingerprint';
import type {CrmProjectSummary,CrmState,Opportunity,CrmValidationIssue} from './types';
import {isOverdue,nextOpenTask} from './tasks';import {staleOpportunity} from './staleness';
export function projectSummary(outputs:AcceptedProjectOutputs,proposal:Proposal|null|undefined):CrmProjectSummary{
 const blockers:CrmValidationIssue[]=[];
 if(outputs.r1Quality!=='Ready for sizing')blockers.push({code:'r1-consumption',severity:'error',message:`R1 consumption: ${outputs.r1Quality}`,link:'/consumption'});
 if(!outputs.design.roofs.length||!outputs.design.layout.placements.length||outputs.design.layout.placements.some(p=>p.valid===false))blockers.push({code:'r2-design',severity:'error',message:'R2 design has no valid placed-module layout.',link:'/design'});
 if(outputs.r3Issues.some(i=>i.severity==='error'))blockers.push({code:'r3-electrical',severity:'error',message:'R3 has blocking electrical validation issues.',link:'/design'});
 if(!outputs.r3Summary.annualProductionKwh)blockers.push({code:'r3-production',severity:'error',message:'R3 production is unavailable.',link:'/design'});
 if(outputs.r4Economics.readiness==='Blocked')blockers.push({code:'r4-economics',severity:'error',message:'R4 economics is blocked.',link:'/economics'});
 const active=proposal?.versions.find(v=>v.id===proposal.activeVersionId);const fp=proposalSourceFingerprint(outputs),outdated=!!active&&active.sourceFingerprint!==fp;
 if(!active||!['Ready','Exported'].includes(active.status))blockers.push({code:'r5-proposal',severity:'warning',message:'R5 has no Ready/Exported active proposal.',link:'/proposal'});
 if(outdated)blockers.push({code:'r5-outdated',severity:'error',message:'R5 proposal source snapshot is out of date.',link:'/proposal'});
 return{projectId:outputs.design.projectId,annualConsumptionKwh:outputs.r1Metrics.annualKwh,targetDcKwp:outputs.design.targetDcKwp,placedModules:outputs.design.layout.placements.length,installedDcKwp:outputs.r3DcKwp,inverterLabel:outputs.inverterSpecs.map(x=>x.spec?.model||x.instance.specId).join(', '),annualProductionKwh:outputs.r3Summary.annualProductionKwh,sellPriceMxn:outputs.r4Economics.pricing.sellPriceBeforeVat,grossMarginPct:outputs.r4Economics.pricing.grossMarginPct,paybackYears:outputs.r4Economics.metrics.simplePaybackYears,irrPct:outputs.r4Economics.metrics.irrPct,npvMxn:outputs.r4Economics.metrics.npvMxn,technicalReadiness:blockers.some(b=>['r1','r2','r3'].some(p=>b.code.startsWith(p))&&b.severity==='error')?'Blocked':'Ready',economicReadiness:outputs.r4Economics.readiness,proposalVersion:active?.versionNumber,proposalStatus:active?.status,proposalExportedAt:active?.exportMetadata?.exportedAt,proposalOutdated:outdated,blockers};
}
export const valueOfOpportunity=(o:Opportunity,summaries:Map<string,CrmProjectSummary>)=>o.projectId?summaries.get(o.projectId)?.sellPriceMxn||0:0;
export function opportunityRows(state:CrmState,summaries:Map<string,CrmProjectSummary>,nowIso:string){const account=new Map(state.accounts.map(x=>[x.id,x])),owner=new Map(state.owners.map(x=>[x.id,x]));return state.opportunities.map(o=>{const tasks=state.tasks.filter(t=>t.link.opportunityId===o.id),next=nextOpenTask(tasks),stale=staleOpportunity(o,state,nowIso),summary=o.projectId?summaries.get(o.projectId):undefined;return{o,account:account.get(o.accountId),owner:owner.get(o.ownerId),summary,value:valueOfOpportunity(o,summaries),nextTask:next,overdueCount:tasks.filter(t=>isOverdue(t,nowIso)).length,stale}})}
export function filteredRows(state:CrmState,summaries:Map<string,CrmProjectSummary>,nowIso:string){const q=state.viewPrefs.search.toLowerCase();return opportunityRows(state,summaries,nowIso).filter(r=>(!q||`${r.o.name} ${r.account?.displayName||''} ${r.o.projectId||''}`.toLowerCase().includes(q))&&(!state.viewPrefs.stageId||r.o.stageId===state.viewPrefs.stageId)&&(!state.viewPrefs.ownerId||r.o.ownerId===state.viewPrefs.ownerId)&&(!state.viewPrefs.sourceId||r.o.sourceId===state.viewPrefs.sourceId)&&(!state.viewPrefs.status||state.viewPrefs.status==='all'||r.o.status===state.viewPrefs.status)&&(!state.viewPrefs.overdueOnly||r.overdueCount>0)&&(!state.viewPrefs.staleOnly||r.stale.stale)&&(state.viewPrefs.proposalFilter==='all'||(state.viewPrefs.proposalFilter==='sent'?['Exported'].includes(r.summary?.proposalStatus||''):r.summary?.proposalStatus!=='Exported')))}
