import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';import {api,ApiError} from './api';import {useAuth} from './auth';import {proposalBrandFromOrganization,assetUrlToDataUrl} from './proposalBrand';import {setRuntimeProposalBrand} from '../domain/proposal/runtimeBrand';import officialLogoUrl from '../assets/branding/buenos-dias-sol-by-enertika.png';
export type Brand={id:string;slug:string;displayName:string;shortName:string;legalName?:string|null;defaultLocale:'es-MX'|'en-US';defaultCurrency:'MXN'|'USD';timezone:string;tagline:string;primaryColor:string;secondaryColor:string;accentColor:string;graphiteColor:string;darkGraphiteColor:string;surfaceColor:string;website?:string|null;email?:string|null;phone?:string|null;footerText?:string|null;logoAssetId?:string|null;faviconAssetId?:string|null;proposalDefaults:Record<string,unknown>;version:number};
export const OFFICIAL_BRAND_LOGO_URL=officialLogoUrl;export const OFFICIAL_BRAND_LOGO_SHA256='92af3125cc33715e57c5f6129ae026eb9cf9ca9c75962ea5b3907fb0b74c10d5';export const OFFICIAL_BRAND_LOGO_WIDTH=2048;export const OFFICIAL_BRAND_LOGO_HEIGHT=682;export const OFFICIAL_BRAND_LOGO_ASPECT=OFFICIAL_BRAND_LOGO_WIDTH/OFFICIAL_BRAND_LOGO_HEIGHT;
export const DEFAULT_BRAND:Brand={id:'',slug:'buenos-dias-sol',displayName:'Buenos días sol by Enertika',shortName:'Buenos días sol',defaultLocale:'es-MX',defaultCurrency:'MXN',timezone:'America/Mexico_City',tagline:'Energía que conecta.',primaryColor:'#0295BF',secondaryColor:'#007FB8',accentColor:'#0780AD',graphiteColor:'#464647',darkGraphiteColor:'#3D4247',surfaceColor:'#FFFFFF',proposalDefaults:{},version:1};
const Ctx=createContext<{brand:Brand;status:'loading'|'ready'|'error';error?:ApiError;reload:()=>Promise<void>}|null>(null);
export function applyBrandTokens(brand:Brand,el:HTMLElement=document.documentElement){el.style.setProperty('--brand-primary',brand.primaryColor);el.style.setProperty('--brand-secondary',brand.secondaryColor);el.style.setProperty('--brand-accent',brand.accentColor);el.style.setProperty('--brand-graphite',brand.graphiteColor);el.style.setProperty('--brand-dark-graphite',brand.darkGraphiteColor);el.style.setProperty('--brand-surface',brand.surfaceColor);el.style.setProperty('--accent',brand.primaryColor);el.style.setProperty('--ink',brand.darkGraphiteColor)}
async function bundledLogoDataUrl(){try{return await assetUrlToDataUrl(officialLogoUrl)}catch{return undefined}}
async function applyProposalBrand(brand:Brand,organizationId?:string){let logoDataUrl:string|undefined;if(brand.logoAssetId&&organizationId){try{logoDataUrl=await assetUrlToDataUrl(api.assetUrl(organizationId,brand.logoAssetId))}catch{logoDataUrl=undefined}}if(!logoDataUrl&&brand.slug==='buenos-dias-sol')logoDataUrl=await bundledLogoDataUrl();setRuntimeProposalBrand(proposalBrandFromOrganization(brand,logoDataUrl))}
export function BrandProvider({children}:{children:React.ReactNode}){const {session}=useAuth();const [brand,setBrand]=useState<Brand>(DEFAULT_BRAND);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [error,setError]=useState<ApiError>();const reload=async()=>{if(!session){setBrand(DEFAULT_BRAND);setStatus('ready');await applyProposalBrand(DEFAULT_BRAND);return}setStatus('loading');try{const b=await api.brand(session.organizationId);setBrand(b);await applyProposalBrand(b,session.organizationId);setStatus('ready');setError(undefined)}catch(e){setError(e as ApiError);setStatus('error')}};useEffect(()=>{reload()},[session?.organizationId]);useEffect(()=>{applyBrandTokens(brand);document.title=`${brand.shortName} · Plataforma solar`},[brand]);const value=useMemo(()=>({brand,status,error,reload}),[brand,status,error]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useBrand(){const v=useContext(Ctx);if(!v)throw new Error('BrandProvider missing');return v}
export function BrandLogo({className=''}:{className?:string}){const {brand}=useBrand();const {session}=useAuth();const src=brand.logoAssetId&&session?api.assetUrl(session.organizationId,brand.logoAssetId):brand.slug==='buenos-dias-sol'?officialLogoUrl:undefined;if(src)return <img className={`r7-brand-logo ${className}`} src={src} alt={brand.displayName} width={OFFICIAL_BRAND_LOGO_WIDTH} height={OFFICIAL_BRAND_LOGO_HEIGHT}/>;return <div className={`r7-brand-fallback ${className}`} aria-label={`${brand.displayName} · activo oficial no cargado`}><strong>{brand.shortName}</strong><span>by Enertika</span><small>{brand.tagline}</small></div>}
