import type {ConsumptionValidation,DataQualityStatus,ProjectEnergyProfile} from './types';
import {requiresDemand,supportsPowerFactor} from './types';

const month=/^\d{4}-(0[1-9]|1[0-2])$/;
export function validateEnergyProfile(p:ProjectEnergyProfile):ConsumptionValidation[]{
  const issues:ConsumptionValidation[]=[]; const usable=p.consumption.filter(x=>month.test(x.period)&&Number.isFinite(x.kwh)&&x.kwh>0);
  if(usable.length<12)issues.push({code:'MIN_MONTHS',severity:'error',message:`At least 12 usable months are required; found ${usable.length}.`});
  const seen=new Set<string>(); for(const x of p.consumption){if(seen.has(x.period))issues.push({code:'DUPLICATE_PERIOD',severity:'error',message:`Duplicate billing period ${x.period}.`,period:x.period});seen.add(x.period);if(!month.test(x.period))issues.push({code:'PERIOD_FORMAT',severity:'error',message:`Unsupported period format ${x.period}. Use YYYY-MM.`,period:x.period});if(!Number.isFinite(x.kwh)||x.kwh<0)issues.push({code:'INVALID_KWH',severity:'error',message:`Invalid kWh for ${x.period}.`,period:x.period});else if(x.kwh===0)issues.push({code:'ZERO_KWH',severity:'warning',message:`Zero consumption in ${x.period}; verify source data.`,period:x.period});if(x.amountMxn!=null&&(!Number.isFinite(x.amountMxn)||x.amountMxn<0))issues.push({code:'INVALID_AMOUNT',severity:'error',message:`Invalid billed amount for ${x.period}.`,period:x.period});}
  const sorted=[...usable].sort((a,b)=>a.period.localeCompare(b.period)); for(let i=1;i<sorted.length;i++){const [py,pm]=sorted[i-1].period.split('-').map(Number);const d=new Date(py,pm,1);const expected=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(sorted[i].period!==expected)issues.push({code:'MISSING_PERIOD',severity:'warning',message:`Expected ${expected} between ${sorted[i-1].period} and ${sorted[i].period}.`});const ratio=sorted[i].kwh/sorted[i-1].kwh;if(ratio>1.8||ratio<.45)issues.push({code:'MONTH_JUMP',severity:'warning',message:`Large month-to-month change at ${sorted[i].period}.`,period:sorted[i].period});}
  if(requiresDemand(p.service.tariff)){const demandPeriods=new Set(p.demand.filter(x=>Number.isFinite(x.kw)&&x.kw>=0).map(x=>x.period));for(const x of usable)if(!demandPeriods.has(x.period))issues.push({code:'DEMAND_REQUIRED',severity:'error',message:`Demand is required for ${p.service.tariff} in ${x.period}.`,period:x.period});}
  if(supportsPowerFactor(p.service.tariff)){for(const pf of p.powerFactor){if(!Number.isFinite(pf.value)||pf.value<=0||pf.value>1)issues.push({code:'INVALID_PF',severity:'error',message:`Power factor must be > 0 and ≤ 1 for ${pf.period}.`,period:pf.period});else if(pf.value<.9)issues.push({code:'LOW_PF',severity:'warning',message:`Low power factor (${pf.value.toFixed(2)}) in ${pf.period}.`,period:pf.period});}}
  const total=usable.reduce((s,x)=>s+x.kwh,0);if(total<=0)issues.push({code:'ANNUAL_TOTAL',severity:'error',message:'Annual consumption total is not usable.'});
  if(!issues.length)issues.push({code:'VALID',severity:'info',message:'Profile is complete and deterministic checks passed.'}); return issues;
}
export function dataQualityStatus(issues:ConsumptionValidation[]):DataQualityStatus{if(issues.some(i=>i.code==='MIN_MONTHS'||i.code==='DEMAND_REQUIRED'||i.code==='INVALID_KWH'||i.code==='DUPLICATE_PERIOD'||i.code==='PERIOD_FORMAT'||i.code==='INVALID_PF'))return'Incomplete';if(issues.some(i=>i.severity==='warning'||i.severity==='error'))return'Needs review';return'Ready for sizing'}
